### ISSUE TITLE
Oracle database Mapping

### ISSUE THREAD

**Issue by tofarias** [laravel-doctrine/orm#100]
Hi, I generated entities from mysql database, it's work. But now I need do same in oracle database.
When I run this for one table:

vendor\bin\doctrine orm:convert:mapping --from-database -v --filter=USERS annotation domain

I get this:

![doctrine-orm-convert-mapping](https://cloud.githubusercontent.com/assets/7261216/11059910/d9675324-8783-11e5-8f4c-db66809cb101.PNG)

The "--filter" option not work?

**Comment by FoxxMD** [comment]
I believe your question is [specific to doctrine](https://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/tools.html#reverse-engineering) as laravel-doctrine does not cover this command. I would check to see if your usage of the filter option is working correctly -- [it uses `strpos` to define the array it is cast to and then uses a regular expression.](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Tools/Console/MetadataFilter.php) See [this write-up](http://blog.kowalczyk.cc/2011/11/11/symfony2-importing-entity-mapping-data-using-regular-expression-filters/) for more information on how to write a filter for this command.

**Comment by patrickbrouwers** [comment]
Does the table CK_LOG actually have a primary key? Because that's what it fails on.

**Comment by tofarias** [comment]
Ok, but I'm using the "--filter=users" option, the "--filter=users" should mapping only the "users" table, not?

**Comment by patrickbrouwers** [comment]
--filter expects a string pattern, so just users won't work I think.
In the mean time we have this command ourselves: `php artisan doctrine:convert:mapping`
