### ISSUE TITLE
Config files mapping example seems incorrect

### ISSUE THREAD

**Issue by matt-allan** [laravel-doctrine/orm#103]
Hey guys,

The config files mapping example in the docs looks like this:

```
'id'     => [
            'id' => [
                'type'     => 'integer',
                'strategy' => 'identity'
            ],
        ],
```

It should look like this:

```
'id'     => [
            'id' => [
                'type'     => 'integer',
                'generator' => [
                    'strategy' => 'auto'
                ],
            ],
        ],
```

Otherwise you get the error `If you want automatically generated identifiers instead you need to adjust the metadata mapping accordingly.` because the generator strategy isn't picked up.

**Comment by patrickbrouwers** [comment]
Can you make a PR? Thanks

**Comment by matt-allan** [comment]
Opened. https://github.com/laravel-doctrine/docs/pull/30
