### ISSUE TITLE
What features are missing?

### ISSUE THREAD

**Issue by bicatu** [laravel-doctrine/orm#104]
Hi,  I am trying to find out any limitations of the current 1.0 version.  I am about to start a new project and really want to use Doctrine with Laravel but I want to know any known problems or operations I can fulfill yet.

**Comment by patrickbrouwers** [comment]
That's very difficult to answer without knowing more about your project. You can better join us on Slack and ask specific questions about stuff you need. 

I'm using Laravel Doctrine in several big apps and it's working perfectly.
