### ISSUE TITLE
Automatically add metadata paths from packages

### ISSUE THREAD

**Issue by neon64** [laravel-doctrine/orm#105]
I had this problem with mitchellvanw's laravel doctrine package and I don't think this package is any different.

It is annoying to manually add paths to `config/doctrine.php`, especially when they are paths for packages you indirectly depend upon.

In some of my projects I have used a helper method inside a service provider that will append an item onto the `paths` array:

```
abstract class BaseServiceProvider extends ServiceProvider {

    /**
     * Register a directory of Doctrine entities.
     *
     * @param  string  $directory
     * @return void
     */
    public function loadEntitiesFrom($directory) {
        $metadata = $this->app['config']['doctrine.managers.default.paths'];
        $metadata[] = $directory;
        $this->app['config']->set('doctrine.managers.default.paths', $metadata);
    }

}
```

However this might stuff up deferred providers.

Is there a solution to this that you guys use?

**Comment by patrickbrouwers** [comment]
Example from the ACL package:

``` php

public function boot() {
    $this->app->make(DoctrineManager::class)->addPaths([
         __DIR__ . DIRECTORY_SEPARATOR . 'Permissions',
    ]);
}
```
