### ISSUE TITLE
How do I get the doctrine cache instance? 

### ISSUE THREAD

**Issue by EwanValentine** [laravel-doctrine/orm#107]
I'm using 2nd level caching for my entities, I'm set-up to use Redis. It's caching okay, but I need to be able to clear the caching when an entity is updated etc. I'm setting the cache with `useResultCache(true);`. However, I can't see from your documentation how you flush caches etc. 

Thanks!

**Comment by patrickbrouwers** [comment]
Just get it from the EntityManager, `$em->getCache();`

http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/second-level-cache.html#cache-api

**Comment by EwanValentine** [comment]
Wow, that easy! Thanks!
