### ISSUE TITLE
ENUM type error in doctrine:schema:validate

### ISSUE THREAD

**Issue by christiancannata** [laravel-doctrine/orm#108]
Hi guys,
I get this error when I try to validate my schema:

"Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it."

I have added this in my doctrine.php config file:
 'custom_types'              => [
        'json' => LaravelDoctrine\ORM\Types\Json::class,
        'enum' => Doctrine\DBAL\Types\StringType::class
    ],

but this not work.

How can I fix it?

**Comment by josenicomaia** [comment]
In order to solve it, I am using this snipet on AppServiceProvider.php:

``` php
    public function boot(\LaravelDoctrine\ORM\DoctrineManager $doctrineManager) {

        parent::boot();

        // Adding mapping server type to Doctrine type
        $doctrineManager->extendAll(function (\Doctrine\ORM\Configuration $configuration,
                \Doctrine\DBAL\Connection $connection,
                \Doctrine\Common\EventManager $eventManager) {

            $connection->getDatabasePlatform()->registerDoctrineTypeMapping('enum', 'string');
        });
    }
```

**Comment by josenicomaia** [comment]
I guess that it will solve your problem @christiancannata
