### ISSUE TITLE
Validation without DoctrinePresenceVerifier

### ISSUE THREAD

**Issue by mattcrowe** [laravel-doctrine/orm#110]
Is it possible to disable/prevent the registration of the \LaravelDoctrine\ORM\Validation\DoctrinePresenceVerifier? 

I'm trying to use this in a mixed environment, ie with Doctrine and Eloquent, and when I use Validator::make() I would rather use the original implementation. The DoctrineServiceProvider is basically choosing this Verifier for everything.

**Comment by josenicomaia** [comment]
There are so many ways to achieve it. But no one using configuration, just hacking.

But I will tell what should fit better to you.

AppServiceProvider.php

``` php
        $this->app->singleton('eloquent.validation.presence', function ($app) {
            return new \Illuminate\Validation\DatabasePresenceVerifier($app['db']);
        });

        $this->app->singleton('doctrine.validation.presence', \LaravelDoctrine\ORM\Validation\DoctrinePresenceVerifier::class);
```

When using the Validator

``` php
        Validator::setPresenceVerifier(\App::make('eloquent.validation.presence'));
        Validator::make();
```

``` php
        Validator::setPresenceVerifier(\App::make('doctrine.validation.presence'));
        Validator::make();
```

**Comment by josenicomaia** [comment]
@mattcrowe I hope this works haha. I didn't test it.

**Comment by patrickbrouwers** [comment]
@josenicomaia solution is a good one for this use case.
