### ISSUE TITLE
Builtin IBM_DB2 support

### ISSUE THREAD

**Issue by bskimball** [laravel-doctrine/orm#113]
I am currently using Atrauzzi laravel-doctrine, and have successfully configured it to work with the IBM_DB2 driver. I would like to migrate to this version but it looks like the IBM_DB2 driver is unsupported.

**Comment by josenicomaia** [comment]
I was looking here, and I guess that it is not so hard to do.

Create a Ibmdb2Connection like https://github.com/laravel-doctrine/orm/blob/1.0/src/Configuration/Connections/MysqlConnection.php using your actual atrauzzi's config.

PS: I have never used IBM_DB2

**Comment by patrickbrouwers** [comment]
You can use any connection driver you want, that's no problem. Only we won't add all drivers that exist, only the most commonly used.

Have a look at our documentation, it shows how you can add custom connection drivers: http://www.laraveldoctrine.org/docs/1.0/orm/connections

**Comment by bskimball** [comment]
Sweet I didn't see that section of the docs. I can post the config if I get it working. I will take the route Patrick suggested as I do not want to edit any files inside the vendor folder. Thanks to you both for the response.

**Comment by patrickbrouwers** [comment]
np :)

**Comment by bskimball** [comment]
I actually used josenicomaia's technique by creating a DB2Connection.php file, placing the IBM_DB2 driver options in that file. I then set the connection in my config file to 'db2'. This works great.

**Comment by patrickbrouwers** [comment]
You didnt add the file in the vendor folder right? Because it will be gone on the next composer update.

**Comment by bskimball** [comment]
Is the best approach to add a new service provider and place in the boot method?

**Comment by josenicomaia** [comment]
I suggested this approach wishing you make a PR with it.

But If you are not planing it, you have to put it on the boot method because what @patrickbrouwers said.

**Comment by bskimball** [comment]
I can make a PR, like I said, I already have it working with the separate file. In the mean time for my personal use I will add it to the boot method.

Sorry, for the misunderstanding, I'm new to this

**Comment by josenicomaia** [comment]
Great! We are all new on this. :smile: 
I have a slice on it. The important is that you are using it :D

**Comment by bskimball** [comment]
I'm following the instructions on the docs about adding the driver to the boot method and I'm getting this.
Argument 1 passed to App\Providers\AppServiceProvider::App\Providers\{closure}() must be an instance of App\Providers\Application, array given, called in /www/zendsvr6/htdocs/pmta-app/vendor/laravel-doctrine/orm/src/Configuration/Manager.php on line 103 and defined

Also, there seems to be a typo in the docs. The demo has $cache as the value, but inside the function it is using $connections.

**Comment by bskimball** [comment]
For anyone else looking to add IBM_DB2...

go to app/Providers/AppServiceProvider.php

add this to your boot method

``` php

    public function boot(ConnectionManager $connections)
    {
        $connections->extend('ibm_db2', function() {
            return [
               'driver' => 'ibm_db2',
                           'host' => 'localhost',
                       'dbname' => '<YourDatabaseName>',
                       'user' => '<YourUserName>',
                       'password' => '<YourPassword>',
                       'driverOptions' => [
                           'i5_lib' => '<YourLibraryName>',
                       ],
            ];
        });
    }

```

*note I am using DB2 on the IBM iSeries
