### ISSUE TITLE
L5.2 authentication

### ISSUE THREAD

**Issue by patrickbrouwers** [laravel-doctrine/orm#114]
From upgrade guide:

```
Custom Drivers

If you are using the Auth::extend method to define a custom method of retrieving users, you should now use Auth::provider to define your custom user provider. Once you have defined the custom provider, you may configure it in the providers array of your new auth.php configuration file.

For more information on custom authentication providers, consult the full authentication documentation.
```

Will become something like this:

```
$this->app->make('auth')->provider('doctrine', function ($app, $config) {

            $entity = $config['model'];

            $em = $app['registry']->getManagerForClass($entity);

            if (!$em) {
                throw new InvalidArgumentException("No EntityManager is set-up for {$entity}");
            }

            return new DoctrineUserProvider(
                $app['hash'],
                $em,
                $entity
            );
        });
```

**Comment by joshhornby** [comment]
@patrickbrouwers I seem to be having issues with the `auth` middleware in 5.2. I get the following error `No EntityManager is set-up for App\User` I have seen the issue https://github.com/laravel-doctrine/orm/issues/99 and followed your comments in there, but still doesn't seem to fix the issue.

```
app
    ...
    User.php
```

And my `User` class:

``` php
namespace App;

use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use \LaravelDoctrine\ORM\Auth\Authenticatable as AuthenticatableTrait;

class User implements AuthenticatableContract
{
    use AuthenticatableTrait;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;
}
```

My `auth.php` contains:

``` php
    'providers' => [
        'users' => [
            'driver' => 'doctrine',
            'model' => App\User::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],
```

My `doctrine.php` looks as follows:

``` php
            'namespaces' => [
                'App'
            ],
            'paths'      => [
                base_path('app'),
            ],
```

The stack trace can be seen below:

<img width="1277" alt="screenshot 2016-02-20 00 05 05" src="https://cloud.githubusercontent.com/assets/5455767/13192600/aa9b5aa4-d765-11e5-906f-bc29f2831703.png">

Any ideas? Am I missing something?

**Comment by joshhornby** [comment]
I have had another look and seems I was missing the ORM doc blocks:

``` php
/**
 * @ORM\Entity
 * @ORM\Table(name="users")
 */
```

This isn't very clear in the docs so will submit a PR this weekend.

**Comment by patrickbrouwers** [comment]
Agree that it's best to have it in the docs too, but on the other hand think when using doctrine you must know about adding the @ORM\Entity metadata to the class.

**Comment by firdausious** [comment]
Agree with @patrickbrouwers , must add @ORM\Entity metadata to the class on docs

**Comment by asimsagirabbasi** [comment]
i have receiving different error can anyone let me know where is issue
App\Entities\Admin and LaravelDoctrine\ORM\Auth\Authenticatable define the same property ($password) in the composition of App\Entities\Admin. However, the definition differs and is considered incompatible. Class was composed
