### ISSUE TITLE
Call to undefined method [setPresenceVerifier]

### ISSUE THREAD

**Issue by reyezmarc** [laravel-doctrine/orm#118]
Version: 1.0.14

Hello,

I got the following error when accessing the Validator make method:

```
BadMethodCallException in ServiceProvider.php line 234:
Call to undefined method [setPresenceVerifier]
in C:\xampp\htdocs\xxx\vendor\laravel\framework\src\Illuminate\Support\ServiceProvider.php line 234
at ServiceProvider->__call('setPresenceVerifier', array(object(DoctrinePresenceVerifier))) in C:\xampp\htdocs\xxx\vendor\laravel\framework\src\Illuminate\Validation\Factory.php line 99
at VanDeLeurFormBuilder->setPresenceVerifier(object(DoctrinePresenceVerifier)) in C:\xampp\htdocs\xxx\vendor\laravel\framework\src\Illuminate\Validation\Factory.php line 99
```

Any idea why this error occurs?

**Comment by patrickbrouwers** [comment]
At first I thought it could be: https://github.com/laravel-doctrine/orm/pull/115

But 1.0.14 is Laravel 5.1 only. 

Are you running Laravel 5.2?

Edit: but it seems `VanDeLeurFormBuilder` is calling `setPresenceVerifier`

**Comment by reyezmarc** [comment]
I'm running Laravel 5.1.

**Comment by patrickbrouwers** [comment]
Seems the problem lies with `VanDeLeurFormBuilder` (check the stack trace)

**Comment by reyezmarc** [comment]
Thanks for giving me directions to where to look at. Turned out I had a couple of namespace issues in that file.

**Comment by patrickbrouwers** [comment]
No problem. Enjoy the package! And join us on Slack if you have Doctrine questions!

**Comment by beingjungshahi** [comment]
I’m getting following error while installing acl.
[Illuminate\Contracts\Container\BindingResolutionException]  
Target [Doctrine\Common\Persistence\ManagerRegistry] is not instantiable while building [LaravelDoctrine\ORM\DoctrineManager].  
how can i fix this???

Santosh Jung Shahi
Balaju-16, Ktm
M:9841482507
E:adxantos@gmail.com

**Comment by patrickbrouwers** [comment]
Can you please create a dedicated issue for this, as it has nothing to do with this issue.
Alternatively you can ask for help on our Slack, which I highly recommend!

**Comment by beingjungshahi** [comment]
thank you so much sir
Santosh Jung Shahi
Balaju-16, Ktm
M:9841482507
E:adxantos@gmail.com
