### ISSUE TITLE
'exists' and 'unique' validation breaks with laravel/framework >=5.2.11

### ISSUE THREAD

**Issue by jwpage** [laravel-doctrine/orm#119]
Since 5.2.11, the Validator class has started calling PresenceVerifier::setConnection regardless of the arguments passed (see: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Validation/Validator.php#L1119)

The LaravelDoctrine DoctrinePresenceVerifier doesn't implement this method, so it breaks.

I don't think LaravelDoctrine really needs to handle changing the connection (this should be done on the Entity-level, no?), so simply adding an empty `public function setConnection($connection) {}` should fix it?

(Would have added a test case, but there's no tagged illuminate/validation release with the latest changes in it. Sorry!)

**Comment by patrickbrouwers** [comment]
Ugh more breaking changes in point releases. Even more annoyingly `setConnection` is not even on the contract.

And yes, the connection is handled on entity level.

Will see if I find some time to fix it.

**Comment by patrickbrouwers** [comment]
Fixed in 1.1.2. 
Also it supports rules like this `exists:manager2.App\User,id` with a custom manager now.

https://github.com/laravel-doctrine/orm/releases/tag/1.1.2

**Comment by jwpage** [comment]
Awesome, thank you! :smiley:

**Comment by ramseyjiang** [comment]
It still has the same problem in 5.2.45.
