### ISSUE TITLE
How to change naming strategy?

### ISSUE THREAD

**Issue by raygo22** [laravel-doctrine/orm#120]
Is there a way to change naming strategy in the configuration? I'm migrating some models from another framework, and everything was camelCase, now I'm getting errors because it's looking for fields with underscores in the database.

**Comment by patrickbrouwers** [comment]
Yes, you can set the naming strategy per entity manager with the key `naming_strategy`.

doctrine.php config:

```
'managers'                  => [
        'default' => [
            'naming_strategy' => YourNamingStrategy::class
            'dev'        => env('APP_DEBUG'),
            'meta'       => env('DOCTRINE_METADATA', 'annotations'),
            'connection' => env('DB_CONNECTION', 'mysql'),
            'namespaces' => [
                'App'
            ],
            'paths'      => [
                base_path('app')
            ],
           ....
      ]
]
```

Edit: if you need the default (camelCase); Doctrine\ORM\Mapping\DefaultNamingStrategy
