### ISSUE TITLE
Where can I define resolve_target_entities

### ISSUE THREAD

**Issue by reyezstef** [laravel-doctrine/orm#121]
Hello, I was wondering where I could define this config item: resolve_target_entities

as described in this manual:

http://symfony.com/doc/current/cookbook/doctrine/resolve_target_entity.html

I tried by modifying the config, but there doesn't seem to be a clear namespace defined for this and so I probably didn't define it at the right place. 

Regards

**Comment by patrickbrouwers** [comment]
Have a look at #86

**Comment by reyezstef** [comment]
Thank you will look into it

**Comment by reyezstef** [comment]
I have added the following extension:

```
<?php

namespace MyPackage\Core\Doctrine\Listeners;

use Doctrine\Common\Annotations\Reader;
use Doctrine\Common\EventManager;
use Doctrine\DBAL\Connection;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Tools\ResolveTargetEntityListener;
use LaravelDoctrine\ORM\Extensions\Extension;

class ResolveTargetEntityExtension implements Extension
{
    /**
     * @param EventManager           $manager
     * @param EntityManagerInterface $em
     * @param Reader|null            $reader
     */
    public function addSubscribers(EventManager $manager, EntityManagerInterface $em, Reader $reader = null)
    {
        $rtel = new \Doctrine\ORM\Tools\ResolveTargetEntityListener;

        dd(config('core.entities'),1);

        foreach(config('core.entities') as $interface=>$concrete)
        {
            dd($interface, $concrete);

            $rtel->addResolveTargetEntity($interface, $concrete, array());
        }

        $manager->addEventSubscriber(
            $rtel
        );
    }

    /**
     * @return array
     */
    public function getFilters()
    {
        return [];
    }
}
```

I have added a dd() to see if the actual extension is triggered. I have added this in my config:

```
    'extensions'                => [
        MyPackage\Core\Doctrine\Listeners\ResolveTargetEntityExtension::class,
```

But when accessing my User object in middleware, I get a class does not exist error and the extension is not executed. 

In the service provider bootExtensionManager function I see the following code is triggered, but I'm unsure if this is doing what is it is supposed to be doing:

```
       if (!$this->isLumen()) {
            $this->app->make(HttpKernel::class)->pushMiddleware(BootExtensions::class);

            return;
        }
```

Or I did configure something wrong. 

Hope you can help me out.

**Comment by reyezstef** [comment]
I got this working through command line. But when accessing an entity in middleware through http, it crashes with class does not exist error.

**Comment by reyezstef** [comment]
When I put this in the construct of the extension:

```
    public function __construct(){
        echo 1;
        exit;
    }
```

I see 1 through command line, but not via http.

**Comment by reyezstef** [comment]
The LaravelDoctrine\ORM\Extensions\ExtensionManager is booting after middleware it seems.

What I did to solve it is:

```
    protected function bootExtensionManager()
    {

        // If running in console we can boot immediately
        if (php_sapi_name() === 'cli') {
            $this->app->make(ExtensionManager::class)->boot();

            return;
        }

        // If running a HTTP Request in Laravel we want to push in middleware so we
        // boot after the session start. Some extensions make use of the session
        // to find out who the currently authenticated user is, e.g Loggable
        if (!$this->isLumen()) {
            $this->app->make(HttpKernel::class)->prependMiddleware(BootExtensions::class);

            return;
        }

        // Add BootExtension to the end of the Lumen middleware stack
        $this->app->middleware([BootExtensions::class]);
    }
```

I put in : prependMiddleware(BootExtensions::class), instead of pushMiddleware(BootExtensions::class)

Would it be possible to fix this for 5.1, would be highly appreciated. 

Update: 
I meant in the bootExtensionManager in DoctrineServiceProvider;

**Comment by patrickbrouwers** [comment]
I think you are doing something wrong in your code then. This works perfectly fine for me.

Are you calling the interface in another middleware perhaps?

**Comment by reyezstef** [comment]
Yes I call it in another middleware.

**Comment by patrickbrouwers** [comment]
I will have to investigate the impact of changing it to prepend.

**Comment by patrickbrouwers** [comment]
Will add it in next release

**Comment by patrickbrouwers** [comment]
Have reverted the commit, it breaks extension who need the session to be started. 

Edit: fixed it in another way. Resolve stuff should remain working.
