### ISSUE TITLE
Auth driver + Gedmo\Mapping\Annotation\Blameable

### ISSUE THREAD

**Issue by morfin** [laravel-doctrine/orm#123]
Hi, I'm trying to implement Auth, according to this: http://www.laraveldoctrine.org/docs/1.1/orm/auth. The problem is that when I change driver to "doctrine", I get this error when validating Doctrine schema: 

```
  [Doctrine\Common\Annotations\AnnotationException]
  [Semantical Error] The annotation "@Gedmo\Mapping\Annotation\Blameable" in property App\Model\User::$createdBy does not exist
  , or could not be auto-loaded.
```

This is my auth.php:

```
'providers' => [
        'users' => [
            'driver' => 'doctrine',
            'model' => App\Model\User::class,
        ]
]
```

The User model that implements Illuminate\Contracts\Auth\Authenticatable is using Blameable annotation in createdBy property.

Digging a little bit, I found that this is the call that causing the problem: $manager->getMetadataFactory()->getAllMetadata(), located at vendor/laravel-doctrine/orm/src/IlluminateRegistry.php Line 339

```
            if (!$manager->getMetadataFactory()->isTransient($class)) {
                foreach ($manager->getMetadataFactory()->getAllMetadata() as $metadata) {
                    if ($metadata->getName() === $class) {
                        return $manager;
                    }
                }
            }
```

Any idea?

**Comment by FoxxMD** [comment]
Are you using annotations only? Or are you using yaml/xml?

**Comment by morfin** [comment]
Only annotations.

**Comment by morfin** [comment]
Notice that laravel-doctrine auth instructions point to Laravel 5.1. Probably this hasn't been tested with 5.2

**Comment by patrickbrouwers** [comment]
https://github.com/laravel-doctrine/extensions/issues/22

**Comment by patrickbrouwers** [comment]
Next release should work in the normal order again
