### ISSUE TITLE
Issue with orm 1.1.4 and lumen 5.2.5

### ISSUE THREAD

**Issue by fabienkrubals** [laravel-doctrine/orm#126]
Hello.
I hope this is the correct process to submit an issue:

There is a little issue appearing in 1.1.4 of the ORM with Lumen (5.2.5)

It seems the change introduced in https://github.com/laravel-doctrine/orm/commit/68a25eb6764a072b8d72855a964788dec64885ff is the cause :

The lumen application context does not have 'booted' method.

[2016-02-23 16:35:00] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Call to undefined method Laravel\Lumen\Application::booted() in /home/vagrant/pay-service/vendor/laravel-doctrine/orm/src/DoctrineServiceProvider.php:46
Stack trace:
#0 /home/vagrant/pay-service/vendor/laravel/lumen-framework/src/Application.php(172): LaravelDoctrine\ORM\DoctrineServiceProvider->boot()
#1 /home/vagrant/pay-service/bootstrap/app.php(85): Laravel\Lumen\Application->register(Object(LaravelDoctrine\ORM\DoctrineServiceProvider))
#2 /home/vagrant/pay-service/vendor/phpunit/phpunit/src/Util/Fileloader.php(56): include_once('/home/vagrant/p...')
#3 /home/vagrant/pay-service/vendor/phpunit/phpunit/src/Util/Fileloader.php(38): PHPUnit_Util_Fileloader::load('/home/vagrant/p...')
#4 /home/vagrant/pay-service/vendor/phpunit/phpunit/src/TextUI/Command.php(804): PHPUnit_Util_Fileloader::checkAndLoad('/home/vagrant/p...')
#5 /home/vagrant/pay-service/vendor/phpunit/phpunit/src/TextUI/Command.php(633): PHPUnit_TextUI_Command->handleBootstrap('/home/vagrant/p...')
#6 /home/vagrant/pay-service/vendor/phpunit/phpunit/src/TextUI/Command.php(120): PHPUnit_TextUI_Command->handleArguments(Array)
#7 /home/vagrant/pay-service/vendor/phpunit/phpunit/src/TextUI/Command.php(109): PHPUnit_TextUI_Command->run(Array, true)
#8 /home/vagrant/pay-service/vendor/phpunit/phpunit/phpunit(47): PHPUnit_TextUI_Command::main()
#9 {main}

**Comment by patrickbrouwers** [comment]
Fixing it right now. Wish Lumen was more compatible with Laravel :'(

**Comment by patrickbrouwers** [comment]
Forgot to mention, but the fix was released couple of days back.

**Comment by fabienkrubals** [comment]
awesome :) 

thanks, seems functional now.
