### ISSUE TITLE
After Running Composer Update Fluent Class Does Not Exist

### ISSUE THREAD

**Issue by oddz** [laravel-doctrine/orm#130]
Using the most recent source this class does not exist in fluent repo but is referenced in this repo.

LaravelDoctrine\Fluent\Extensions\ExtensibleClassMetadataFactory

**Comment by oddz** [comment]
The class is referenced in this file.

src\Configuration\MetaData\Fluent.php

**Comment by oddz** [comment]
Anyone having this issue needs to use the fluent version: dev-extensions-support

**Comment by patrickbrouwers** [comment]
Our goal is to tag Fluent as 1.2 today with the extension support in it.

**Comment by oddz** [comment]
Cool, bad timing I guess on my end.

**Comment by patrickbrouwers** [comment]
Glad to hear that you like it :) 
And glad to hear someone using Fluent! :D

**Comment by felipeweb11** [comment]
Which the release date of fluent 1.2?

**Comment by patrickbrouwers** [comment]
Fluent version 1.1 is released.
