### ISSUE TITLE
[BUG] Password reset broken on 1.0.*

### ISSUE THREAD

**Issue by pmartelletti** [laravel-doctrine/orm#131]
### Package version, Laravel version

Using 1.0.18 and Laravel 5.1.31
### Expected behaviour

When trying to reset a password, an email should be sent to the user.
### Actual behaviour

Getting the following error:

> Argument 1 passed to LaravelDoctrine\ORM\Auth\Passwords\DoctrineTokenRepository::__construct() must implement interface Doctrine\ORM\EntityManagerInterface, null given, called in /home/pablo/Software/php/crm-exposed/vendor/laravel-doctrine/orm/src/Auth/Passwords/PasswordResetServiceProvider.php on line 63 and defined in DoctrineTokenRepository.php line 34

@patrickbrouwers  any ideas of what could be wrong? Please not that we would like to stick to Laravel 5.1, hence why we are using version 1.0.*

**Comment by pmartelletti** [comment]
@patrickbrouwers any comments?

**Comment by FoxxMD** [comment]
Can you check that in your `providers` in `config/app.php` that 

``` php
LaravelDoctrine\ORM\Auth\Passwords\PasswordResetServiceProvider
```

is listed after 

``` php
LaravelDoctrine\ORM\DoctrineServiceProvider
```

**Comment by pmartelletti** [comment]
@FoxxMD  I can't be so stupid... Thanks for that!
