### ISSUE TITLE
Doctrine Fixture/Seeding Support

### ISSUE THREAD

**Issue by oddz** [laravel-doctrine/orm#136]
It would be nice to have seeding/fixtures that are compatible with Laravel doctrine. I'm researching options for my own project which lead me to this blog article.

http://culttt.com/2014/06/30/getting-started-doctrine-2-laravel/

In the comments an individual asks about using fixtures with doctrine and author cites these two sources as possibilities.

https://github.com/fzaninotto/Faker#populating-entities-using-an-orm-or-an-odm
https://github.com/doctrine/data-fixtures

Since faker is already included I think a simple approach would be to replace or offer an alternative for the doctrine seeding and factory generation. One of the nice things is that doctrine is already supported by faker unlike Eloquent. 

The second package is nice but I think is a little dated and doesn't integrate quite as nicely with Laravel. However, I also came across this package.

https://github.com/nelmio/alice

Using alice is probably the approach I'm going to take since it seems very powerful. It also always defining fixture data as yaml or php which is nice for the Laravel folks who want to keep everything in php. Alice already has a bridge for many other packages why not Laravel.

Just something to think about. It would would nice to support the entire gamut of Eloquent functionality including the seeding and factories.

**Comment by FoxxMD** [comment]
I currently use alice for seeding and testing, it works like a champ. 

However, installation/use didn't require any extra steps to use it with LD. Is there something more you think LD should be doing to facilitate use of alice or faker?

**Comment by oddz** [comment]
I'm not quit sure as I have just began exploring alices usage.

**Comment by oddz** [comment]
The first problem I have run into is using bcrypt within alice yml files.

**Comment by oddz** [comment]
I believe I have figured this out.

I create a console command to load in seeds. Currently only user data.

```
<?php

namespace Modules\Core\Console\Commands;

use Illuminate\Console\Command;
use Nelmio\Alice\Fixtures;
use Modules\Core\Faker\Provider\Helpers;
use Modules\Core\Faker\Provider\Carbon;
use Faker\Generator;
use Doctrine\ORM\EntityManagerInterface;

class SeedDatabase extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'core:seed';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Seed the database.';

    protected $em;

    public function __construct(EntityManagerInterface $em) {

        parent::__construct();

        $this->em = $em;

    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle() {

        $file = database_path('fixtures/base-data/users.yml');

        $generator = new Generator();
        $providers = [
            new Helpers($generator),
            new Carbon($generator),
        ];

        $objects = Fixtures::load($file, $this->em,[
            'providers'=> $providers
        ]);
        
    }
}
```

I created two custom providers and hooked them up with alice/faker. On eexposed bcrypt and the other carbon::now.

```
<?php namespace Modules\Core\Faker\Provider;

use Faker\Provider\Base;
use Carbon\Carbon as ActualCarbon;

/*
 * Use carbon dates.
 */
class Carbon extends Base {

    public function carbon_now() {

        return ActualCarbon::now();

    }

}
```

```
<?php namespace Modules\Core\Faker\Provider;

use Faker\Provider\Base;

/*
 * Expose Laravel helpers to faker.
 */
class Helpers extends Base {

    public function bcrypt($value, $options = []) {

        return bcrypt($value,$options);

    }

}
```

My user yml file than look like this which seems to load without error.

```
Modules\Core\Entities\User:
  user0:
    email: test3@gmail.com
    password: <bcrypt('-Password1')>
    createdAt: <carbon_now()>
    updatedAt: <carbon_now()>
  user1:
    email: test2@gmail.com
    password: <bcrypt('-Password1')>
    createdAt: <carbon_now()>
    updatedAt: <carbon_now()>
  user2:
    email: test1@gmail.com
    password: <bcrypt('-Password1')>
    createdAt: <carbon_now()>
    updatedAt: <carbon_now()>
```

If there is a better way to do it I'm all ears.

**Comment by FoxxMD** [comment]
> I think you're right though. Doesn't seem there is much need for a bridge here.

Right. Your command looks nice and I'm sure this would be super helpful to laravel/doctrine users but it doesn't fit the scope of laravel-doctrine/orm. Perhaps consider publishing your own package that provides this command (and providers) and use laravel-doctrine/orm as a dependency? :) We could add a section in our docs like "Packages Using LD" and include your project there.

**Comment by oddz** [comment]
Working through it I think it is better suited as a recipe than a new provider. However, if I get to the point where it warrants a reusable provider I will let you know. Thanks.
