### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by reyezJelle** [laravel-doctrine/orm#137]
Is there a way to set the characterencoding for mssql server. It seems that setting the property in config/database.php doesn't have an effect.

// config/database.php
  'sqlsrv' => [
            'driver'   => 'sqlsrv',
            'host'     => env('DB_HOST', 'localhost'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset'  => 'Latin1_General_CI_AS',
            'prefix'   => '',
        ],

**Comment by patrickbrouwers** [comment]
You'll have to add a pull-request to add `charset` to `LaravelDoctrine\ORM\Configuration\Connections\SqlsrvConnection`

**Comment by patrickbrouwers** [comment]
Will be added to next release
