### ISSUE TITLE
Proxy configuration occurs in wrong place

### ISSUE THREAD

**Issue by FoxxMD** [laravel-doctrine/orm#14]
I had to stick my `’proxies’ => [ ]` in the `’meta`’ array in my config in order for the EM to pick up my custom path for proxies, but the default config shows `proxies` as going inside a `manager` array.

[Here](https://github.com/laravel-doctrine/orm/blob/develop/src/DoctrineServiceProvider.php#L114) the EM is created and resolves proxy settings from the `meta` key in the manager array (by getting the settings and driver from the `meta` array in config). So if we don’t have proxies in the meta array under the driver we are using it uses defaults

[However farther down](https://github.com/laravel-doctrine/orm/blob/develop/src/DoctrineServiceProvider.php#L159) the EM setup function we set proxies settings from the correct key in the manager array, but it doesn’t do anything!

Any suggestions @patrickbrouwers?

**Comment by patrickbrouwers** [comment]
I'm wondering why we would even want to have a separate storage for proxies per manager. Perhaps it just best do keep it at once place. That will solve that problem.

**Comment by FoxxMD** [comment]
It's like that in [the default config](https://github.com/patrickbrouwers/Laravel-Doctrine/blob/master/config/doctrine.php#L28)

I could see it being useful if I have one set of entities that are mature and don't need to be autogenerated, but am working on another set (with a different EM) where I want them autogenerated. 

But I guess it ain't too practical. You think it would be better to keep it all in the `meta` root section?

**Comment by patrickbrouwers** [comment]
Well it seems it's not possible to overrule the proxy per manager. (Strange). 

Autogenerated is only on dev env anyway.

**Comment by patrickbrouwers** [comment]
This should be fixed with dfe3c170fc19bf78fcf3dc82925763650a97e788 I think.
