### ISSUE TITLE
[QUESTION] generate mapping files extension mismatch?

### ISSUE THREAD

**Issue by jaccoTopVintage** [laravel-doctrine/orm#141]
### Package version: 1.1, Laravel version: 5.2

Hi,

In file `vendor/laravel-doctrine/orm/src/Console/MappingImportCommand.php` at line `81`, the output filename for mappings files is set to `.'.orm.'.$type;`

The result is that the console command:

`php artisan doctrine:mapping:import`

generates **`.orm.xml`** or **`.orm.yaml`** files.

<br>
However, the console command: 

`php artisan doctrine:generate:entities`

expects **`.dcm.xml`** or **`.dcm.yaml`** files.

<br>
Is this an intentional mismatch? if so, what is the intended difference between the two file extensions?

**Comment by jaccoTopVintage** [comment]
I've narrowed the issue down to method `getAllClassNames($globalBasename)` in file `vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\Driver\DefaultFileLocator.php` at line `126`.

The command:
`php artisan doctrine:mapping:import xml database/mappings`
produces `.orm.xml` files, while the `getAllClassNames()` method is looking for `.dcm.xml` files.

With this additional information, could anyone maybe point us in the right direction?

**Comment by patrickbrouwers** [comment]
Why did you empty this issue?

**Comment by jaccoTopVintage** [comment]
because I was in the process of updating it with more in-depth information, thereby rephrasing my question.

Sorry for confusing you with the intermediate step.

**Comment by patrickbrouwers** [comment]
Can you make a PR to make that a console setting?

**Comment by jaccoTopVintage** [comment]
I'm not sure that making the extension-type an console setting will fix the issue.

It seems that the **`.dcm.xml`** extension is for the `xml` driver,
while the **`.orm.xml`** extension is for the `SimplifiedXml` driver.

source: [doctrine/reference/xml-mapping](https://doctrine-orm.readthedocs.org/en/latest/reference/xml-mapping.html)

**Comment by jaccoTopVintage** [comment]
So, some 4 hours later...

**Note:** We tried using yaml files as well; the resulting errors and solutions are the same for both `.xml` and `.yml` files, so wherever I write `.xml`, you could read `.yml`.

<br>
There seems to be an issue which is related to namespaces.

Our Laravel app is organized as follows:

```
[project]
   +- [App]
       +- [Entites]
   +- [database]
       +- [mappings]
```

We created our mappings files using console command:

`php artisan doctrine:mapping:import xml database\mappings`

renamed our mappings files from **`.orm.xml`** into **`.dcm.xml`**.

We then proceeded to create our entities using console command:

`php artisan doctrine:generate:entities`

Which created our entities in folder `app/entities`, as expected. Finally, we manually added our namespace `namespace App\Entities;` to each of the entities files.

**However**

In order to make both the console commands work, we needed to make changes to the file:
`vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/FileDriver.php`

The changed lines are in method `getElement()`  (introducing the variable: `$classNameBase`):

```
    public function getElement($className)
    {
        if ($this->classCache === null) {
            $this->initialize();
        }

        if (isset($this->classCache[$className])) {
            return $this->classCache[$className];
        }

        $result = $this->loadMappingFile($this->locator->findMappingFile($className));

        $classNameBase = explode('\\', $className);
        $classNameBase = end($classNameBase);
        if (!isset($result[$classNameBase])) {
           throw MappingException::invalidMappingFile($className, $classNameBase . $this->locator->getFileExtension());
        }

        return $result[$classNameBase];
    }
```

All in all, this feels like a rather ugly hack, which somehow suggests that the use `.xml` (or `.yml`) files mappings instead of annotations are not (yet) fully supported by laravel-doctrine?

Is this a known issue? or are we the first to report this?

Do you guys see any potential solution for this that would work without modifying the Doctrine2 files directly (but rather provide the solution within the `laravel-doctrine/orm` files)?

Cheers,
Jacco

**Comment by jaccoTopVintage** [comment]
The mapping file extension mismatch is due to the use of the `XML` driver

```
// File: config/doctrine.php
'meta' => 'Xml',
```

The XML driver expects two things (both of which are currently not supplied by the `mappings:import` console script):
- generated files should have the extension: `.dcm.xml`,
- generated files should have their namespace prefixed to the filename, for example: `App.Entities.Nnnnnnnnnnnnn.dcm.xml`

---

When using the `SimplifiedXML` driver:

```
// File: config/doctrine.php
'meta' => 'SimplifiedXml',
```

the imported mapping files are Ok as is.

**Comment by patrickbrouwers** [comment]
It indeed seems the mapping import uses `orm` in favour of `dcm`, which probably has to do with the fact the command has been ported from Symfony. 
This issue will be fixed with: https://github.com/laravel-doctrine/orm/commit/d2b647a3b95c243c01755a5027585e4f1238f532
