### ISSUE TITLE
[QUESTION]dql works with artisan, not working with apache

### ISSUE THREAD

**Issue by GiorgioZett** [laravel-doctrine/orm#142]
[QUESTION].

laravel-doctrine/orm": 1.1.9, laravel : 5.2.29

I'm new to laravel and doctrine 2.
I have done some works and some test, but I have a strange issue.
There is a controller, there is a simple DQL query that works if I use artisan serve, but the same query is broken when local apache serve laravel web app.
When I use apache server, laravel home page works, and  api's work, too.
I checked config/doctrine.php, and I made some test with different base path and namespace, but it  always fails.

This is the request stack trace :

```
[Semantical Error] line 0, col 33 near &#039;app\Entities\Accessi&#039;: Error: Class &#039;app\Entities\Accessi&#039; is not defined
       <li> in <a title="/home/giorgio/progetti/ngtem/backend/ngtem/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">QueryException.php line 63</a></li>
       <li>at <abbr title="Doctrine\ORM\Query\QueryException">QueryException</abbr>::semanticalError('line 0, col 33 near &#039;app\Entities\Accessi&#039;: Error: Class &#039;app\Entities\Accessi&#039; is not defined.', <em>object</em>(<abbr title="Doctrine\ORM\Query\QueryException">QueryException</abbr>)) in <a title="/home/giorgio/progetti/ngtem/backend/ngtem/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php line 483" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Parser.php line 483</a></li>
       <li>at <abbr title="Doctrine\ORM\Query\Parser">Parser</abbr>->semanticalError('Class &#039;app\Entities\Accessi&#039; is not defined.', <em>array</em>('value' => 'app\Entities\Accessi', 'type' => '100', 'position' => '33')) in <a title="/home/giorgio/progetti/ngtem/backend/ngtem/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php line 971" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Parser.php line 971</a></li>
       <li>at <abbr title="Doctrine\ORM\Query\Parser">Parser</abbr>->AbstractSchemaName() in <a title="/home/giorgio/progetti/ngtem/backend/ngtem/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php line 1702" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Parser.php line 1702</a></li>
       <li>at <abbr title="Doctrine\ORM\Query\Parser">Parser</abbr>->RangeVariableDeclaration() in <a title="/home/giorgio/progetti/ngtem/backend/ngtem/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php line 1557" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Parser.php line 1557</a></li>
       <li>at <abbr title="Doctrine\ORM\Query\Parser">Parser</abbr>->IdentificationVariableDeclaration() in <a title="/home/giorgio/progetti/ngtem/backend/ngtem/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php line 1292" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Parser.php line 1292</a></li>
       <li>at <abbr title="Doctrine\ORM\Query\Parser">Parser</abbr>->FromClause() in <a title="/home/giorgio/progetti/ngtem/backend/ngtem/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php line 874" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Parser.php line 874</a></li>
       <li>at <abbr title="Doctrine\ORM\Query\Parser">Parser</abbr>->SelectStatement() in <a title="/home/giorgio/progetti/ngtem/backend/ngtem/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php line 843" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Parser.php line 843</a></li>
       <li>at <abbr title="Doctrine\ORM\Query\Parser">Parser</abbr>->QueryLanguage() in <a title="/home/giorgio/progetti/ngtem/backend/ngtem/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php line 268" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Parser.php line 268</a></li>
       <li>at <abbr title="Doctrine\ORM\Query\Parser">Parser</abbr>->getAST() in <a title="/home/giorgio/progetti/ngtem/backend/ngtem/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php line 351" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Parser.php line 351</a></li>
       <li>at <abbr title="Doctrine\ORM\Query\Parser">Parser</abbr>->parse() in <a title="/home/giorgio/progetti/ngtem/backend/ngtem/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php line 281" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Query.php line 281</a></li>
       <li>at <abbr title="Doctrine\ORM\Query">Query</abbr>->_parse() in <a title="/home/giorgio/progetti/ngtem/backend/ngtem/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php line 293" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Query.php line 293</a></li>
       <li>at <abbr title="Doctrine\ORM\Query">Query</abbr>->_doExecute() in <a title="/home/giorgio/progetti/ngtem/backend/ngtem/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php line 969" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">AbstractQuery.php line 969</a></li>
       <li>at <abbr title="Doctrine\ORM\AbstractQuery">AbstractQuery</abbr>->executeIgnoreQueryCache(<em>null</em>, '1') in <a title="/home/giorgio/progetti/ngtem/backend/ngtem/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php line 924" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">AbstractQuery.php line 924</a></li>
       <li>at <abbr title="Doctrine\ORM\AbstractQuery">AbstractQuery</abbr>->execute(<em>null</em>, '1') in <a title="/home/giorgio/progetti/ngtem/backend/ngtem/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php line 727" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">AbstractQuery.php line 727</a></li>
       <li>at <abbr title="Doctrine\ORM\AbstractQuery">AbstractQuery</abbr>->getResult()
```

Do you have any idea about this?
Thanks a lot!

**Comment by FoxxMD** [comment]
What is your local environment and what environment is the break happening in? (OSX, Windows, *nix)

If you are using environmental variables have you checked that they are populated/being recognized by the apache server?

**Comment by GiorgioZett** [comment]
thanks for the quick reply!
so...
ubuntu 14
apache 2.4.7
I use .env config file, but there is no doctrine config in it.
About apache conf: there is an alias (ngtem) to serve laravel public folder.
all apache alias conf seems right.
There is an .htaccess file in the public folder.
I added this line in it: 
`RewriteBase /ngtem`
`ngtem`  is apache alias.
I added cors middleware, it works well, otherwise others apis would fail.
it seems a class loading issue, but I can't understand where could be the wrong conf.

**Comment by patrickbrouwers** [comment]
Sure your autoloading is set-up correctly?

**Comment by GiorgioZett** [comment]
I created a doctrine.php in app/config folder.
I changed this:
`'paths'      => [
                base_path('app/Entities')
            ],`
and removed namespace entry.
Entities are in app/Entities folder.
others settings are the same as doctrine.php in vendor/laravel-doctrine/orm/config
Is there any other autoloader to setup in laravel or doctrine configuration I can check?
thanks

**Comment by FoxxMD** [comment]
I'm still not entirely sure what the problem is. Can you clarify this:

> works if I use artisan serve
> broken when **local apache** serve laravel web app
> When I use **apache server**, laravel home page works, and api's work, too.

Are there two apache servers? Is one of them in a different environment? Can you clear that up?

> I changed this:
> 'paths' => [ base_path('app/Entities') ],

Changed to what?

Have you tried running `php composer dump-autoload`?

**Comment by GiorgioZett** [comment]
local apache and apache server means my local apache instance, so just one apache instance.
I mean when I use built-in apache server (artisan) all works fine.
If I add alias to apache, to serve laravel app by apache, the first DQL query is broken, with the stack trace I paste in the first message .
I tried to run dump-autoload, but nothing change.
Is there a better (or correct) solution to serve laravel app by apache?
In my apache instance there are others web apps, so I can't change document root to laravel public folder.
thanks

**Comment by FoxxMD** [comment]
> I can't change document root to laravel public folder.
> `RewriteBase /ngtem`

I have a feeling this is your problem.

So, correct me if I'm wrong, your app structure looks like this?

```
backend/ngtem/
 - app/
 - bootstrap/
 - config/
 ...
```

Try having your alias point to `backend/ngtem/public/`. I know there is a `server.php` file in the root dir but I'm fairly certain `artisan serve` is setting its base in `public/`.

Also, ensure you have psr-4 or psr-0 configurations setup correctly in `composer.json`.

Btw, you should consider using [vhosts for apache](https://httpd.apache.org/docs/current/vhosts/examples.html) so you can set a document root normally.

**Comment by guiwoda** [comment]
@GiorgioZett Can you paste your DQL as well?

Is your entity on namespace `App\Entities` or `app\Entities`? Because the error says it's trying to look for (lowercase) `app\Entities\Accesi`
