### ISSUE TITLE
[QUESTION] Driver [] not supported.

### ISSUE THREAD

**Issue by drsect0r** [laravel-doctrine/orm#146]
Got the following exception after following the installation located at http://www.laraveldoctrine.org/docs/1.1/orm/installation.

``` php
LaravelDoctrine\ORM\Exceptions\DriverNotFound
Driver [] not supported.
```

``` shell
$ php artisan -V
Laravel Framework version 5.2.31
```

**Comment by patrickbrouwers** [comment]
Can you show me your doctrine.php config

**Comment by drsect0r** [comment]
@patrickbrouwers I tried to replicate and it is working now.
