### ISSUE TITLE
[QUESTION] Example project?

### ISSUE THREAD

**Issue by appkr** [laravel-doctrine/orm#147]
Is there a complete example (Github repository) that I can understand how to use this project? That would be super helpful to get started quickly. 

I've been reading the document and tried to follow along for more than 24 hours, but was not successful even implementing simple CURD with mysql. ): I think that is because I don't have experience in Doctrine~

**Comment by patrickbrouwers** [comment]
https://github.com/laravel-doctrine/Laravel-Doctrine-Quickstart

It's also advisable to follow some tutorials about Doctrine to get your head around the concept.

**Comment by appkr** [comment]
Thank you! I'll study it this night and update the fact how it helped.

**Comment by appkr** [comment]
I went through the diff. Now I start understand the usage. Thanks a lot!
