### ISSUE TITLE
[BUG] Configuration for mappings path ignored by mappingsImportCommand

### ISSUE THREAD

**Issue by Jacco-V** [laravel-doctrine/orm#151]
### Version Info

Package v1.1.10,
Laravel v5.2.
### Expected behaviour

Having specified my `config/doctrine.php` file as follows (petty much the unchanged from the default):

```
return [
    'managers'                  => [
        'default' => [
            'dev'        => env('APP_DEBUG'),
            'meta'       => env('DOCTRINE_METADATA', 'SimplifiedXml'),
            'connection' => env('DB_CONNECTION_DEFAULT', 'default'),
            'namespaces' => [
                'App\Entities'
            ],
            'paths'      => [
                base_path('database/mappings') => 'App\Entities',
            ],

            // (...)
        ]
    ]
];
```

I would expect the console command: `php artisan doctrine:mapping:import` to write the mapping information into the directory: `database/mappings/NameOfTable.orm.xml`
### Actual behaviour

Because in [MappingImportCommand.php:43](https://github.com/laravel-doctrine/orm/blob/1.1.10/src/Console/MappingImportCommand.php#L43) the default is hardcoded as `'app/Mappings'`, the mapping information is written to `app/Mappings/NameOfTable.orm.xml` instead.
### Steps to reproduce the behaviour

Create a new project, include laravel-doctrine with its default configuration, add some table to your standard database, run console command `php artisan doctrine:mapping:import`

**Comment by patrickbrouwers** [comment]
Please make a PR for these changes.

**Comment by patrickbrouwers** [comment]
Closing this for now (see PR). Might revisit this in the future (major release). For now I think using the {dest-path} argument is good enough.
