### ISSUE TITLE
[QUESTION][BUG] Laravel Doctrine inside a Job (when running the listener as a daemon using supervisord)

### ISSUE THREAD

**Issue by chancezeus** [laravel-doctrine/orm#152]
### Package version

1.1.8
### Laravel version

5.2.22

I'm currently working on a project where I need to be able to offload a couple of commands using the queue runner and jobs.
In another project I worked on previously I ran into issues where it was impossible to do so using the laravel-doctrine, because after a while (when the jobs had little to no work to do) the database timed out and disconnected. The problem was that I could not find a way to (a) detect this situation and (b) reconnect to the database, since the project needed to be finished and I wasn't relying on the query builder, DQL or doctrine specific functionality I rewrote the entire project to use Eloquent.
For the project I'm currently working on this is not an option since it uses the doctrine ORM, query builder and DQL more extensively to build queries that aggregate data and information from the database in such a way that using eloquent would result in dozens if not hundreds of extra queries against the database (the doctrine queries used have been analyzed and optimized to run as fast as possible using the proper indexes/lookups/etc so temp table creation and other slow operations (table scans) are either minimal (max 1 temp table for sorting the data returned to the process) or non-existent).
### Expected behaviour

The database silently reconnects or there is a way to detect the timeout condition and reconnect manually
### Actual behaviour

The connection gets dropped on the database side and there is no way to detect it or issue a reconnect
### Steps to reproduce

Create a Job that uses the EntityManager to query or update items in the database. Start a daemon worker process `php artisan queue:work [queue] --sleep=3 --tries=3 --daemon`.
Schedule a job on the queue and after being idle for at least `wait_timeout` seconds (the default wait_timeout is 8 hours, but can be set in the config or through the mysql `set global` command) schedule another one, since the daemon keeps running inside the same laravel container/process the database has timed out (because there were no queries) and the job fails.

**Comment by patrickbrouwers** [comment]
Take a look at this package made by @maxbrokman https://github.com/maxbrokman/SafeQueue  I think it solves this problem.

**Comment by chancezeus** [comment]
Nice one, the only thing I notice it that it actually relies on the fact that an `EntityManager is closed` exception is being thrown and restarting the worker. This is a way to handle the problem, but in my opinion there should be an option to handle this using Doctrine/the EntityManager itself and not by restarting the worker.

As a way to look at it:
**The proposed solution**
You have a car that can be turned on once, without a way to tell if it is still running or restart it.
You use the car till it breaks down
You replace the car with the same car and try again

**The proper solution**
You have a car that can be turned on and restarted.
There is a warning light that tells you the car is still running.
If the car stops running you can either (a) start it again manually or (b) it starts itself again when needed

**Comment by patrickbrouwers** [comment]
@maxbrokman 

http://stackoverflow.com/questions/14060507/doctrine2-connection-timeout-in-daemon

**Comment by chancezeus** [comment]
Thanks :) I'll give it a try

**Comment by patrickbrouwers** [comment]
Actually I think the package already does what you need:

https://github.com/maxbrokman/SafeQueue/blob/master/src/Worker.php#L86

Before every job is executed, it makes sure the connection is running. If not, it will re-connect.

**Comment by patrickbrouwers** [comment]
@chancezeus any news on this?

**Comment by maxbrokman** [comment]
@chancezeus I think I've changed it since you last looked at it, it now checks if the EM is open before working a job.

I'll probably get the package to a tagged version in the near future
