### ISSUE TITLE
[BUG] --filter for doctrine:mapping:import command does not accept a value

### ISSUE THREAD

**Issue by Jacco-V** [laravel-doctrine/orm#153]
### Package version, Laravel version

Package v1.1.10,
Laravel v5.2.

When trying to import a specific table by using doctrine's --filter argument, the argument fails because it does not accept any value
### Expected behaviour

```
php artisan doctrine:mapping:import --filter=users
  > writing /app/Mappings/Users.orm.xml
```
### Actual behaviour

```
php artisan doctrine:mapping:import --filter=users

  [Symfony\Component\Console\Exception\RuntimeException]
  The "--filter" option does not accept a value.
```
### Steps to reproduce the behaviour

type the above mentioned command

**Comment by patrickbrouwers** [comment]
https://github.com/laravel-doctrine/orm/pull/150
