### ISSUE TITLE
[BUG] Generate entities command does not resolve path correctly

### ISSUE THREAD

**Issue by Jacco-V** [laravel-doctrine/orm#154]
### Package version, Laravel version

Package v1.1.10,
Laravel v5.2.
### Expected behaviour

if I run command `doctrine:generate:entities`, I expect the generated entities to be written to

```
/app/Entities/[NameOfEntity].php
```
### Actual behaviour

When using the `doctrine:generate:entities` command, the resulting entities get written in wrong path location:

```
php artisan doctrine:generate:entities

Generating getter and setter for default entity manager...
Processing entity "App/Entities/Users"

Entity classes generated to "/app/Entities"
```

Which _looks_ ok, **but...** in reality, the files end up in:

```
/app/Entities/App/Entities/Users.php
```
### Steps to reproduce the behaviour

use the command as described above

**Comment by patrickbrouwers** [comment]
Just tested it (and used it before) for me it works like expected. 

Could you debug why it goes wrong here: https://github.com/laravel-doctrine/orm/blob/1.1/src/Console/GenerateEntitiesCommand.php#L55

If you find anything let us now, so we can improve this.

**Comment by Jacco-V** [comment]
I'll see if I can find the source of the issue.

edit: made pull request.

**Comment by patrickbrouwers** [comment]
I debugged this myself and concluded that nothing is wrong with the current implementation and that the result you are seeing is correct behaviour.

The command will check the namespaces of your entities and will create the required paths. With dest-path you can set the wanted destination path.

Your example will only work if your path is perfectly aligned with your namespace. 
`/app/Entities` vs `App/Entities`.

If you'd rename `app` to `App` and use `php artisan doctrine:generate:entities /` it should generate them in the folder you want.

The `app/Entities` default of the command is not a terrible default as it's kind of a safeguard to protect people who don't know what they are doing from messing with their folder structures (My current opinion is that it would have been better to require the dest-path argument). The `app/Entities` folder is easy to delete and also easy to move the Entities in the right folder from. Advanced users should pass the path as argument. 

Using the paths settings from the config will have the same unexpected result and especially with the inconsistency of that config value it's no guarantee to work for everyone.
