### ISSUE TITLE
[BUG] Unable to select data after switching PostgreSQL Schema

### ISSUE THREAD

**Issue by EspadaV8** [laravel-doctrine/orm#162]
### Package version, Laravel version

1.0.21, Laravel 5.1.26 (LTS)
### Expected behaviour

After setting the `search_path` in PostgreSQL you should be able to run doctrine queries on tables within that schema.
### Actual behaviour

A `Doctrine\DBAL\Exception\TableNotFoundException` is thrown with the message

```
SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "jobs" does not exist
```
### Steps to reproduce the behaviour

We are making heavy use of the [Laravel-PGSchema](https://github.com/pacuna/Laravel-PGSchema) package to switch between PostgreSQL schemas in a multitenancy application. With Eloquent this works without an issue but while attempting to do something similar using this package the following is thrown

```
Doctrine\DBAL\Exception\TableNotFoundException with message 'An exception occurred while executing 'SELECT t0.id AS id_1, t0.effective_dates AS effective_dates_2, t0.person AS person_3, t0.source AS source_4, t0.recruitment_cost AS recruitment_cost_5, t0.created_at AS created_at_6, t0.updated_at AS updated_at_7, t0.deleted_at AS deleted_at_8 FROM jobs t0 WHERE t0.id = ? AND ((t0.deleted_at IS NULL))' with params ["1"]:

SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "jobs" does not exist
LINE 1: ... updated_at_7, t0.deleted_at AS deleted_at_8 FROM jobs t0 WH...
```

This is run within the `tinker` command after running the following

```
Psy Shell v0.6.1 (PHP 7.0.7 — cli) by Justin Hileman
>>> PGSchema::switchTo('espadav8');
>>> $a = EntityManager::find('Lapis\Domain\Job\DoctrineJob', '1');
```

The schema exists within PostgreSQL and running a query via the `DB` facade returns an array of all the jobs within the table.

Is there some way to work out how doctrine is connecting to the database because I'm assuming it's not using the same connection as the rest of the application.

Thanks

**Comment by guiwoda** [comment]
Hi @EspadaV8, thanks for your report!
Unfortunately, LaravelDoctrine does not share the connection with Laravel's `DB` facade, so when `PGSchema::switchTo` sends the `SET search_path` command to Postgres, it sends it on a connection that Doctrine _is not using_.

As you can read in [postgres docs](https://www.postgresql.org/docs/9.1/static/sql-set.html):

> SET only affects the value used by the current session.

Possible solution:

Drop your dependency con Laravel-PGSchema, as it's not compatible with LaravelDoctrine. Then replace all calls to `PGSchema::switchTo('some-schema')` with:

```
EntityManager::getConnection()->exec("SET search_path TO some-schema");
```

**Comment by EspadaV8** [comment]
Ah, okay. I read that it uses the same connection as the rest of Laravel, I guess that just meant it uses the same connection details?

**Comment by patrickbrouwers** [comment]
Yes, it only shares the connection details, not the actual PDO connection.

**Comment by EspadaV8** [comment]
Okay then, that makes sense then 😄 Thanks for the information. I might see if I can either improve the package to also support this package or see about creating something to replace it that does work here.

Thanks again :-)

**Comment by patrickbrouwers** [comment]
@EspadaV8  I discussed this a bit with @guiwoda and we found a possiblity to share the connection between Laravel and Doctrine.

Perhaps you could try out this branch and see if it fixes your problem: https://github.com/laravel-doctrine/orm/tree/feature/share-laravel-pdo-connection. Please let us know :)

**Comment by maxbrokman** [comment]
@patrickbrouwers I think sharing the connection could have other potential benefits, potentially simplifies logging?

We currently have two audit logs set up that that record all write queries to a file, one for each connection. Perhaps this would make it simpler (not looked at / tested the code)

**Comment by EspadaV8** [comment]
@patrickbrouwers Hi. Sorry for the delay. I've not had chance to check that branch out yet but as soon as I get some time I will absolutely give it a go and let you know how it goes. Thanks

**Comment by patrickbrouwers** [comment]
Closing this. 1.2.0 should support this now, as we are sharing the connection with Laravel. If not any errors pop-up related to this package, please reopen the ticket.
