### ISSUE TITLE
[1.2][Bug] IlluminateRegistry creating duplicate manager references

### ISSUE THREAD

**Issue by dave-redfern** [laravel-doctrine/orm#173]
### Expected behaviour

Running the Doctrine commands should result in single set of output e.g.: doctrine:info one set of entities per configured EntityManager.
### Actual behaviour

Both default and (in this instance) MySQL are being bound to IlluminateRegistry during setup. This leaves 2 manager instances for the same set of Entities. 1.1.\* is unaffected and gives the expected, single manager.
### Steps to reproduce the behaviour

Upgrade to 1.2.*, use default settings. Create a couple of entities and map them. Once setup run: `./artisan doctrine:info` There is duplicate output of the entity information, but it is the same information.

I believe it is due to changes in the addManager / addConnection in ORM\IlluminateRegistry. It is now adding both the default name and the connection to the set of managers and these are passed into the main Doctrine ManagerRegistry. There should only be one added. Likely needs to be a check on the name to see if it is the same as the default since it appears to be the connection name triggering the behaviour.

Examples with simplified output:

```
// 1.1.* array dump from dump($this->managers) in IlluminateRegistry::addManager
vagrant@homestead:~/homestead$ ./artisan doctrine:info
array:1 [
  "default" => "default"
]
Found 44 mapped entities for default entity manager:
// snip
```

```
//1.2.* array dump from dump($this->managers) in IlluminateRegistry::addManager
vagrant@homestead:~/homestead$ ./artisan doctrine:info
array:2 [
  "default" => "default"
  "mysql" => "default"
]
Found 44 mapped entities for default entity manager:
// snip
Found 44 mapped entities for default entity manager:
// snip
```

In the 1.2 output, the entities are listed twice.

Reverting to the original code in addManager (from 1.1 branch) gives the expected outcome and the main library still appears to work. Replace in ORM\IlluminateRegistry::addManager() ln 78 the
code taken directly from https://github.com/laravel-doctrine/orm/blob/1.1/src/IlluminateRegistry.php#L78:

```
public function addManager($manager, array $settings = [])
{
    $this->container->singleton($this->getManagerBindingName($manager), function () use ($settings) {
        return $this->factory->create($settings);
    });
    $this->addConnection($manager);
    $this->managers[$manager] = $manager;
}
```

**Comment by patrickbrouwers** [comment]
Hey, thanks for noticing. In theory it shouldn't be a big issue as it's just a duplicated reference to the EM object. We need this alias to retrieve the EM for the password reset / failed job handling. I'll have a look this week to improve this, so it won't show as duplicated anymore.

**Comment by dave-redfern** [comment]
How about adding extra configuration to the main doctrine.php for jobs/password reset tables? That way it can be configured and suitable defaults set. Something like jobs => [ connection => default ] or similar.

**Comment by patrickbrouwers** [comment]
Laravel has a config setting for that, but the naming is not 100% compatible with LD, as it refers to the connection name not the manager name.  That was the reason for a alias. Perhaps a doctrine config setting will be less of a hassle.

**Comment by dpgover** [comment]
For us, having this duplicated manager is making the commands like d:s:u or even the creation of the schema executing twice (and failing).

1.1.13 works fine, 1.2 breaks the commands :sob:

**Comment by dave-redfern** [comment]
@dpgover I was afraid that duplicate execution would be a side-effect. If downgrading to 1.1.X is not doable, you could patch the ORM\IlluminateRegistry (as I mentioned); but you'll lose that on any update so it's not an ideal "fix".

**Comment by patrickbrouwers** [comment]
Guys, don't worry. It will be patched today.

**Comment by dave-redfern** [comment]
@patrickbrouwers Ping me if you need some testing; today is a public holiday for me so I have time ;)

**Comment by dpgover** [comment]
We downgraded to 1.1.13. It's not a problem right now.

I mentioned the problem just so you know!

Cheers.

**Comment by patrickbrouwers** [comment]
@dave-redfern can you give v1.2.3 a go? Should be patched.

**Comment by dave-redfern** [comment]
@patrickbrouwers Confirmed, duplicate output resolved...

However: generating a migration and it wants to delete the password_resets table. I think thats a separate issue though. I replaced the PasswordResetProvider, and everything else seems to be in-order, unless I missed some other config option.

**Comment by patrickbrouwers** [comment]
Yes that's right. As the password_resets table and failed_jobs table are temporary tables, they will recreate themselves if they don't exist. If you want to force to keep them you could modify the filter setting (https://github.com/laravel-doctrine/migrations/blob/1.0/config/migrations.php#L45) to always keep them.
