### ISSUE TITLE
[QUESTION] Migrations and transactions in tests

### ISSUE THREAD

**Issue by mpallante** [laravel-doctrine/orm#176]
Hello, I'm trying to do end-to-end functional testing but it seems that the `DatabaseTransactions` and `DatabaseMigrations` traits do not work.

I use Codeception to run all the tests and I created (for example) a `ResourceTest` in the functional suite to check that the route-controller-view flow works when I access a given resource. Of course `ResourceTest` extends `TestCase`. I'm using Sqlite as testing database.

So I have

```
<?php
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\WithoutMiddleware;

class ResourceTest extends TestCase
{
    use DatabaseTransactions;
    use WithoutMiddleware;

    /** @var \Faker\Generator */
    protected $generator;
    /** @var \Faker\ORM\Doctrine\Populator */
    protected $populator;

    protected function setUp()
    {
        parent::setUp();
        $this->generator = \Faker\Factory::create();
        $this->populator = new Faker\ORM\Doctrine\Populator($this->generator, app('em'));
    }

    protected function tearDown()
    {
        unset($this->populator);
        unset($this->generator);
        parent::tearDown();
    }

    public function testGetResource()
    {
        $this->populator->addEntity('App\MyResource', 1, [
            'name' => function () { return $this->generator->name; }
        ]);
        $entities = $this->populator->execute();

        $response = $this->call('GET', '/api/resource/' . $entities['App\MyResource'][0]->getId());

        $this->assertEquals(200, $response->getResponseCode());
    }
}
```

The `testGetResource()` test passes, but the newly created record is not deleted at the end of the test, as I would expect from the `DatabaseTransactions` trait.

I'm not very surprised by this behaviour, because I think that the populator has nothing to do with the transaction manager used by Laravel.

What really surprise me is that the `DatabaseMigrations` trait does not work.

If I add it to the test

```
...
use Illuminate\Foundation\Testing\DatabaseMigrations;
...
class ResourceTest extends TestCase
{
    use DatabaseMigrations;
    use DatabaseTransactions;
    use WithoutMiddleware;
...
```

then I get an exception when I run `$this->populator->execute()`

```
An exception occurred while executing 'INSERT INTO resources (name) VALUES (?)':
SQLSTATE[HY000]: General error: 1 no such table: resources
```

Moreover, if I run the migrations manually to get tables, with `php artisan migrate --database=sqlite`, then the `execute()` method hangs for a while and then I get this error

```
SQLSTATE[HY000]: General error: 5 database is locked
```

At the moment, I'm not using Laravel Doctrine migrations, but standard Laravel ones.

I'm using Laravel Doctrine version is 1.2.3, Laravel is 5.2.41.

Thank you very much for any help!

**Comment by patrickbrouwers** [comment]
Hey sorry for the late response I was on holiday.

I think you are trying to mix two things: you are trying to use Laravel testing helpers within Codeception. Codeception has a lot of great helpers on its own. I myself use Codeception to run all my intregration/functional tests without those helpers.

Codeception already does some transactions starts, so if you do the same with a trait, the db is already locked when it tries to lock it for the 2nd time.

Another way of speeding up the tests: (how I do it)

1) create sqlite dump in `tests/_data/dump.sql`, you can do this with `php artisan doctrine:dump:sqlite` for example.

2)
codeception.yml

```
modules:
    config:
        Db:
             dsn: 'sqlite:/database/database.sqlite'
             user: 'root'
             password: ''
             dump: 'tests/_data/dump.sql'
             populate: true
             cleanup: true
             reconnect: true
```

3) functional.suite.yml

```
modules:
    enabled:
        - Db
```

Now it will reset your db on each test back to the dump.sql file contents.

Here's some more information about the Laravel module in codeception: http://codeception.com/docs/modules/Laravel5
