### ISSUE TITLE
[BUG] Call to member function isAbstract on null in mappedEventSubscriber doctrine:generate:entities

### ISSUE THREAD

**Issue by manticorp** [laravel-doctrine/orm#177]
Please prefix your issue with one of the following: [BUG] [PROPOSAL] [QUESTION].
### Package version, Laravel version

1.2
5.3
### Expected behaviour

Generates entities
### Actual behaviour

Throws up the error in title
### Steps to reproduce the behaviour

run php artisan doctrine:generate:entities

This seems to be related to the following issue filed on the doctrine github:

https://github.com/doctrine/doctrine2/issues/4459

and the following pull request:

https://github.com/doctrine/doctrine2/pull/1345

The generate:entities command uses the `DisconnectedClassMetadataFactory` and so `getReflectionClass` isn't guaranteed to return anything and can be null, as such the following lines in `LaravelDoctrine\ACL\Mappings\Subscribers\MappedEventSubscriber` should be changed:

From:

```
    /**
     * A MappedSuperClass or Abstract class cannot be instantiated.
     *
     * @param ClassMetadata $metadata
     *
     * @return bool
     */
    protected function isInstantiable(ClassMetadata $metadata)
    {
        if ($metadata->isMappedSuperclass) {
            return false;
        }

        if ($metadata->getReflectionClass()->isAbstract()) {
            return false;
        }

        return true;
    }
```

To:

```
    /**
     * A MappedSuperClass or Abstract class cannot be instantiated.
     *
     * @param ClassMetadata $metadata
     *
     * @return bool
     */
    protected function isInstantiable(ClassMetadata $metadata)
    {
        if ($metadata->isMappedSuperclass) {
            return false;
        }

        if (!$metadata->getReflectionClass() || $metadata->getReflectionClass()->isAbstract()) {
            return false;
        }

        return true;
    }
```

I've tried it and it seems to work fine after that - but I don't know if this will affect anything else internally.

**Comment by patrickbrouwers** [comment]
Could you do those changes in a PR, that's easier for me to look at it / test it. Thanks.

**Comment by manticorp** [comment]
Ack really sorry, this was meant for acl not orm!
