### ISSUE TITLE
[BUG] No results when adding more than 2 parameters to the querybuilder

### ISSUE THREAD

**Issue by chris-code-lab** [laravel-doctrine/orm#179]
### Package version

laravel-doctrine/orm v1.2.5 
Lumen v5.2.7. 
Oracle database. 

```
$conn = $this->getEntityManager()->getConnection();
$queryBuilder = $conn->createQueryBuilder();
$queryBuilder->select('*')
    ->from('SYNCHS')
    ->where('SYNCHS.CLIENT_ID = :clientId')
    ->andWhere('SYNCHS.TOP_CLIENT_ID = :topClientId')
    ->andWhere('SYNCHS.ID = :synchId');

$queryBuilder->setParameter('clientId', $clientId)
    ->setParameter('topClientId', $topClientId)
    ->setParameter('synchId', $synchId);

echo $queryBuilder->getSQL();
var_dump($queryBuilder->getParameters());

$stmt = $queryBuilder->execute();
var_dump($stmt);

$results = $stmt->fetchAll();
dd($results);
```

If I comment any one of the where/addwhere clause, I end up with the expected result set, but if I have more than 2 parameters bound, it returns an empty array instead of 1 row.
`$queryBuilder->getParameters()` is returning all 3 parameters.
When using the 3 parameters, if I copy / paste the string returned by `$queryBuilder->getSQL();` into Toad and run the query against the database with the parameter values returned by  `$queryBuilder->getParameters()`, I get 1 row.
### Expected behaviour

$results contains 1 row.
### Actual behaviour

$results is an empty array.

**Comment by patrickbrouwers** [comment]
If this indeed it goes wrong it's an issue with the parent package doctrine/orm. This package has no influence in how the query builder works.
Maybe someone on our Slack can help you, but the Doctrine IRC / github issues will most likely be a better place to ask about this.
