### ISSUE TITLE
[1.2][Bug] Notification extend is called without checking Laravel version

### ISSUE THREAD

**Issue by dave-redfern** [laravel-doctrine/orm#182]
### Package version, Laravel version

1.2.7
### Expected behaviour

Laravel Doctrine should continue to function on Laravel 5.2+.
### Actual behaviour

Error: [ReflectionException] Class Illuminate\Notifications\ChannelManager does not exist because Laravel 5.2 does not have the notification manager.
### Steps to reproduce the behaviour

Use 1.2.7 with Laravel 5.2.X.
### Suggested fix

In DoctrineServiceProvider::extendNotificationChannel add a check for the Laravel application version from Illuminate\Foundation\Application::VERSION and only apply it when the major/minor is > 5.3.

**Comment by dave-redfern** [comment]
@patrickbrouwers confirm fixed, thanks! 👍

**Comment by patrickbrouwers** [comment]
Nice, thanks for notifying me :)
