### ISSUE TITLE
[QUESTION] Custom mapping type carbondatetime never synced.

### ISSUE THREAD

**Issue by chay22** [laravel-doctrine/orm#184]
Spent some hours learning doctrine and this package, reading some chapters of docs and whatnot, then going to use `carbon` as exactly shown here, https://github.com/laravel-doctrine/orm/issues/149

```
'mapping_types' => [
    'datetime' => 'carbondatetime'
 ],

...
...

 'custom_types' => [
    'json' => LaravelDoctrine\ORM\Types\Json::class,
    'carbondate' => DoctrineExtensions\Types\CarbonDateType::class,
    'carbondatetime' => DoctrineExtensions\Types\CarbonDateTimeType::class,
    'carbondatetimetz' => DoctrineExtensions\Types\CarbonDateTimeTzType::class,
    'carbontime' => DoctrineExtensions\Types\CarbonTimeType::class,
],
```
### Package version, Laravel version

laravel-doctrine/orm: 1.2.8
laravel/framework: 5.3.15
laravel-doctrine/fluent: 1.1.3
### Expected behaviour

When `mapping_type` left as is, console `doctrine:schema:validate` outputs

```
Validating for default entity manager...
[Mapping]  OK - The mapping files are correct.
[Database] OK - The database schema is in sync with the mapping files.
```
### Actual behaviour

Otherwise, when `'datetime' => 'carbondatetime'` added.

```
Validating for default entity manager...
[Mapping]  OK - The mapping files are correct.
[Database] FAIL - The database schema is not in sync with the current mapping file.
```

I've tried to `update`, `update --force`, `drop` then re`ceate`, It still warns the failure whether I use `$builder->carbonDateTime('created_at')` or `$builder->dateTime('created_at')` in fluent map when `'datetime' => 'carbondatetime'` added in `mapping_type`.

However, using`$builder->carbonDateTime('created_at')` when `'datetime' => 'carbondatetime'` added, I still can see the comment on the field just like when I left it out, which is expected(?).

```
MariaDB [testestes]> show full columns from users;
+----------------+------------------+-----------------+------+-----+---------+----------------+---------------------------------+--------------------------+
| Field          | Type             | Collation       | Null | Key | Default | Extra          | Privileges                      | Comment                  |
+----------------+------------------+-----------------+------+-----+---------+----------------+---------------------------------+--------------------------+
| id             | int(10) unsigned | NULL            | NO   | PRI | NULL    | auto_increment | select,insert,update,references |                          |
| username       | varchar(255)     | utf8_unicode_ci | NO   |     | NULL    |                | select,insert,update,references |                          |
| password       | varchar(255)     | utf8_unicode_ci | NO   |     | NULL    |                | select,insert,update,references |                          |
| email          | varchar(255)     | utf8_unicode_ci | NO   |     | NULL    |                | select,insert,update,references |                          |
| created_at     | datetime         | NULL            | NO   |     | NULL    |                | select,insert,update,references | (DC2Type:carbondatetime) |
| updated_at     | datetime         | NULL            | NO   |     | NULL    |                | select,insert,update,references | (DC2Type:carbondatetime) |
| remember_token | varchar(255)     | utf8_unicode_ci | NO   |     | NULL    |                | select,insert,update,references |                          |
+----------------+------------------+-----------------+------+-----+---------+----------------+---------------------------------+--------------------------+
```

But, using `$builder->dateTime('created_at')`, both cases result a plain datetime. Still finding a good time to dig into the source since I just started learning and haven't even finished reading all the fun parts.

**Comment by patrickbrouwers** [comment]
Hey, thanks for using doctrine and fluent!

Just to check:
- did you include the extensions package?
- if you fetch a record in doctrine and `dd($user->created_at)` does it return a Carbon instance?

(Tip: you can also use the `->timestamps()` extension for `created_at` and `updated_at`, it will auto fill them on persistance. (See extensions docs: http://www.laraveldoctrine.org/docs/1.2/extensions/timestamps / http://www.laraveldoctrine.org/docs/1.2/fluent/extensions#timestamps)
