### ISSUE TITLE
[QUESTION] How Generate Entities from an Existing Database?

### ISSUE THREAD

**Issue by n-singularity** [laravel-doctrine/orm#190]
Hy guys,

I tried to generate entities from an existing database use symfony tutorial. But syntax "doctrine:mapping:convert" is not defined. 

is there any other way to do that?

**Comment by patrickbrouwers** [comment]
For starters this is not a Symfony package :) So we don't apply to the same syntax.

I think you are looking for `php artisan doctrine:mapping:import`

**Comment by n-singularity** [comment]
I tried `php artisan doctrine:mapping:import` and i get XML files, so i need to change from XML files to Entities.

is there any other syntax to do that?

**Comment by patrickbrouwers** [comment]
`php artisan help doctrine:mapping:import` will show you the options. 

```
doctrine:mapping:import [options] [--] [<mapping-type>] [<dest-path>]
```

`mapping-type` defaults to `xml`, but you can set it to the driver you want. 
If you want to generate entities from xml/yaml, you can use the `doctrine:generate:entities` command.

**Comment by n-singularity** [comment]
`doctrine:generate:entities` only recognize php files. have I missed something?

**Comment by avdarie** [comment]
I have same problem. i need to install fluent package to work that ? 
I did:
`php artisan doctrine:mapping:import`  --> that creates  xml files in \app\Mapping\ with all mapping information from DB . 
When i will create entities with command:
`php artisan doctrine:generate:entities`  --> Not found any Mapping. 

Maybe I need to configure something in doctrine.php ? 

Thanks !

**Comment by avdarie** [comment]
Hi,
I solved the problem ... 
`php artisan doctrine:mapping:import annotation` create in annotation type. Mapping a php class with annotation.
`php artisan doctrine:generate:entities` recongize all entities and create setter and getters...
If  mapping is in another type ex (yaml,php or xml) generate:entities not work ...

But you need to be carefully because rewrite all entities ...

**Comment by ergonomic0013** [comment]
php artisan doctrine:mapping:import annotations
after do:
php artisan generate:enitites
