### ISSUE TITLE
[QUESTION] Why generated entity have no namespace defined within them?

### ISSUE THREAD

**Issue by loiclavoie** [laravel-doctrine/orm#193]
In the laravel framework (that I'm still learning), everything under app is defined within the namespace App/ (basically, PSR-4 autoloading logic).

When I generate my entities for the legacy database I'm working with at the moment, I've used the mapping import  with the appropriate configuration and parameter to generate my yml  file.
`clear;php artisan doctrine:mapping:import --em=myEm yml ./path/to/mappingfile --namespace=NamespaceWhereToPutTheEntities`

Now when I use:
`clear;php artisan doctrine:mapping:import --em=myEm`
It generate the file within App/Entities/NamespaceWhereToPutTheEntities but within each entity file, there's absolutely no namespace definititon.

Expected:
```
<?php
  namespace App/Entities/NamespaceWhereToPutTheEntities;
  class MyEntity{....

```

Current:
```
<?php
  class MyEntity{....

```

Is there something I'm missing?

**Comment by patrickbrouwers** [comment]
If you want the entities to have a namespace, you will have to use the `--namespace` option. This is expected behaviour.
