### ISSUE TITLE
QUESTION  or reflection...   FatalErrorException in ResetsPasswords.php line 102:

### ISSUE THREAD

**Issue by Sztukmistrz** [laravel-doctrine/orm#194]
laravel-doctrine/orm": "1.2.*, "laravel/framework": "5.3.*"

Restet password

I stayed for longer on unpleasant message. I tried to reset the password for the user. An error occurred!?:

```
FatalErrorException in ResetsPasswords.php line 102: 
Call to undefined method Entities\Passport\User::forceFill()
```

I did everything according to instructions ... or perhaps I did not.
It looks as if at that moment acted Eloquent?

So I created function in: App\Http\Controllers\Auth\ResetPasswordController

```
protected function resetPassword($user, $password)
    {
        $user->setPassword(bcrypt($password));
        $user->setRememberToken(str_random(60));
        \EntityManager::persist($user);
        \EntityManager::flush();

        \Auth::guard()->login($user);
    }
```

----
Question: is this OK? or I missed something?
or should it be shown in the manual?

Thank you in advance for your answer

**Comment by patrickbrouwers** [comment]
You indeed can't completely reuse the trait inside the  ResetPasswordController as it is coupled to Eloquent. 

The way you solved it, is correct.

**Comment by Sztukmistrz** [comment]
Thank you very much for the advice.
Thank you also for your work and the possibility to use it in my own projects!
Grateful forever. Christopher.
