### ISSUE TITLE
[PROPOSAL] Entity Generator --no-backup option

### ISSUE THREAD

**Issue by loiclavoie** [laravel-doctrine/orm#196]
### Package version, Laravel version
5.3
### Expected behaviour
When running the command, the option --no-backup shouldn't expect a parameter.  It should be, if present, false, otherwise true.
### Actual behaviour
At the moment, this line put True when --no-backup is present
`$entityGenerator->setBackupExisting(!$this->option('no-backup')); `
(GenerateEntitiesCommand.php:81)
So when the command is ran with  --no-backup, backup files are still generated

**Comment by patrickbrouwers** [comment]
Can you PR this, please. Thx.

**Comment by loiclavoie** [comment]
@patrickbrouwers I'm sorry Patrick, I never saw that comment o_O.

What do you mean by PR it?

**Comment by patrickbrouwers** [comment]
PR = making a pull request. But I've already fixed it myself a month ago. Should be fixed in the latest version.
