### ISSUE TITLE
[QUESTION] Laravel 5.2 Artisan Command and laravel-doctrine

### ISSUE THREAD

**Issue by stefanheimann** [laravel-doctrine/orm#197]
### Package version, Laravel version
laravel/framework": "5.2.*"
laravel-doctrine/orm: "1.1.*"

### Behaviour
If I'm using a laravel-doctrine repository method (findAll) inside a laravel console command, it doesn't fetch all entity properties. Using the same method inside a web route, the entitiy is fully populated.

Does anybody have a clue what have to be done that laravel-doctrine is fully working inside a console command?

**Comment by patrickbrouwers** [comment]
Did you manage to solve it? It doesn't sound like something this package is responsible for tbh. I've successfully used Doctrine in the console before.
