### ISSUE TITLE
[BUG] Laravel's Internal acceptance testing doesn't allow eager loading.

### ISSUE THREAD

**Issue by ing200086** [laravel-doctrine/orm#201]
I am like Doctrine's data mapper arch, and I am running through the getting started tutorial. With laravel I found an issue when trying to do eager loading of relationships. Is this a known bug, and is there a work around? I don't like the idea of not testing the end-points of my API. Any help would be appreciated.

I am providing my repository for ease.
    https://github.com/ing200086/laravel-doctrine-learning.git

If you setup the application and run phpunit, there is an issue with the json structure when calling the /api/v1/user/ URI. The issue is that the internal testing doesn't seem to eager load the bugs. The odd thing is when you access it directly from Postman or Chrome, it does.

**Comment by maxbrokman** [comment]
Could you provide a bit more detail sorry? Not sure what exactly isn't happening and where, a link to a test and a description of what you expect to happen and what happens would be good.

**Comment by ing200086** [comment]
Sure. In the code I provided in the repository there are 3 main entities: User, Product, Bug.

I used laravel to create a simple api where when I go the URI api/v1/user.

In Chrome it creates the result
```json
{
  "data": [
    {
      "name": "George Orwell",
      "bugs": [
        {
          "id": 2,
          "title": "Time has stopped!"
        },
        {
          "id": 22,
          "title": "Qui qui aut labore perferendis a deserunt."
        }
      ]
    },
    {
      "name": "Dr. Rickie Bruen",
      "bugs": [
        {
          "id": 8,
          "title": "Sint ex quia laudantium delectus nulla dolore."
        }
      ]
    }
 ]
}
```

In the tests/acceptance/api/UserTest.php I attempted to test this recreate this with Laravel's automated testing but the resulting response to the same call is

```json
{
  "data": [
    {
      "name": "George Orwell",
      "bugs": []
    },
    {
      "name": "Dr. Rickie Bruen",
      "bugs": []
    }
 ]
}
```

This tells me that somehow the base framework testing is going through a different channel which prevents the eager loading.

Has anyone else run into this bug, or is this just an issue with my code?

**Comment by maxbrokman** [comment]
You're not actually eager loading the [bugs](https://github.com/ing200086/laravel-doctrine-learning/blob/a78a6798806a6432863ed4e8fbc22b5bfe88fa6a/app/Http/Controllers/Api/v1/UserController.php#L28), they're being lazy loaded in your transformer. 

They way you're using fractal is a little bit odd, look into [includes instead](http://fractal.thephpleague.com/transformers/#including-data) which could play a role maybe.

Not sure what could be causing the behaviour you are seeing, I suggest adding a test case to your users test that makes sure all users seeded by the parent class are getting the correct number of bugs, will at least help to narrow things down.

If you can get them out of the database with the bugs attached then we'll have to look elsewhere, but I doubt this is related to Laravel Doctrine.

**Comment by ing200086** [comment]
I figured I was telling doctrine to eager load in (I'm not sure how you linked to call out a line or I would) app\ORM\Mappings\UserMapping.php:L31. Is that not the intended use of the fetchEager()?

Thanks for the fractal includes link. I'll have to look into that.

I will try and update the code to have a segregated test with one user and 2 bugs. Then I'll see if I can get them out. Thanks.

**Comment by maxbrokman** [comment]
Ah sorry, I didn't look at the mappings. Yes it should be eager in the `fetchAll` case I think. 

Your problem doesn't immediately seem to be related to eager or lazy loading though, it should behave the same in the end.

**Comment by ing200086** [comment]
It seems to have something to do with Laravel's test framework. If I go through guzzle then in seems to work, but through laravel's framework it does not.

I am surprised that nobody has seen this before.

**Comment by dave-redfern** [comment]
It is generally a much better idea to not using eager loading, but to instead use a custom repository find method and do a fetch join. For example in the UserRepository (by the way, you shouldn't use app() in the repo, if you need a query builder, just call $this->createQueryBuilder('some_alias'), the entity manager is already loaded in the repo):

```php
class UserRepository extends EntityRepository
{
    public function fetchAllUsersWithReportedBugs()
    {
        $qb = $this->createQueryBuilder('u');
        $qb
            ->addSelect('b')
            ->leftJoin('u.reportedBugs', 'b')
        ;
        return $qb->getQuery()->getResult();
    }
}
```

That will then load the users and all the bugs through the relationship User.reportedBugs and in a single query. Note that this is generally OK for small entities / small numbers of results; but should never be done with many-to-many relationships or on multiple entities (e.g. user, reportedbugs, assigned bugs, some other thing, another thing). Query might still be fast, but you will pay a heavy price for hydrating (converting to objects) everything pulled back by the query.

If you add barryvdh/debugbar you can get the query output and will see that this generates a query that selects all columns from user and all columns from reported bugs, so you can see how it can become a problem.

Note that eager loading can sometimes do weird stuff if there is lazy or extra lazy associated with either side of the entity e.g. reportbugs lazy loads the User, that can sometimes cause the entities to be uninitialised (ran into this myself - only fix was to either remove eager/extra lazy or use a fetch-join to force the load).

There's another method to multi-load, but better to understand repositories and their role first :)

I would also suggest using Pagination to keep the number of results sensible (even in an example / learning). Pretty easy with the Paginatable trait.

**Comment by lex0r** [comment]
I can confirm that in my case I see a very similar issue (laravel/lumen-framework 8.2.3, laravel-doctrine 1.7.6).

My models are hydrated when I execute the code in the non-testing context, and aren't when I run acceptance tests.

**Comment by eigan** [comment]
@lex0r Difficult to help you here. Could you use xdebug and step through both cases to see what's going on?

Also please open a new issue instead :-)
