### ISSUE TITLE
[BUG] Lumen overwrites validation.presence with Illuminate\Validation\DatabasePresenceVerifier

### ISSUE THREAD

**Issue by blacktemplar** [laravel-doctrine/orm#202]
I am trying to use the presence validation for doctrine, but I cannot use it with Lumen since it gets overwritten by the default presence provider. I am using the Lumen Framework 5.3.3.

I debugged it a little bit and the problem seems to be that registerValidatorBindings() in Laravel\Lumen\Application.php binds a function which calls register('Illuminate\Validation\ValidationServiceProvider'). In the ValidationServiceProvider the validation.presence singleton gets overwritten. So it seams to be a problem with the Lumen Framework.

**Comment by patrickbrouwers** [comment]
Not really sure that's something we can fix in the library to be honest :(
You could try and overrule that `registerValidatorBindings` in your project and set it to the doctrine service provider.

**Comment by matt-allan** [comment]
This is a general problem with how Lumen works ([see this issue](https://github.com/laravel/lumen-framework/issues/416)).

@blacktemplar If you resolve the validator once (`app('validator')`) before the Laravel Doctrine service provider runs it should work.  That will stop [this block of code](https://github.com/laravel/lumen-framework/blob/5.2/src/Application.php#L199) from running.

**Comment by patrickbrouwers** [comment]
Should be fixed in 1.3.4
