### ISSUE TITLE
Fluent - get driver and add mappings during runtime

### ISSUE THREAD

**Issue by zdnk** [laravel-doctrine/orm#204]
Hello,

my application is separated into modules. I was wondering if theres a way to add Fluent mappings in ServiceProvder registration rather then in config file as it provides more dynamic approach and ability to have modulable application.

Thanks.

**Comment by patrickbrouwers** [comment]
You can do it this way:

```
/**
* @param DoctrineManager $manager
*/
public function boot(DoctrineManager $manager)
{
    $manager->addMappings([
        UserMapping::class,
    ]);
}
```
