### ISSUE TITLE
[BUG] findAll() only returning single attribute from entity

### ISSUE THREAD

**Issue by nshCore** [laravel-doctrine/orm#210]
Please prefix your issue with one of the following: [BUG] [PROPOSAL] [QUESTION].

### Package version, Laravel version
        "laravel/lumen-framework": "5.3.*",
        "laravel-doctrine/orm": "1.2.*",

### Expected behaviour
findAll() should return all attributes of all entities

### Actual behaviour
only returning one attribute

### Steps to reproduce the behaviour
$results = app()->make('em')->getRepository('App\Entities\SomeEntity')->findAll();
dd($results);

For some reason laravel doctrine is only returning a single attribute from my entity and not all columns.

**Comment by josenicomaia** [comment]
Can you provide your doctrine.php, Entity and mapping?

**Comment by nshCore** [comment]
doctrine.php

```
<?php
return [

    'managers'                  => [
        'default' => [
            'dev'        => env('APP_DEBUG'),
            'meta'       => env('DOCTRINE_METADATA', 'annotations'),
            'connection' => env('DB_CONNECTION', 'sqlite'),
            'namespaces' => [
                'app'
            ],
            'paths'      => [
                env('COMPASS_ENTITIES',base_path('vendor/apiarchitect/compass/src/Entities')),
                env('AUTH_ENTITIES',base_path('vendor/apiarchitect/auth/src/Entities')),
                env('LOG_ENTITIES',base_path('vendor/apiarchitect/log/src/Entities')),
                env('NODE_ENTITIES',base_path('vendor/jkirkby91/lumendoctrinecomponent/src/Entities')),
                env('APP_ENTITIES',base_path('/app/Entities')),
            ],
            'repository' => Doctrine\ORM\EntityRepository::class,
            'proxies'    => [
                'namespace'     => false,
                'path'          => storage_path('proxies'),
                'auto_generate' => env('DOCTRINE_PROXY_AUTOGENERATE', false)
            ],

            'events'     => [
                'listeners'   => [],
                'subscribers' => []
            ],
            'filters'    => [],

            'mapping_types'              => [
                'enum' => 'string'
            ]
        ]
    ],

    'extensions'                => [
        LaravelDoctrine\Extensions\Timestamps\TimestampableExtension::class,
        LaravelDoctrine\Extensions\SoftDeletes\SoftDeleteableExtension::class,
        LaravelDoctrine\Extensions\Loggable\LoggableExtension::class,
        LaravelDoctrine\Extensions\Blameable\BlameableExtension::class,
        LaravelDoctrine\Extensions\IpTraceable\IpTraceableExtension::class,
        LaravelDoctrine\ORM\Extensions\TablePrefix\TablePrefixExtension::class,

    'custom_types'              => [
        'json' => LaravelDoctrine\ORM\Types\Json::class
    ],

    'custom_datetime_functions' => [],

    'custom_numeric_functions'  => [],

    'custom_string_functions'   => [],

    'logger'                    => env('DOCTRINE_LOGGER', false),

    'cache'                      => [
        'default'                => env('DOCTRINE_CACHE', 'memcached'),
        'namespace'              => null,
        'second_level'           => false,
    ],

    'gedmo'                     => [
        'all_mappings' => false
    ],

    'doctrine_presence_verifier' => true,
];

```

Entity showOff.php

```
<?php

namespace App\Entities;

use Doctrine\ORM\Mapping as ORM;
use App\Jobs\IndexNewEntitiesJob;
use App\Jobs\UpdateIndexEntitiesJob;
use Doctrine\Common\Collections\ArrayCollection;
use ApiArchitect\Compass\Entities\User;

/**
 * Class ShowOff
 *
 * @package Jkirkby91\DoctrineSchemas
 * @author James Kirkby <jkirkby91@gmail.com>
 *
 * @ORM\Entity
 * @ORM\HasLifeCycleCallbacks
 * @ORM\Table(name="show_off")
 * @ORM\Entity(repositoryClass="App\Repositories\ShowOffRepository")
 */
class ShowOff extends \App\Entities\MediaObject
{

    /**
     * @ORM\Column(type="string", length=45, nullable=false, unique=false)
     */
    protected $type;
    
    /**
     * @ORM\Column(type="integer", length=45, nullable=false)
     */
    protected $size;

    /**
     * @ORM\Column(type="datetime", length=45, nullable=false, unique=false)
     */
    protected $lastModified;

    /**
     * @ORM\OneToOne(targetEntity="\ApiArchitect\Compass\Entities\User", fetch="EAGER", cascade={"persist"})
     */
    protected $owner;

    /**
     * @ORM\OneToOne(targetEntity="\App\Entities\HairCutter", fetch="EAGER", cascade={"persist"})
     * @ORM\Column(nullable=true, unique=false)
     */
    protected $hairCutter;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    protected $filePath;


    /**
     * HairCutter constructor.
     * @param    $fileName   
     * @param    $filePath   
     * @param    $owner   
     * @param    $hairCutter   
     */
    public function __construct($fileName, $filePath, User $owner, $type, $lastModified, $size)
    {
        $this->name = $fileName;
        $this->filePath = $filePath;
        $this->owner = $owner;
        $this->type = $type;
        $this->lastModified = $lastModified;
        $this->size = $size;
        $this->nodeType = 'showOff';
    }

    /**
     * Gets the value of filePath.
     *
     * @return mixed
     */
    public function getFilePath()
    {
        return $this->filePath;
    }

    /**
     * Sets the value of filePath.
     *
     * @param mixed $filePath the file path
     *
     * @return self
     */
    protected function setFilePath($filePath)
    {
        $this->filePath = $filePath;

        return $this;
    }

    /**
     * Gets the value of owner.
     *
     * @return mixed
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * Sets the value of owner.
     *
     * @param mixed $owner the owner
     *
     * @return self
     */
    protected function setOwner(User $owner)
    {
        $this->owner = $owner;

        return $this;
    }

    /**
     * Gets the value of hairCutter.
     *
     * @return mixed
     */
    public function getHairCutter()
    {
        return $this->hairCutter;
    }

    /**
     * Sets the value of hairCutter.
     *
     * @param mixed $hairCutter the hair cutter
     *
     * @return self
     */
    protected function setHairCutter($hairCutter)
    {
        $this->hairCutter = $hairCutter;

        return $this;
    }
}
```

The only attribute returned is 'nodeType' like this

> [
>     {
>       "nodeType": "showOff"
>     },
>     {
>       "nodeType": "showOff"
>     },
>     {
>       "nodeType": "showOff"
>     }
> ]

There is other data in the actual table when viewed via mysql

**Comment by nshCore** [comment]
I've switched on the logger to file and the query generated as followed

` SELECT t0.type AS type_1, t0.size AS size_2, t0.last_modified AS last_modified_3, t0.hair_cutter AS hair_cutter_4, t0.file_path AS file_path_5, t0.content_url AS content_url_6, t0.embed_url AS embed_url_7, t0.height AS height_8, t0.width AS width_9, t0.player_type AS player_type_10, t0.about AS about_11, t0.award AS award_12, t0.comment AS comment_13, t0.comment_count AS comment_count_14, t0.text AS text_15, t0.thumbnail AS thumbnail_16, t0.version AS version_17, t0.name AS name_18, t0.id AS id_19, t0.nid AS nid_20, t0.node_type AS node_type_21, t0.owner_id AS owner_id_22, t23.enabled AS enabled_24, t23.username AS username_25, t23.email AS email_26, t23.password AS password_27, t23.remember_token AS remember_token_28, t23.name AS name_29, t23.id AS id_30, t23.nid AS nid_31, t23.node_type AS node_type_32, t0.aggregate_rating_id AS aggregate_rating_id_33, t34.rating_count AS rating_count_35, t34.rating_score AS rating_score_36, t34.name AS name_37, t34.id AS id_38, t34.nid AS nid_39, t34.node_type AS node_type_40, t0.author_id AS author_id_41, t42.enabled AS enabled_43, t42.username AS username_44, t42.email AS email_45, t42.password AS password_46, t42.remember_token AS remember_token_47, t42.name AS name_48, t42.id AS id_49, t42.nid AS nid_50, t42.node_type AS node_type_51, t0.translator_id AS translator_id_52, t53.enabled AS enabled_54, t53.username AS username_55, t53.email AS email_56, t53.password AS password_57, t53.remember_token AS remember_token_58, t53.name AS name_59, t53.id AS id_60, t53.nid AS nid_61, t53.node_type AS node_type_62 FROM show_off t0 LEFT JOIN users t23 ON t0.owner_id = t23.id LEFT JOIN aggregate_rating t34 ON t0.aggregate_rating_id = t34.id LEFT JOIN users t42 ON t0.author_id = t42.id LEFT JOIN users t53 ON t0.translator_id = t53.id ;`

If I run it from mysql command line returns all the expected data too, so looks like its stripping out my data post query and cant figure out why

**Comment by eigan** [comment]
Just a guess here, but..
`nodetype` is a public property? Looks like since you return an array in the [controller method](http://stackoverflow.com/questions/42019091/laravel-doctrine-only-returning-single-attribute-from-findall-query), Laravel only outputs the public properties of the object in the array. What does `showResponse()` do?

You could try to implement JsonSerializable::[jsonSerialize](http://php.net/manual/en/jsonserializable.jsonserialize.php) and return an array with the data you need.

**Comment by nshCore** [comment]
showResponse() is a factory for returning a Diactoros\Response\JsonResponse object.

You are right it seems that it needs to be a public attribute to be returned here, which is weird as in other controllers I am doing similar methods of returning data, which do grab the entire entities protected properties I then pass them into a fractal transformer to only out put the attributes I want. Im not overly keen on public attributes, but since it will be part of a public feed im not concerned.

I would have thought even though im calling findAll() from a controller method, im injecting a repository into the controller which has been instantiated with the relevant entity, so the repository object should be able to get the protected attributes of the entity.

My showOffRepositoryServiceProvider has this method

```
   /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->bind(\App\Repositories\ShowOffRepository::class, function($app) {
            return new \App\Repositories\ShowOffRepository(
                $app['em'],
                $app['em']->getClassMetaData(\App\Entities\ShowOff::class)
            );
        });     
    }
```

my appServiceProvider then injects the repo into the controller

        $this->app->bind(\App\Http\Controllers\ShowOffController::class, function($app) {
            return new \App\Http\Controllers\ShowOffController(
                $app['em']->getRepository(\App\Entities\ShowOff::class),
                new \App\Http\Transformers\ShowOffTransformer(),
                new Filesystem($this->app)
            );
        });

In previous smfony/doctrine i've used JSM serializer with the expose annotation to get the attributes I want, is this compatible with laravel doctrine?

@eigan thanks for the suggestion though!!!

**Comment by eigan** [comment]
Just to clarify, `findAll()` does not return an array of objects? Or does `getHairCutter()` return null on every object?

Since you use a custom repository, might want to check ShowOffRepository::findAll()

_Have you cleared the cache? I see memcached as default_

**Comment by nshCore** [comment]
`findAll()` returns the data in this structure

```
[
{
"nodeType": "showOff"
},
{
"nodeType": "showOff"
},
{
"nodeType": "showOff"
}
]

```
`getHairCutter()` returns a user object that is on a one-to-one association  from the showOffEntity

Even though showOffEntity has a custom repository ShowOffRepository it inherits `findAll()` directly from \Doctrine\ORM\EntityRepository.

ShowOffRepository only contains custom methods for storing and updating entities.

Yep i've been dropping caches after changes

**Comment by eigan** [comment]
I have never seen `findAll()` return anything else than objects.. Strange..
I would check the MediaObject mapping/methods for some weird stuff and run `php artisan doctrine:schema:validate`

**Comment by nshCore** [comment]
yeh for sure something weird now, i abstracted the `index()` into my LumenRestServerComponent its behaving as it should. 

https://github.com/jkirkby91-2/LumenRestServerComponent/blob/master/src/Http/Controllers/ResourceController.php

Maybe something wrong in the business logic layer of my app. Any way will continue to investigate, thank for the support. I guess this wasnt really a bug after all.
