### ISSUE TITLE
Bug memcache connect

### ISSUE THREAD

**Issue by hoangnguyengia** [laravel-doctrine/orm#212]
### https://github.com/laravel-doctrine/orm/blob/1.2/src/EntityManagerFactory.php

$configuration = $this->setup->createConfiguration(
            array_get($settings, 'dev', false),
            array_get($settings, 'proxies.path'),
            $this->cache->driver()
        );

lost $this->cache->driver()

**Comment by patrickbrouwers** [comment]
Duplicate issue
