### ISSUE TITLE
[BUG] Doctrine caching methods accept TTL in seconds, but Laravel use minutes

### ISSUE THREAD

**Issue by aledelgo** [laravel-doctrine/orm#216]
### Expected behaviour
Save query result in cache with a TTL  = 5 **seconds**

### Actual behaviour
The cresult in the cache have a TTL of 5 **minutes**

### Long explanation
When i try to save the result of a query in the cache via native doctrine commands, it expect the cache TTL to be **in seconds**, but the cache driver used refer to Laravel cache drivers that accept the same parameter in minutes. So setting a query cache TTL to 5 seconds mean settin a TTL of 5 minutes in the cache store (eg. Redis)

### Steps to reproduce the behaviour
Save a query result with cache TTL = 5

**Comment by patrickbrouwers** [comment]
Thanks for spotting this. A PR for this would be very helpful.

**Comment by patrickbrouwers** [comment]
Reference: https://github.com/laravel-doctrine/orm/blob/1.3/src/Configuration/Cache/IlluminateCacheAdapter.php#L57

**Comment by aledelgo** [comment]
Thanks for the hint, I've already fixed it in my code but never really tested it for float numbers. Now i verified that in the Laravel cache storage the lifeTime number is multiplied again by 60 and accept floats as  so it will work fine with any lifetime number from laravel-doctrine.
I'll do a PR in minutes.

**Comment by patrickbrouwers** [comment]
Fix released as 1.3.2
