### ISSUE TITLE
How to use pagination?

### ISSUE THREAD

**Issue by dickyeka** [laravel-doctrine/orm#217]
EntityManager::getRepository(Product::class)->paginate(); ?

**Comment by maxbrokman** [comment]
See the documentation here: http://www.laraveldoctrine.org/docs/1.2/orm/repositories#pagination

**Comment by dickyeka** [comment]
must use QueryBuilder ? what if i use ORM  EntityManager::getRepository(Product::class) ?

**Comment by patrickbrouwers** [comment]
You can only use the pagination feature of Laravel-Doctrine if you use custom repositories. It's not supported by us nor Doctrine-Core team to call any pagination methods directly on default repositories.

**Comment by guiwoda** [comment]
If you use service location to get your repo, make sure your custom repo is mapped to your entity

**Comment by dickyeka** [comment]
you have example code?

**Comment by guiwoda** [comment]
http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/annotations-reference.html#entity

http://www.laraveldoctrine.org/docs/1.2/fluent/reference#advanced
