### ISSUE TITLE
[BUG] PaginateFromParams `paginateAll` is broken

### ISSUE THREAD

**Issue by maxbrokman** [laravel-doctrine/orm#218]
### Branch: 1.3

https://github.com/laravel-doctrine/orm/blob/31fb87ad8008133236a09c80e761d91cac26abd3/src/Pagination/PaginatesFromParams.php#L9-L38

### Expected behaviour

`PaginateFromParams` `paginateAll` offers a `$page` argument and passes this to `paginate`.

### Actual behaviour

`paginateAll` takes a `$pageName` argument (as with `PaginateFromRequest`) and incorrectly passes this into `paginate` in the `$page` position.

**Comment by patrickbrouwers** [comment]
@guiwoda

**Comment by maxbrokman** [comment]
Did you know you can +1 your own comments?

**Comment by guiwoda** [comment]
You can also fix your own issues! :wink:

**Comment by patrickbrouwers** [comment]
Not as fun as downvoting your comment ;)

**Comment by maxbrokman** [comment]
you guys are mean I not gonna be friends with you any more

**Comment by maxbrokman** [comment]
@guiwoda I could fix my own issues but I have soooo many boring crud controllers to write

**Comment by maxbrokman** [comment]
maybe later in the week

**Comment by guiwoda** [comment]
I'll help :)
