### ISSUE TITLE
1) Narwhal\User\Tests\UserTest::testCreateUser InvalidArgumentException: Unable to locate factory with name [default] [Narwhal\ User\Domain\Entity\User].

### ISSUE THREAD

**Issue by azeem81** [laravel-doctrine/orm#220]
[QUESTION]. how to fix error on running a test.

Factory is defined in /database/factories/ModelFactory.php as below:

   $factory->define(\Narwhal\User\Domain\Entity\User::class, function (Faker\Generator $faker) {
    static $password;

    return [
        'name' => $faker->name,
        'email' => $faker->unique()->safeEmail,
        'password' => $password ?: $password = bcrypt('secret'),
        'phone' => $faker->phoneNumber,
        'status' => $faker->boolean,
        'group' => $faker->randomNumber,

    ];
});

and test is written as:

namespace Narwhal\User\Tests;

use Narwhal\User\Domain\Entity\User;
use PHPUnit\Framework\TestCase;

class UserTest extends TestCase
{
    public function testAddCounter(){
        $this->assertEquals(4,2+2);
    }

    public function testCreateUser(){

        $users = factory(\Narwhal\User\Domain\Entity\User::class)->make();

    }
}

on executing i get error :
InvalidArgumentException: Unable to locate factory with name [default] [Narwhal\User\Domain\Entity\User].

### Steps to reproduce the behaviour

**Comment by patrickbrouwers** [comment]
Did you check our docs: http://www.laraveldoctrine.org/docs/1.3/orm/testing

**Comment by patrickbrouwers** [comment]
Use `entity()` helper like explained in docs.

```
public function testCreateUser(){


    $users = entity(\Narwhal\User\Domain\Entity\User::class)->make();

}
```

**Comment by azeem81** [comment]
now i am getting this error:

PHPUnit 6.0.10 by Sebastian Bergmann and contributors.

.E                                                                  2 / 2 (100%)

Time: 284 ms, Memory: 6.00MB

There was 1 error:

1) Narwhal\User\Tests\UserTest::testCreateUser
Illuminate\Contracts\Container\BindingResolutionException: Target [Doctrine\Common\Persistence\ManagerRegistry] is not instantiable while building [LaravelDoctrine\ORM\Testing\Factory].

**Comment by patrickbrouwers** [comment]
I think you need to extend the Laravel Testcase for this to work.
