### ISSUE TITLE
[BUG] SimpleHydrator ignores parent class' properties when hydrating child class.

### ISSUE THREAD

**Issue by RBastianini** [laravel-doctrine/orm#222]
### Package version, Laravel version
Laravel: 5.2.29
laravel-doctrine: 1.2.8
### Expected behaviour
When using `LaravelDoctrine\ORM\Testing\Factory::create()` to create an instance of a Model that inherits from another one, all *private* properties of the parent model are ignored by `LaravelDoctrine\ORM\Testing\SimpleHydrator` and not set on the model.
### Actual behaviour
I'd expect `LaravelDoctrine\ORM\Testing\Factory::create()` to set all properties that the model has, no matter if they are defined on the class being instantiated or in the parent one.
### Steps to reproduce the behaviour

Create two model classes
```php
class ParentModel
{
  private $property;
}
```
```php
class ChildModel extends ParentModel
{
  private $otherProperty;
}
```

Try to invoke `LaravelDoctrine\ORM\Testing\Factory::create(ChildModel::class, ['parentProperty' => 'someValue', 'otherProperty' => 'someOtherValue');` and only `$otherProperty` will be set, while `$parentProperty` will be null.

I think the issue is that `LaravelDoctrine\ORM\Testing\SimpleHydrator` uses `ReflectionClass::hasProperty($field)` to check if a field is defined on the model, but this ignores private inherited fields. A simple workaround would be to declare them protected instead of private, but this breaks encapsulation, and I would like to avoid it if at all possible.

**Comment by patrickbrouwers** [comment]
Will be supported from next release.
