### ISSUE TITLE
[ISSUE] Validation broken on update from 1.3.1 to 1.3.4

### ISSUE THREAD

**Issue by shane-scalable** [laravel-doctrine/orm#233]
Recently updating packages has caused validation to no longer map the class namespace to the table name for some reason. 

I'm rolling back versions for now until this is fixed.  If I get some downtime and it has not been addressed then I will look into it myself.

### Package version, Laravel version
- Updating laravel/framework (v5.4.15 => v5.4.19) Downloading: 100%         
- Updating laravel-doctrine/orm (1.3.1 => 1.3.4) Downloading: 100%         
- Updating gedmo/doctrine-extensions (v2.4.26 => v2.4.28) Downloading: 100%   

### Expected behaviour
Previous to update validation worked properly when referencing an entity namespace

### Actual behaviour
I recieve the following error after the above upgrade:
`
QueryException in Connection.php line 647:
SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "App\Entities\User" does not exist
LINE 1: select count(*) as aggregate from "App\Entities\User" where ...
^ (SQL: select count(*) as aggregate from "App\Entities\User" where "email" = 23qrwasd@asdf.com)
`
### Steps to reproduce the behaviour
My request object has the folowing validation rules, which has been working until now:
`
public function rules()
    {
        return [
            'first' => 'required|max:255',
            'last' => 'required|max:255',
            'email' => 'required|email|max:255|unique:App\Entities\User,email',
            'type' => 'required|in:admin,screener',
        ];
    }
`
It seems that in one of these updates it broke the reference to the namespace inside of the validation logic.  I am working backwards now to try to determine which version this occurred in, but it seems it may be the Master/Slave connection support ticket as it seems like the most likely to have touched the effected code. https://github.com/laravel-doctrine/orm/pull/214/commits (I am stoked for the Master/Slave connection support also as I will be needing it soon enough for my project :D )

**Update: Confirming that rolling back from 1.3.4 to 1.3.1 did correct the issue

**Comment by iAchilles** [comment]
I have the same issue.

**Comment by patrickbrouwers** [comment]
Fix in 1.3.5
