### ISSUE TITLE
[QUESTION] doctrine:generate:entities src not generate getters and setters

### ISSUE THREAD

**Issue by juanwilde** [laravel-doctrine/orm#234]
My project: laravel 5.3.* with laravel/doctrine 1.2.*

When I perform an `artisan doctrine:generate:entities src --filter=MyClass` the command runs ok but my getters and setters are not created.

This issue is happening to me since I updated all my dependencies (composer update)

This is an example of Entity

    <?php

    namespace Entities;

    use Doctrine\ORM\Mapping as ORM;
    use App\Helpers\DoctrineDateTranlator;

    /**
     * Class Notices
     *
     * @ORM\Table(name="notices")
     * @ORM\Entity(repositoryClass="Repositories\NoticesRepository")
     */
    class Notices
    {
        use DoctrineDateTranlator;

        /**
         * @var \Ramsey\Uuid\Uuid
         *
         * @ORM\Id
         * @ORM\Column(type="uuid", nullable=false)
         * @ORM\GeneratedValue(strategy="CUSTOM")
         * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
         */
        private $id;

        /**
         * @var NoticesTypes
         *
         * @ORM\ManyToOne(targetEntity="NoticesTypes")
         * @ORM\JoinColumn(name="types_code", referencedColumnName="code")
         */
        private $type;

        /**
         * @var NoticesNotifications
         *
         * @ORM\ManyToOne(targetEntity="NoticesNotifications")
         * @ORM\JoinColumn(name="notifications_code", referencedColumnName="code")
         */
        private $notification;
    }

Any idea why now it's not working?

**Comment by patrickbrouwers** [comment]
Nothing has changed in this command for months. You have to use `--generate-methods` to generate the getters and setters.

**Comment by juanwilde** [comment]
![screen shot 2017-05-07 at 14 32 06](https://cloud.githubusercontent.com/assets/6040385/25780947/01f55b46-3332-11e7-9080-e2efc2196ad7.png)

Well, this is the output of the command with `--generate-methods`, but still having no getters and setters.

I tried with my old `composer.json` from a past commit and it works, but now it's not working. This is my actual dependencies:

    "require": {
            "php": ">=5.6.4",
            "laravel/framework": "5.3.*",
            "laracasts/flash": "^2.0",
            "jenssegers/date": "^3.2",
            "laravel-doctrine/orm": "1.2.*",
            "laravel-doctrine/migrations": "1.0.*",
            "lord/laroute": "^2.3",
            "laravel-doctrine/extensions": "1.0.*",
            "gedmo/doctrine-extensions": "^2.4",
            "beberlei/DoctrineExtensions": "^1.0",
            "intervention/image": "^2.3",
            "ramsey/uuid-doctrine": "^1.2",
            "laravel/socialite": "2.0.21",
            "spatie/laravel-cookie-consent": "^1.8",
            "bogardo/mailgun": "^5.0",
            "php-http/guzzle6-adapter": "^1.1",
            "predis/predis": "^1.1",
            "andywer/js-localization": "dev-laravel-5"
       },


Thanks for answer on sunday! I appreciate a lot :)

**Comment by patrickbrouwers** [comment]
Can you try `--generate-methods=true`

**Comment by juanwilde** [comment]
`The "--generate-methods" option does not accept a value. `

If I exectute it without the `src` it generate them ok, but under my `app/Entities` folder instead `src/Entities`

Maybe this could help

**Comment by patrickbrouwers** [comment]
I just tested it on L5.3 with the latest LD1.2 version and for me using `--generate-methods` works.  It also puts them in the `src` folder for me.

As reference: `php artisan doctrine:generate:entities src --generate-methods`

**Comment by juanwilde** [comment]
Thank you. I suspect that it's permission stuff. Because I'm running a Vagrant environment with "NFS" filesystem and in some cases I had permission issues.

For the moment I generated them into app/Entities and then I moved to src/Entities. So this thread could be closes since I think it is not a laravel/doctrine problem.

Thanks a lot again :)

**Comment by patrickbrouwers** [comment]
👍
