### ISSUE TITLE
[PROPOSAL] Make DoctrineCollector widget keys configurable or unique

### ISSUE THREAD

**Issue by zquintana** [laravel-doctrine/orm#237]
Right now in the current model the collector for debugbar collides widget keys with Laravel's built in query collector. This makes it difficult to use Doctrine along side Eloquent with debugging for monitoring. With existing applications it is desirable at times to keep eloquent running alongside Doctrine during the transition. Allowing this to be configurable or using a different key allows both logs to exist side by side.

see https://github.com/laravel-doctrine/orm/blob/1.3/src/Loggers/Debugbar/DoctrineCollector.php#L26

If this is need by more people than myself, I can fork this repo and contribute it.

**Comment by guiwoda** [comment]
I think reading an env variable and defaulting to the current key would be fine.
Your PR would be welcome, @zquintana

**Comment by patrickbrouwers** [comment]
Closing this one as we have a PR #241 for it.
