### ISSUE TITLE
[BUG?] SimpleHydrator should be calling setter method if available

### ISSUE THREAD

**Issue by Fluepke** [laravel-doctrine/orm#238]
In Doctrine it's the application's responsibility of keeping a bidirectional association in sync.

In their [documentation](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/unitofwork-associations.html#important-concepts) it reads as follows:

> Make sure to update both sides of a bidirectional association (or at least the owning side, from Doctrine’s point of view).

When creating an object using a `Factory`, _laravel-doctrine_ relies on the `SimpleHydrator` to create the actual object from the array provided within the custom `Factory`.

The `SimpleHydrator` however does not call the **setter methods** which may be used to keep the _inverse side_ in sync, instead it relies on setting the properties directly.

Furthermore setters might perform checks and validation, so IMO it's reasonable to first check if a setter method exists and if not fallback to setting the property directly.

**Comment by guiwoda** [comment]
Closing this, check #239 for more details.
