### ISSUE TITLE
[QUESTION] Notification want to save notifiable as new

### ISSUE THREAD

**Issue by obeone** [laravel-doctrine/orm#243]
### Package version, Laravel version
Laravel Doctrine : 1.3.5
Laravel : 5.4.26

### Expected behaviour
Notification to be saved in database

### Actual behaviour
Doctrine think that the user is new (and it's not), sio when the notification is saved, an error occured : 
```
A new entity was found through the relationship 'App\Entities\Notification#user' that was not configured to cascade persist operations for entity: App\Entities\Member@0000000010061229000000007960a447. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'App\Entities\Member#__toString()' to get a clue.
```

### Steps to reproduce the behaviour
Notification Entity : 
```
<?php
namespace App\Entities;

use Doctrine\ORM\Mapping AS ORM;

/**
 * @ORM\Entity
 */
class Notification extends \LaravelDoctrine\ORM\Notifications\Notification
{
    /**
     * @var Member
     * @ORM\ManyToOne(targetEntity="App\Entities\Member")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="member_email", referencedColumnName="email")
     * })
     */
    protected $user;
}
```

The entity Member use the trait \LaravelDoctrine\ORM\Notifications\Notifiable and the notification is sent using : 
```
public function toEntity($notifiable)
    {
        return (new \App\Entities\Notification)
            ->to($notifiable)
            ->success()
            ->message('New project')
            ->action('Voir', route('project.detail', ['project', $this->project->getProjectid()]));
    }
```

I think I did everything as indicated in documentation, so I don't understand why Doctrine thinks the Member entity is new

**Comment by obeone** [comment]
I found a workaround by using a merge, to force database to refresh data.

I put : 
```
$notifiable = \EntityManager::merge($notifiable);
```

In the toEntity method of the notification

**Comment by guiwoda** [comment]
You're probably using the `$user` object straight from session.
If Doctrine doesn't know about the object, it won't be in its `IdentityMap` so it will always consider it a new instance.

Your workaround is actually the way to go. Either that or modify the session driver to only save an ID and fetch the real user from Doctrine every time (can be optimized with L2 cache later).

**Comment by bigperson** [comment]
I have the same problem when adding Illuminate\Contracts\Queue\ShouldQueue interface to Notification class. Please tell me the options for solving the problem.

```
$notifiable = \EntityManager::merge($notifiable);
```
Does not solve my problem. 

Laravel Doctrine : 1.4
Laravel : 5.5
Laravel Horizon: 1.0

**Comment by hbouhadji** [comment]
Hello,

I have the same issue when I'm adding `ShouldQueue` to my Notification, any solutions please ?

**Comment by hbouhadji** [comment]
Found a workaround to replace the `merge` since it's deprecated

```
$notifiable = EntityManager::find(get_class($notifiable), $notifiable);
```
