### ISSUE TITLE
[BUG] \LaravelDoctrine\ORM\IlluminateRegistry::resetManager returns null

### ISSUE THREAD

**Issue by adridev** [laravel-doctrine/orm#247]
### Package version, Laravel version
1.3
### Expected behaviour
I guess it should return a fresh entity manager
### Actual behaviour
It returns null

**Comment by patrickbrouwers** [comment]
PR would be much appreciated :)

**Comment by adridev** [comment]
Of course, let me do it ;)

**Comment by adridev** [comment]
There you have it https://github.com/laravel-doctrine/orm/pull/250

**Comment by patrickbrouwers** [comment]
PR merged
