### ISSUE TITLE
[QUESTION] php 7.x

### ISSUE THREAD

**Issue by vv12131415** [laravel-doctrine/orm#248]
do you consider to move to php 7.x only?
Since next version of laravel will require it.
If yes, the same question  for strict types.

**Comment by patrickbrouwers** [comment]
It depends fully on if we will have to support a "Laravel 5.5" only version. Until we can manage to support both 5.4 and 5.5 with the same version of this package, we will support both versions. But changes are high there will be a php 7.x only version which would only be for Laravel 5.5 usage.
