### ISSUE TITLE
[BUG] Implicit faker dependency not declared in composer.json

### ISSUE THREAD

**Issue by Jalle19** [laravel-doctrine/orm#254]
### Package version, Laravel version

1.3.x, Lumen 5.4.x

### Expected behaviour

Library works when project dependencies are installed with `--no-dev`

### Actual behaviour

Library doesn't work at all due to implicit `fzaninotto/faker` dependency (https://github.com/laravel-doctrine/orm/blob/1.3/src/DoctrineServiceProvider.php#L10)

### Steps to reproduce the behaviour

Try to use this library in a project where dependencies are installed with `composer install --no-dev`. The only way to make the library work is to add `fzaninotto/faker` as a dependency to your own project, something that shouldn't have to be done.

**Comment by Korri** [comment]
@Jalle19 This should not be an issue as long as you don't use the entity factory in production, is it?

**Comment by Jalle19** [comment]
No, you can't include the service provider at all without the dependency.

**Comment by Jalle19** [comment]
register() calls registerEntityFactory() which needs the library.

**Comment by maxbrokman** [comment]
Can you provide a stack trace? Should only kick in when you try to get an entity factory.

**Comment by Jalle19** [comment]
I need to look at it tomorrow, I don't remember how to reproduce it at the moment. Still, the fact that there is a use statement and a register method that needs this library strongly suggests that it is an actual dependency, not just somethinf required for testing.

**Comment by Korri** [comment]
`use` and `::class` don't need an existing class, so it should work.

**Comment by maxbrokman** [comment]
I think Laravel used to not require Faker, though it is now in `require-dev` to be fair.

**Comment by patrickbrouwers** [comment]
> use and ::class don't need an existing class, so it should work.

^ Indeed. It shouldn't be a problem as long as you don't try to resolve the Factory anywhere.

**Comment by Jalle19** [comment]
Found an old stack trace, I have a feeling it's not the one that caused me to create this bug report but I don't see how to reproduce this either so let's close this.
