### ISSUE TITLE
[PROPOSAL] Add ability to register custom hydrators through config

### ISSUE THREAD

**Issue by Viniter** [laravel-doctrine/orm#256]
There is currently no nice way of registering custom hydrators, other then fetching the entity manager somewhere in the application bootstrap and calling `$em->getConfiguration()->addCustomHydrationMode()`.

It would be nice if there was an optional field in the configuration, and it would be registered in the `EntityManagerFactory` similarly to custom types or custom functions.

It's a tiny change, I could submit a PR if you're interested.

**Comment by patrickbrouwers** [comment]
PR's are always welcomed :)
