### ISSUE TITLE
OracleConnection

### ISSUE THREAD

**Issue by verissimomanoel** [laravel-doctrine/orm#261]
I found a problem related to Oracle connection. When I try to connect to SERVICE_NAME, this does not work because the code below is missing from the OracleConnection class:
             'servicename' => array_get ($ settings, 'service_name'),
             'service' => array_get ($ settings, 'service'),

These parameters are provided in the documentation of the laravel-oci8 library.

**Comment by patrickbrouwers** [comment]
The `OracleConnection` was added by a pull-request, I have never used it myself, but it seemed to work for him. Maybe `laravel-oci8` library changed in the meantime. Can you provide a PR for this, thanks.

**Comment by verissimomanoel** [comment]
I provide a new PR for this FIX, please aprove that. I need that urgent!

**Comment by fabriciopaulo** [comment]
I'm also not know how to create oracle connection because for use this package apparently is need to use the  Yajra/laravel-oci8 package that not is a good driver.

**Comment by verissimomanoel** [comment]
How to connect I know, but the problem is connect using SERVICE_NAME. In actual version only is possible connect using SID. I submitted a pull request with correction.

**Comment by gmsantos** [comment]
I did this Connection PR a long time ago @patrickbrouwers. Unfortunately I didn't use Oracle anymore and don't know if `laravel-oci8` changed or there are better options.

**Comment by verissimomanoel** [comment]
@patrickbrouwers Any position about PR #262?
