### ISSUE TITLE
[PROPOSAL] Allow persisting entities created with Entity factory

### ISSUE THREAD

**Issue by Korri** [laravel-doctrine/orm#266]
## Issue

So currently almost all my model factories look like this:
```php
$factory->define(Entities\User::class, function (Faker $faker) {
    return [
        'email' => $faker->unique()->email,
        'display_name' => $faker->firstName . ' ' . $faker->lastName,
        'role' => function () {
            return entity(Entities\Role::class)->create();
        },
    ];
});
```
I have to use `create()` for the role because I don't have _cascade persist_ enabled (and I don't want it), so if using `make()` I get a ton of `A new entity was found through the relationship...` errors.

This causes two issues:
   1. When calling `entity(Entities\User::class)->make()` the Role gets saved to database.
   2. When calling `entity(Entities\User::class)->create()` , `EntityManager::flush()` gets called twice which cause performance issues on large entities with multiple relationships.

## Proposal

I have a few solutions to propose, all of them work for me:

### 1. Have `make()` call persist on the entities it creates

__pros__: Transparent and easy to use.
__cons__: Changes the current behaviour.

### 2. Create a new method just for that

Maybe call it `persist()` or `makeAndPersist()`?
__pros__: Clearer and doesn't change current behaviour.
__cons__: One more method that could be confusing.

### 3. Have `FactoryBuilder` persist any entity created through a closure

__pros__: Transparent and easy to use.
__cons__: Less differences than __1.__ but still changes the current behaviour.

**Comment by Korri** [comment]
What do you guys think? I'm happy to send a pull request if you agree with one of the proposed solutions.

**Comment by guiwoda** [comment]
FactoryBuilder is meant to be used in seeding and testing. Performance issues shouldn't be a concern in neither (testing is arguable, but you shouldn't be creating lots of entities in each case anyway.)

Plus, you can always `make` both entities and call persist manually.
I don't believe this is a feature that's really needed. But if I had to decide on it, I'd go for 3. Make is meant to be a "just build the thing" method, so it shouldn't persist. And adding a new method would diverge from Laravel's API.

**Comment by Korri** [comment]
@guiwoda Yes we use it for feature testing.

Some of our tests take up to 2 seconds just inserting entities. I know this is extreme, but we test an `orders` endpoint with pagination, so we end up creating 30 of them, and each order has 3 lines, a customer, a location, a company, a seller, and those have other relationships like product, address etc.. and this ends up doing something close to 400 calls to flush.

I'm ok with solution 3, I sent a PR for solution one, but will do a new one for solution 3.

**Comment by guiwoda** [comment]
@Korri are you using an in-memory database for your end to end tests?

**Comment by Korri** [comment]
@guiwoda not exactly, we use an actual sqlite database, but everything runs inside a transaction that is rolled back after the test.

In essence gives us the speed of in-memory database and the capacity to not re-build the database from scratch every time.

**Comment by Korri** [comment]
But what takes `flush()` time is not the actual database according to my profiling, it's just computing the list of entities that need to be saved every time.

**Comment by Korri** [comment]
Here is the pull request: #284

**Comment by garret-gunter** [comment]
Is there a problem with using ```make()``` and then persisting the entity before returning it from the closure?  I feel like this would cause a lot of confusion if someone was expecting no entities to be persisted from calling ```make()```.  It might be better to somehow inform the closure which method was called on the parent factory ( e.g. ```make()``` vs ```create()```).

**Comment by Korri** [comment]
@garret-gunter I agree with the confusing part, it makes the code a bit confusing, maybe adding a `$persist = false` attribute to make would be cleaner?

One other solution would be to set a  `persistOnMake` flag before calling `make()` from inside the `create()` method.

Both those solution would keep the current behaviour unchanged.

**Comment by garret-gunter** [comment]
I haven't looked into how Laravel factories natively handle the arguments passed to closures in factories.  The current arguments passed to closures in laravel-doctrine are the properties returned from the factory.  

Is it possible to add the flag there?  Or allow us to add it in a 'meta data' type of thing?  Otherwise it might be best to bind a variable to each closure (which would might get messy).

**Comment by Korri** [comment]
You are right, first arguments are the attributes: https://github.com/laravel/framework/blob/9c9b86c692529c82f44c635ef363b4d709bc2f39/src/Illuminate/Database/Eloquent/FactoryBuilder.php#L182

But I was thinking of making it something like (using an extra argument as flag):
```php
public function make(array $attributes = [], $persist = false)
```

**Comment by garret-gunter** [comment]
Yes, but I was talking about the parameters passed to anonymous functions in the factory itself.


```php
$factory->define(\App\Models\Dealers\Dealer::class, function (Faker\Generator $faker, array $attributes = []) {

	// Make user for example purposes.
	$user = entity(\App\Models\User::class)->make();

	// Handle Dealer names.
	$name = $attributes['name'] ?? function ($args) use ($faker) {

			/**
			 * When the function is called, $args will contain the other attributes values.
			 * $args = [
			 *      'user' => \App\Models\User(),  // The parent scopes $user value.
			 *      'foo'  => 'baz',
                         *      'name'  => // This function.  Note: not entirely sure if the 'name' key has a value.
			 *  ]
			 */

			if (!empty($args['user']) && is_object($args['user']) && !is_callable($args['user']) && !empty($args['user']->name)) {
				return $args['user']->name;
			}
			else {
				return $faker->name;
			}
		};

	return [
		'name' => $name,
		'user' => $user,
		'foo'  => 'baz',
	];

});
```

**Comment by Korri** [comment]
Ho ok, I'm not sure how this could help? You want to pass a flag inside the anonymous function?

**Comment by patrickbrouwers** [comment]
PR merged
