### ISSUE TITLE
[PROPOSAL] Querylogging in Laravel Debugbar

### ISSUE THREAD

**Issue by mro95** [laravel-doctrine/orm#267]
I'm using laravel-doctrine 1.2 (laravel 5.3)

I would like some SQL query debug information in de Larvel debugbar (https://github.com/barryvdh/laravel-debugbar). At the moment no queries are shown.

Can you add this feature or is there a way to implement this?

**Comment by mro95** [comment]
After some googling i find this https://github.com/barryvdh/laravel-debugbar/issues/329
In a comment is mentioned that you have you could set .env variable
`DOCTRINE_LOGGER=LaravelDoctrine\ORM\Loggers\LaravelDebugbarLogger`
and it will work, Thanks @nejtr0n.
You might want to add this to your documentation.

**Comment by patrickbrouwers** [comment]
It actually is in the docs: http://www.laraveldoctrine.org/docs/1.3/orm/config-file#logger
