### ISSUE TITLE
Problems installing with composer

### ISSUE THREAD

**Issue by Edwin-Luijten** [laravel-doctrine/orm#27]
I trying yo install this package to test it, but when doing composer require and with minimum-stability set to dev it still says "a typo or the package is not available in a stable-enough version". Any suggestion on what i'm doing wrong?

**Comment by Edwin-Luijten** [comment]
I forgot the top part of the installation read-me (shame on me)

**Comment by patrickbrouwers** [comment]
Good, you found the new package! The package is no packagist package yet (because we don't think it's stable enough yet. You indeed have to add the github link to the vcs list like you found out :)
