### ISSUE TITLE
[BUG] factory methods with objects fail due to strict array requirement since #268

### ISSUE THREAD

**Issue by btaens** [laravel-doctrine/orm#282]
### Package version, Laravel version
laravel-doctrine/orm 1.3.10
laravel/framework 5.4.36

### Expected behaviour
The factory `make()` method should return a new Entity object as it did in 1.3.5 without any problems.

### Actual behaviour
When calling `entity(Entity::class)->make()` or `entity(Entity::class)->create()`, the following exception is thrown:
> Argument 1 passed to LaravelDoctrine\ORM\Testing\FactoryBuilder::applyStates() must be of the type array, object given, called in vendor/laravel-doctrine/orm/src/Testing/FactoryBuilder.php on line 179

### Steps to reproduce the behaviour
Due to a change for testing purposes in 085b38635bb9b79e53096f20ca9066f0eade64d7, all of my unit tests that use Entity objects as return values in factories now fail, as the method `applyStates()` in `FactoryBuilder` now strictly requires an `array` as its `$definition` parameter.

I've used Entity instantiation, and returned an actual entity in the past, as this was a great way to create more complex and diverse factory return values, and also being somewhat closer to the doctrine way of doing things. For example:

```php
// EntityFactory.php
return new Entity($faker->name, $faker->number);
```
And then in my unit tests I would make the entity as usual:
```php
// EntityTest.php
entity(Entity::class)->make();
```
This would work flawlessly.

The solution would be simply to remove the `array` requirement from `applyStates()`. I've tested it, and it seems to work without any problems.

**Comment by porozhnyy** [comment]
Is there any news on this issue?

**Comment by guiwoda** [comment]
@Hunternnm if you know the solution, please send a PR instead of opening an issue.
