### ISSUE TITLE
[BUG] The class name expected but table name received

### ISSUE THREAD

**Issue by dvmedvedev** [laravel-doctrine/orm#283]
### Package version, Laravel version
laravel-doctrine/orm : **1.4.2**
laravel/framework : **v5.5.14**

### Expected behaviour
Successful registration

### Actual behaviour
Looks like the following backtrace:
```
64. ReflectionException("Class users does not exist")
…/vendor/laravel-doctrine/orm/src/IlluminateRegistry.php:335

63. ReflectionClass::__construct("users")
…/vendor/laravel-doctrine/orm/src/IlluminateRegistry.php:335

62. LaravelDoctrine\ORM\IlluminateRegistry::getManagerForClass("users")
…/vendor/laravel-doctrine/orm/src/Validation/DoctrinePresenceVerifier.php:124

61. LaravelDoctrine\ORM\Validation\DoctrinePresenceVerifier::getEntityManager("users")
…/vendor/laravel-doctrine/orm/src/Validation/DoctrinePresenceVerifier.php:93

60. LaravelDoctrine\ORM\Validation\DoctrinePresenceVerifier::select("users")
…/vendor/laravel-doctrine/orm/src/Validation/DoctrinePresenceVerifier.php:46

59. LaravelDoctrine\ORM\Validation\DoctrinePresenceVerifier::getCount("users", "email", "mail@example.com", null, null, [])
…/vendor/laravel/framework/src/Illuminate/Validation/Concerns/ValidatesAttributes.php:638

58. Illuminate\Validation\Validator::validateUnique(/* data */)
…/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:359
```

### Steps to reproduce the behaviour
- Configure Entity like in the documentation
- Configure auth provider
```   
'providers' => [
      'users' => [
            'driver' => 'doctrine',
            'model' => Entities\User::class,
      ],
],
``` 
- Try to register

**Comment by patrickbrouwers** [comment]
Check where you validate for unique users (unique|users probably), you are validating against a table, instead of the class name.

**Comment by dvmedvedev** [comment]
Yes, it’s a validation issue. But it’s out of the box code. I saw the article about the validation, so I will check it. But for now it looks like the chain of calls have an issue on the step of entity manager receiving. There is impossible to get the class name in this place.

**Comment by dvmedvedev** [comment]
@patrickbrouwers You are right. It was not obvious but the article helped. Very sorry of this.

**Comment by marcosdipaolo** [comment]
I changed the default by :
```php
return Validator::make($data, [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:' . \MDP\Entities\User::class],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);
```
and got rid of the error, but still i cannot register new users, it redirects me to the login page and no new user in the database. 
Where could be the issue?
