### ISSUE TITLE
[QUESTION] Problem with password reset

### ISSUE THREAD

**Issue by MateuszPrasal** [laravel-doctrine/orm#287]
### Package version, Laravel version
Laravel 5.5
laraveldoctrine/orm 1.4
### Expected behaviour
Successful password reset
### Actual behaviour
I got message:
`InvalidArgumentException
Password resetter [users] is not defined.`

`
InvalidArgumentException 
…\vendor\laravel\framework\src\Illuminate\Auth\Passwords\PasswordBrokerManager.php67
54
Illuminate\Auth\Passwords\PasswordBrokerManager resolve
…\vendor\laravel\framework\src\Illuminate\Auth\Passwords\PasswordBrokerManager.php51
53
Illuminate\Auth\Passwords\PasswordBrokerManager broker
…\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php221
52
Illuminate\Support\Facades\Facade __callStatic
…\vendor\laravel\framework\src\Illuminate\Foundation\Auth\SendsPasswordResetEmails.php85
51
App\Http\Controllers\Auth\ForgotPasswordController broker
…\vendor\laravel\framework\src\Illuminate\Foundation\Auth\SendsPasswordResetEmails.php33
50
App\Http\Controllers\Auth\ForgotPasswordController sendResetLinkEmail
…\vendor\laravel\framework\src\Illuminate\Routing\Controller.php54
49
 call_user_func_array
…\vendor\laravel\framework\src\Illuminate\Routing\Controller.php54
48
Illuminate\Routing\Controller callAction
…\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php45
47
Illuminate\Routing\ControllerDispatcher dispatch
…\vendor\laravel\framework\src\Illuminate\Routing\Route.php212
46
Illuminate\Routing\Route runController
…\vendor\laravel\framework\src\Illuminate\Routing\Route.php169
45
Illuminate\Routing\Route run
…\vendor\laravel\framework\src\Illuminate\Routing\Router.php645
44
Illuminate\Routing\Router Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php30
43
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\app\Http\Middleware\RedirectIfAuthenticated.php24
42
App\Http\Middleware\RedirectIfAuthenticated handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
41
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
40
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php41
39
Illuminate\Routing\Middleware\SubstituteBindings handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
38
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
37
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php67
36
Illuminate\Foundation\Http\Middleware\VerifyCsrfToken handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
35
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
34
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php49
33
Illuminate\View\Middleware\ShareErrorsFromSession handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
32
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
31
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php63
30
Illuminate\Session\Middleware\StartSession handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
29
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
28
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php37
27
Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
26
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
25
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php59
24
Illuminate\Cookie\Middleware\EncryptCookies handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
23
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
22
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php102
21
Illuminate\Pipeline\Pipeline then
…\vendor\laravel\framework\src\Illuminate\Routing\Router.php647
20
Illuminate\Routing\Router runRouteWithinStack
…\vendor\laravel\framework\src\Illuminate\Routing\Router.php622
19
Illuminate\Routing\Router runRoute
…\vendor\laravel\framework\src\Illuminate\Routing\Router.php588
18
Illuminate\Routing\Router dispatchToRoute
…\vendor\laravel\framework\src\Illuminate\Routing\Router.php577
17
Illuminate\Routing\Router dispatch
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php176
16
Illuminate\Foundation\Http\Kernel Illuminate\Foundation\Http\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php30
15
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php30
14
Illuminate\Foundation\Http\Middleware\TransformsRequest handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
13
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
12
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php30
11
Illuminate\Foundation\Http\Middleware\TransformsRequest handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
10
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
9
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php27
8
Illuminate\Foundation\Http\Middleware\ValidatePostSize handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
7
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
6
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php46
5
Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
4
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
3
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php102
2
Illuminate\Pipeline\Pipeline then
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php151
1
Illuminate\Foundation\Http\Kernel sendRequestThroughRouter
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php116
0
Illuminate\Foundation\Http\Kernel handle
…\public_html\index.php53`
### Steps to reproduce the behaviour

- Require and configure LaravelDoctrine/ORM like in documentation

- Successfully created users table

- Successfully register user and login

**Comment by josenicomaia** [comment]
Hey @Mateo1907,
Could you post your auth.php?
And the class pointed at `auth.providers.users.model`?

**Comment by marcosdipaolo** [comment]
I'll post it for him
```php
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Authentication Defaults
    |--------------------------------------------------------------------------
    |
    | This option controls the default authentication "guard" and password
    | reset options for your application. You may change these defaults
    | as required, but they're a perfect start for most applications.
    |
    */

    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    /*
    |--------------------------------------------------------------------------
    | Authentication Guards
    |--------------------------------------------------------------------------
    |
    | Next, you may define every authentication guard for your application.
    | Of course, a great default configuration has been defined for you
    | here which uses session storage and the Eloquent user provider.
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | Supported: "session", "token"
    |
    */

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
            'hash' => false,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | User Providers
    |--------------------------------------------------------------------------
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | If you have multiple user tables or models you may configure multiple
    | sources which represent each model / table. These sources may then
    | be assigned to any extra authentication guards you have defined.
    |
    | Supported: "database", "eloquent"
    |
    */

    'providers' => [
        'users' => [
            'driver' => 'doctrine',
            'model' => MDP\Entities\User::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Resetting Passwords
    |--------------------------------------------------------------------------
    |
    | You may specify multiple password reset configurations if you have more
    | than one user table or model in the application and you want to have
    | separate password reset settings based on the specific user types.
    |
    | The expire time is the number of minutes that the reset token should be
    | considered valid. This security feature keeps tokens short-lived so
    | they have less time to be guessed. You may change this as needed.
    |
    */

    'password' => [
        'email' => 'emails.password',
        'table' => 'password_resets',
        'expire' => 60,
    ],

];

```

**Comment by marcosdipaolo** [comment]
Actually this is one of the configs I've tried, and nothing.

Also

```php
'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => User::class,
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
            'hash' => false,
        ],
    ],
```

and

```php
  'providers' => [
        User::class => [
            'driver' => 'doctrine',
            'model' => User::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],
```

**Comment by marcosdipaolo** [comment]
# Found the problem
## Here my config:
```php
<?php

use MDP\Entities\User;

return [

    /*
    |--------------------------------------------------------------------------
    | Authentication Defaults
    |--------------------------------------------------------------------------
    |
    | This option controls the default authentication "guard" and password
    | reset options for your application. You may change these defaults
    | as required, but they're a perfect start for most applications.
    |
    */

    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    /*
    |--------------------------------------------------------------------------
    | Authentication Guards
    |--------------------------------------------------------------------------
    |
    | Next, you may define every authentication guard for your application.
    | Of course, a great default configuration has been defined for you
    | here which uses session storage and the Eloquent user provider.
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | Supported: "session", "token"
    |
    */

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        'api' => [
            'driver' => 'token',
            'provider' => 'users',
            'hash' => false,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | User Providers
    |--------------------------------------------------------------------------
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | If you have multiple user tables or models you may configure multiple
    | sources which represent each model / table. These sources may then
    | be assigned to any extra authentication guards you have defined.
    |
    | Supported: "database", "eloquent"
    |
    */

    'providers' => [
        'users' => [
            'driver' => 'doctrine',
            'model' => User::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Resetting Passwords
    |--------------------------------------------------------------------------
    |
    | You may specify multiple password reset configurations if you have more
    | than one user table or model in the application and you want to have
    | separate password reset settings based on the specific user types.
    |
    | The expire time is the number of minutes that the reset token should be
    | considered valid. This security feature keeps tokens short-lived so
    | they have less time to be guessed. You may change this as needed.
    |
    */

    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],

];

```

**Comment by marcemarin** [comment]
HI, how did you solve it?

**Comment by eigan** [comment]
@marcemarin Please open a new issue explaining your problem. No need to revive this old issue 🙂
