### ISSUE TITLE
 [QUESTION] Can I use pagination for AJAX calls?

### ISSUE THREAD

**Issue by bogdan-dubyk** [laravel-doctrine/orm#299]
### Run `toJson()` method

I know it's not easy to convert entity to JSON, but I think it should be a part of a package otherwise this pagination is not fully functional. If I'm wrong and pagination already supports converting to JSON, please help me to resolve the issue. Or maybe there some workarounds to make it works. First what I think is loop through each item and convert it using JMSSerializer  but it will have a bad effect on performance

**Comment by sstutz** [comment]
you might wanna take a look at https://fractal.thephpleague.com/ :)

**Comment by bogdan-dubyk** [comment]
hmm, as I understand it's pretty same as  JMSSerializer but maybe it's bit lighter but still requires extra work (creating transformer and so on) to do. It's sad that current logic is not supporting transformation out of the box. Thanks @sstutz,  will compare the performance of both fractal and JMS and choose best one.

**Comment by bogdan-dubyk** [comment]
Maybe it will be helpful for someone, I made performance comparison of JMSSerialize and Fractal.

**Entity (I'm adding JMS annotation here once to not duplicate entity, but for fractal example, we do not need those JMS annotations).**

```
/**
 * @ORM\Entity()
 * @JMS\ExclusionPolicy("NONE")
 */
class Campaign
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer", length=10)
     * @JMS\Groups({"for_campaign_list"})
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=55, unique=true)
     * @JMS\Groups({"for_campaign_list"})
     */
    protected $name;

    /**
     * @ORM\Column(type="decimal", name="cpi")
     * @JMS\Type("double")
     * @JMS\Groups({"for_campaign_list"})
     */
    protected $cpi;

    /**
     * @ORM\Column(type="integer")
     * @JMS\Type("integer")
     * @JMS\Groups({"for_campaign_list"})
     */
    protected $testMode;
```

**Query:**
```
public function paginateAllForUser(int $limit = 10, int $page = 1, $sort = null) : LengthAwarePaginator
{
    $query = $this->createQueryBuilder('campaign');
    if(isset($sort)) {
       $sort = explode('|', $sort);
       $query->orderBy($sort[0], $sort[1]);
     }
     $query = $query->getQuery();
      return $this->paginate($query, 10, $page);
}
```

**JMS example:**
```
$campaigns =  $this->campaignRepository->paginateAllForUser($limit, $page, $sort);
$serializer = app('SerializerDoctrine');
$serializedItems = Collection::make([]);
foreach ($campaigns->items() as $campaign) {
$serializedItems->push(
    $serializer->serialize($campaign, 'json', SerializationContext::create()->setGroups(['for_campaign_list'])));
}
$campaigns->setCollection($serializedItems);
$json =  $campaigns->toJson();
```

**Fractal Example:**
_Transformer_
```
class CampaignTransformer extends Fractal\TransformerAbstract
{
    public function transform(Campaign $campaign)
    {
        return [
            'id'      => (int) $campaign->getId(),
            'name'   => $campaign->getName(),
            'testMode' => $campaign->getTestMode(),
            'cpi'    => $campaign->getCpi(),
        ];
    }
}
```
_Serialization_
```
$campaigns =  $this->campaignRepository->paginateAllForUser($limit, $page, $sort);
$fractal = new Manager();
$resource = new FractalCollection($campaigns->items(), new CampaignTransformer());
$resource->setPaginator(new IlluminatePaginatorAdapter($campaigns));
$json = $fractal->createData($resource)->toJson();
```

**Performance benchmarks:**
I have 1000 records.
_JMS_ 
10 per page = 0.13 seconds
100 per page = 1.08  seconds
1000 per page = 8.54  seconds

_Fractal_ 
10 per page = 0.13 seconds
100 per page = 0.96 seconds
1000 per page = 7.93 seconds

Fractal is faster when the amount of items per page is big, but with small amounts, the difference is almost not noticeable. From another side, JMS transformation logic is serving inside entity or .yml but Fractal requiring to create Transformers.

So as for me, JMS is comfortable because require less amount of code to add and I do not need to return a lot of items per page. But if you are returning big amount of items per page or not using annotation maybe Fractal is better solution
