### ISSUE TITLE
[PROPOSAL] Don't extend the auth manager unless it's been bound

### ISSUE THREAD

**Issue by Jalle19** [laravel-doctrine/orm#302]
### Package version, Laravel version

1.4, 5.5

### Expected behaviour

https://github.com/laravel-doctrine/orm/blob/1.4/src/DoctrineServiceProvider.php#L251 should check if the auth manager has been bound before extending it.

### Actual behaviour

It doesn't check, so the auth manager is built from the container whether we need it or not

I've been trying to optimize an application and despite my best efforts this service provider is still the heaviest to register/boot. We don't use the Auth manager at all so the work done here is of no use to us, thus it would be great if it was optional, like `extendNotificationChannel`.

I can make a PR if this has a chance of getting accepted.

**Comment by garret-gunter** [comment]
It might be a good idea to bind only after the manager is resolved using `afterResolving` (https://laravel.com/api/5.5/Illuminate/Container/Container.html#method_afterResolving).

That should solve your problem, while at the same time avoiding the practice of resolving a bound class during service registration.

**Comment by Jalle19** [comment]
Should the extending of the notification manager get the same treatment?

**Comment by garret-gunter** [comment]
I don't think it would hurt.  It wouldn't be as impactful as the auth manager.  I'm not very familiar with the channel manager's lifecycle.

**Comment by Jalle19** [comment]
Okay. I'll make a PR.

**Comment by Jalle19** [comment]
https://github.com/laravel-doctrine/orm/pull/308
