### ISSUE TITLE
Question - Laravel 5.6 support?

### ISSUE THREAD

**Issue by mattkoch614** [laravel-doctrine/orm#303]
I realize Laravel 5.6 is very new at the time I post this, but it looks like this package isn't usable at this time for projects on that version.

### Package version, Laravel version
Laravel Doctrine 1.4, Laravel 5.6

### Expected behaviour
Laravel Doctrine can be installed.

### Actual behaviour
Laravel Doctrine fails to install.

```
Your requirements could not be resolved to an installable set of packages.
```
### Steps to reproduce the behaviour
``composer require "laravel-doctrine/orm:1.4.*"``

**Comment by patrickbrouwers** [comment]
Should be able to install it now.

**Comment by mattkoch614** [comment]
@patrickbrouwers Thank you!
