### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by mehulboricha** [laravel-doctrine/orm#316]
I am using composer require "laravel-doctrine/orm:1.4.*" on laravel 5.5. I am getting the following error.

In Setup.php line 139:

  Type error: Argument 1 passed to Doctrine\ORM\Tools\Setup::createCacheConfi
  guration() must be of the type boolean, null given, called in /srv/users/se
  rverpilot/apps/astutelinks/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup
  .php on line 126

How to fix this?

**Comment by patrickbrouwers** [comment]
Looking at that method `private static function createCacheConfiguration(bool $isDevMode, string $proxyDir, ?Cache $cache) : Cache`, it would mean you don't have `APP_DEBUG=false/true` in your .env

**Comment by patrickbrouwers** [comment]
Also fixed by : https://github.com/laravel-doctrine/orm/pull/315

**Comment by mehulboricha** [comment]
Thank You so Much :)
