### ISSUE TITLE
[BUG] - carbon timestamps mapped through $builder->timestamps() not working

### ISSUE THREAD

**Issue by catalinbuletin** [laravel-doctrine/orm#317]
Hello,
I am using doctrine/orm 1.4.3, and Laravel version 5.5.34

I want to overwrite all `datetime` and `date` types to Carbon instances in particular the ones mapped through the `$builder->timestamps()` method. 

The ones mapped through `$builder->carbonDate()` works as expected.

#### Mapper:

```
public function map(Fluent $builder)
    {
        $builder->field('uuid_binary', 'id')->primary();
        $builder->string('name');
        $builder->carbonDate('someDate');
        $builder->timestamps();
    }
```

#### Config

```
    ...
    'mapping_types' => [
                'date' => 'carbondate',
                'datetime' => 'carbondatetime',
                'datetimetz' => 'carbondatetimetz',
            ]
    ....

    'extensions'                 => [
        LaravelDoctrine\Extensions\Timestamps\TimestampableExtension::class,
    ],
    ....
    
    'custom_types'               => [
        'carbondate'       => DoctrineExtensions\Types\CarbonDateType::class,
        'carbondatetime'   => DoctrineExtensions\Types\CarbonDateTimeType::class,
        'carbondatetimetz' => DoctrineExtensions\Types\CarbonDateTimeTzType::class,
        'carbontime'       => DoctrineExtensions\Types\CarbonTimeType::class,
    ]
```
    In my model I am using the `LaravelDoctrine\Extensions\Timestamps` trait.

   
### Expected behaviour
I would expect that the instances of the createdAt and updatedAt properties on my model to be of type `\Carbon\Carbon`. 

### Actual behaviour
The instances of createdAt and updatedAt properties are of type \DateTime
   
Another issue that i am seeing is with doctrine validator - after i've added the mapping_types it shows this:

> Validating for default entity manager...
> [Mapping]  OK - The mapping files are correct.
> [Database] FAIL - The database schema is not in sync with the current mapping file. 

And after I update the schema:

> Checking if database connected to default entity manager needs updating...
> Updating database schema...
> Database schema updated successfully! "13" queries were executed

The validator shows the same thing - `The database schema is not in sync with the current mapping file.`

Anything I am not seeing?

Thanks a lot!

**Comment by patrickbrouwers** [comment]
Timestamps() defaults to `timestamps` not to Carbon. The only way to override that is to use `carbonDate()` manually

**Comment by catalinbuletin** [comment]
Hey, thanks for the response.

I was thinking that since I am overwriting the `datetime` with `carbondatetime` type, the `timestamps()` would pick that up and serve the correct instances

**Comment by catalinbuletin** [comment]
So then, since this is not a bug, I can change it to a proposal if you think it makes sense to be implemented.

**Comment by patrickbrouwers** [comment]
Just found out how you can configure it:

```
$builder->timestamps('createdAt', 'updatedAt', 'carbondatetime');
```

**Comment by patrickbrouwers** [comment]
Perhaps you could also overwrite the macro: https://laraveldoctrine.org/docs/1.3/fluent/reference#macros and default it to carbon.

**Comment by catalinbuletin** [comment]
Alright! Awesome stuff! 

Thanks a lot for the support and the really awesome job you guys did with this package!

I'll let you know once I try this if I still get that schema validator issue.

**Comment by patrickbrouwers** [comment]
Thanks! You'r welcome :)
