### ISSUE TITLE
getProxyDefinition(): Failed opening required '/tmp/__CG__AppTeam.php' 

### ISSUE THREAD

**Issue by MECU** [laravel-doctrine/orm#32]
Error:
`Doctrine\Common\Proxy\AbstractProxyFactory::getProxyDefinition(): Failed opening required '/tmp/__CG__AppTeam.php' (include_path='.:/usr/lib/php:/usr/local/lib/php:/usr/local/bin')`

It sounded like a permissions problem (but on `/tmp`?), and this [StackOverflow](http://stackoverflow.com/questions/19066140/doctrine-error-failed-opening-required-tmp-cg-source-php) slightly agrees. I even generated the proxies manually as the SO suggests, but I still get this error.

Even worse, my app properly generated into `/home/../storage/proxies`, but this page says it's looking into `/tmp`.

I did clear my cache with artisan and composer and have no outstanding composer updates.

I'm not sure if all the changes in the 1.0.0 may fix this problem. I don't have an easy way to test that.

**Comment by patrickbrouwers** [comment]
Hey!

I assume you were using dev-master. This problem was something I've fixed in dev-develop. However I decided to merge develop into master, so people won't run into these problems anymore when testing the package.

Let me know if it's fixed after a composer update. (Note don't forget to update doctrine.php config to the new version)

**Comment by MECU** [comment]
That fixed it. I upgraded to ~1.0 and it installed 1.0.x-dev.

**Comment by bskimball** [comment]
I have this same issue when using an ArrayCollection, I however have 'auto-generate' set to false. I am running version 1.0.13. Changing 'auto-generate' to true seems to fix the issue.

**Comment by skaterdav85** [comment]
I think I might be getting the same error, but I am using Lumen.

```
FatalErrorException in AbstractProxyFactory.php line 209:
Doctrine\Common\Proxy\AbstractProxyFactory::getProxyDefinition(): Failed opening required '/Users/dtang/Sites/side-projects/shoes-api/storage/proxies/__CG__AppEntitiesGender.php' (include_path='.:')
```

```php
use Doctrine\ORM\Mapping AS ORM;
class Size {
  /**
   * @ORM\OneToOne(targetEntity="Gender")
   * @ORM\JoinColumn(name="gender_id", referencedColumnName="id")
   */
  private $gender;
}
```

 I'm also new to Doctrine so would appreciate any feedback.

**Comment by patrickbrouwers** [comment]
If in the future anybody encounters this problem:
- auto generate (`DOCTRINE_PROXY_AUTOGENERATE`) set to true. However only do this in development! You don't want (and need) that overhead on production environments.
- `php artisan doctrine:generate:proxies` when you deploy to production.
