### ISSUE TITLE
[BUG] metadata cache setting not used

### ISSUE THREAD

**Issue by bjdelange** [laravel-doctrine/orm#320]
I'm working through some performance issues and noticed that even though I have `DOCTRINE_CACHE=memcached` it still uses `ArrayCache` for annotations. 
It works correctly for class metadata, which are cached with Laravel's `MemcachedStore`.

I traced the cause to the method `\Doctrine\ORM\Configuration::newDefaultAnnotationDriver`, which has a hardcoded instantiation of `ArrayCache`. This is still true for the latest version of doctrine.

To compare with a different environment I started up a Symfony 4 project. The cache works perfectly out of the box when configured to use memcached. It does not, however, use that `newDefaultAnnotationDriver` method.

I've been trying to fix this but I haven't found a way yet; annotations uses a different code path than the other cacheable systems.

**Comment by patrickbrouwers** [comment]
I'm wondering if it will actually change performance. If cache is enabled the entire metadata is cached, so it wouldn't even reach the annotation reader?

**Comment by bjdelange** [comment]
That's the problem: cache *is* enabled but annotations are still being parsed and stored in arraycache each request.

**Comment by patrickbrouwers** [comment]
That's weird, I have tested that before with metadata-cache enabled and it didn't get into the annotations parser.

**Comment by bjdelange** [comment]
I've also just noticed that ArrayCache's namespace is empty, but MemcachedStore has it set correctly. Strange anyway.. ArrayCache is a Doctrine class but MemcachedStore belongs to Laravel. It's obvious ArrayCache shouldn't be used at all here.
Could it maybe be a problem when using Gedmo extensions ?

**Comment by patrickbrouwers** [comment]
That could be a possibility. Can you try and reproduce it without Gedmo?

**Comment by bjdelange** [comment]
Yeah.. working on it..

**Comment by bjdelange** [comment]
Disabling Gedmo (and removing all it's annotations to prevent errors) has no effect, unfortunately.
It may need some attention anyway though, two classes are missing:

![image](https://user-images.githubusercontent.com/2757512/37706568-43be12ac-2d00-11e8-89b3-22fb2af3c60c.png)

**Comment by patrickbrouwers** [comment]
That's just because you haven't installed Fluent. It will only use those classes when Fluent is installed.

**Comment by bjdelange** [comment]
Okay, that's unrelated then. I installed it but it had no effect on the caching.

I'm at a loss as to where I should continue my search..

**Comment by patrickbrouwers** [comment]
Can you check this one: https://github.com/laravel-doctrine/orm/pull/295

**Comment by bjdelange** [comment]
That PR is perfect, spot on !

**Comment by patrickbrouwers** [comment]
Reopend it, can you do a review on it as well and test if it solves your problem and confirm there? Thanks!

**Comment by eigan** [comment]
Please reopen this issue if you still got this problem @bjdelange. I am not able to reproduce, so it is really difficult for me to help out. Seems like noone else have this problem either :(
