### ISSUE TITLE
 I want use doctrine 2.7

### ISSUE THREAD

**Issue by acodercat** [laravel-doctrine/orm#322]
please update, thx!

**Comment by patrickbrouwers** [comment]
There's no doctrine 2.7.... ??? https://github.com/doctrine/doctrine2/releases

**Comment by eigan** [comment]
@acodercat If you mean the released doctrine/dbal 2.7;

```diff
+ "doctrine/dbal": "2.7.1 as 2.6.3"
```
_Should probably not do it though._
