### ISSUE TITLE
[BUG] Unique Validation Rules with Additional Where Clauses

### ISSUE THREAD

**Issue by babonzz** [laravel-doctrine/orm#323]
### Package version, Laravel version
"laravel-doctrine/orm": "1.4.*", Laravel 5.5

https://www.laraveldoctrine.org/docs/current/orm/validation
Section: Adding Additional Where Clauses

```
$this->validate($request, [
            'name' => 'required|string|unique:App\Product,name,NULL,id,deleted_at,NULL']);
```

This does not exclude deleted_at == NULL.

After looking at the query, its like
```
SELECT * FROM products WHERE products.name = 'iPhone 7' AND products.deleted_at = 'NULL';
```
instead of
```
SELECT * FROM products WHERE products.name = 'iPhone 7' AND products.deleted_at IS NULL;
```

**Comment by babonzz** [comment]
Added PR https://github.com/laravel-doctrine/orm/pull/324

**Comment by patrickbrouwers** [comment]
PR merged
