### ISSUE TITLE
[BUG] Connection always tries to detect server version when created

### ISSUE THREAD

**Issue by AnatolyRugalev** [laravel-doctrine/orm#325]
Here's the thing.

When I instantiate any repository via entity manager, doctrine creates connection to detect server version. This behavior can be changed with adding `serverVersion` option in `Driver::resolve()` method. 

I think we should provide a way to set server version via configuration. Otherwise, my Artisan won't run without existing database connection because of repository injections in some CLI tools.

See [doctrine docs](https://github.com/doctrine/dbal/blob/master/docs/en/reference/configuration.rst#automatic-platform-version-detection).

### Package version, Laravel version
laravel-doctrine/orm: 1.4.5
laravel/lumen-framework: v5.5.2
### Expected behaviour

Developer can set `serverVersion` via configuration

### Actual behaviour

Developer cannot set `serverVersion` in any possible way without overriding `ConnectionManager` and connections itself

### Steps to reproduce the behaviour

1. Add repository dependency to any Artisan's command constructor
2. Stop database or brake connection to it
3. Run artisan with any command

### Affected databases:

All database drivers which inherit `VersionAwarePlatformDriver` doctrine interface:
* MySQL
* PostgreSQL
* SQL Server
* SQL Anywhere (has no support in laravel-doctrine/orm as I can see) #

**Comment by patrickbrouwers** [comment]
PR merged
