### ISSUE TITLE
[BUG] The Paginator does not support Queries which only yield ScalarResults

### ISSUE THREAD

**Issue by kfeng0806** [laravel-doctrine/orm#329]
Hello,

While working with doctrine paginator if there in query has join statement, it throws error "The Paginator does not support Queries which only yield ScalarResults."

### Package version, Laravel version
laravel-doctrine/orm: 1.4.6
laravel: 5.5

### Expected behaviour
paginate method returns `Illuminate\Pagination\LengthAwarePaginator` instance.

### Actual behaviour
error "The Paginator does not support Queries which only yield ScalarResults" occur.

### Steps to reproduce the behaviour
I have added a test [here](https://github.com/kfeng0806/orm/blob/1.4/tests/Pagination/PaginatorAdapterTest.php#L30-L39)

**Comment by niksynov** [comment]
@kfeng0806 Hey! How did you solve this problem?

**Comment by kfeng0806** [comment]
> @kfeng0806 Hey! How did you solve this problem?

You can use left join, there is an example from my project
```php
$this->qb->leftJoin(PostFavorite::class, 'favorite', 'with', $this->qb->expr()->eq('favorite.post', 'post'))
```
