### ISSUE TITLE
[PROPOSAL] Incomplete info about SimplifiedXML metadata driver in docs and config file

### ISSUE THREAD

**Issue by Oleg-Arkhipov** [laravel-doctrine/orm#330]
### Expected behaviour
Description of SimplifiedXML metadata driver [here](https://www.laraveldoctrine.org/docs/1.3/orm/meta-data-configuration) and [here](https://github.com/laravel-doctrine/orm/blob/e2997b3525a7e6f6c584a7ec2267cd4c0c7e5179/config/doctrine.php#L15) should contain information about `simplified_xml` key used to enable this driver.

**Comment by patrickbrouwers** [comment]
Feel free to PR

**Comment by eigan** [comment]
PR merged. Thanks for the report :)
