### ISSUE TITLE
Styleci configuration issue with linting

### ISSUE THREAD

**Issue by eigan** [laravel-doctrine/orm#333]
> The provided config option 'linting' was not valid.

https://github.styleci.io/analyses/XVL336

botman/botman had same issue and fixed it by doing this:
https://github.com/botman/botman/commit/80d3f07920e3a38160746b128ff8173a5b2dfd9a

I guess someone with access to the styleci account should be able to fix this, as there is no styleci file in this repo.

**Comment by patrickbrouwers** [comment]
Fixed, thanks
