### ISSUE TITLE
[QUESTION] Using Repositories

### ISSUE THREAD

**Issue by mattkoch614** [laravel-doctrine/orm#335]
- Package version: 1.4
- Laravel version: 5.6

### Expected behaviour
When attempting to bind a custom repository in ``AppServiceProvider``, I am able to access the entity manager and the getRepository method as described here: https://www.laraveldoctrine.org/docs/current/orm/repositories

### Actual behaviour
I get the following error message:

```
Non-static method Doctrine\\ORM\\EntityManager::getRepository() should not be called statically
```

**Comment by eigan** [comment]
Sounds like you are using the `Doctrine\ORM\EntityManager` directly and not the Facade (`\EntityManager`). Try `\EntityManager::getRepository()` instead.

**Comment by AkenRoberts** [comment]
@mattkoch614 Did @eigan's advice help?

**Comment by mattkoch614** [comment]
@AkenRoberts Once I get a chance to check what I ended up doing I'll report back.

**Comment by patrickbrouwers** [comment]
^ what @eigan says

**Comment by Noext** [comment]
> Sounds like you are using the `Doctrine\ORM\EntityManager` directly and not the Facade (`\EntityManager`). Try `\EntityManager::getRepository()` instead.

it is working , documentation is wrong, it missing the \

**Comment by mattkoch614** [comment]
Apologies for not replying back, this was so long ago I haven't even seen the code in a while. I am sure these answers are indeed correct!
