### ISSUE TITLE
[BUG] Commands need update from fire() to handle()

### ISSUE THREAD

**Issue by tvogt** [laravel-doctrine/orm#336]
Please prefix your issue with one of the following: [BUG] [PROPOSAL] [QUESTION].

### Package version, Laravel version
1.3.8 with Laravel 5.5.40

### Expected behaviour
it works

### Actual behaviour
  Method LaravelDoctrine\ORM\Console\InfoCommand::handle() does not exist  

### Steps to reproduce the behaviour
call any doctrine: console command

**Comment by eigan** [comment]
You should use laravel doctrine 1.4.x with Laravel 5.5+

**Comment by patrickbrouwers** [comment]
What @eigan says ^

**Comment by petemcfarlane** [comment]
It'd be great if this was on the docs, right now they just take me to version 1.3 - version 1.4 isn't mentioned anywhere so far as I can see?

<img width="1166" alt="screen shot 2018-08-07 at 15 37 02" src="https://user-images.githubusercontent.com/3472717/43782674-c75808b0-9a57-11e8-83ca-1c3d648bff4d.png">

**Comment by patrickbrouwers** [comment]
No documentation changes I think, never got around to adding it to the docs
