### ISSUE TITLE
[QUESTION] API documentation

### ISSUE THREAD

**Issue by TerraTech** [laravel-doctrine/orm#338]
Does LaravelDoctrine have online API documentation like:
https://laravel.com/api/5.6/Illuminate.html

I've poked around and haven't found any.  FWIW, I stumbled upon the Laravel API docs by accident while searching for information on the 'MessageBag' class.

Thank!

**Comment by patrickbrouwers** [comment]
We don't, but we also don't really expose a lot of public api's. For doctrine's API, see: https://www.doctrine-project.org/api/orm/2.7/index.html
