### ISSUE TITLE
[QUESTION] Any known limitation, such as can we use the assertDatabaseHas

### ISSUE THREAD

**Issue by bicatu** [laravel-doctrine/orm#340]
Hi,

I am using Laravel 5.6, Laravel Doctrine ORM 1.4 with  sqlite (in memory) for tests.

I've overridden my setupTraits to be

```php
    protected function setUpTraits()
    {
        $uses = parent::setUpTraits();

        if (isset($uses[DatabaseMigrations::class])) {
            $this->runDatabaseMigrations();
        }

        return $uses;
    }
```

Which is being executed fine.

When I use the $this->assertDatabaseHas and pass the name of the table it gives me

Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 no such table: items (SQL: select count(*) as aggregate from "items" where ("id" = d165843f-6792-478b-a77d-ab18f14dd152))

**Comment by porozhnyy** [comment]
`assertDatabaseHas` creates a new connection. I for myself redefined the method `assertDatabaseHas` and check the data in the current connection with `app('em')...`

**Comment by bicatu** [comment]
Hi could you share a gist or even suggest a PR for that?

**Comment by keithbrink** [comment]
Here's what I used to get `assertDatabaseHas` working:

```
$pdo = app()->make(\Doctrine\ORM\EntityManagerInterface::class)->getConnection()
            ->getWrappedConnection();

app()->make(\Illuminate\Database\ConnectionInterface::class)->setPdo($pdo);
```

That can go anywhere before the method is called, I put it into a trait for tests that use Doctrine.

Stole the idea from here: https://github.com/laravel-doctrine/orm/issues/304#issuecomment-413218029
