### ISSUE TITLE
[PROPOSAL] No command like `doctrine:generate:repositories`

### ISSUE THREAD

**Issue by vv12131415** [laravel-doctrine/orm#342]
### Package version, Laravel version
Laravel 5.6.29
laravel-doctrine/orm 1.4.7

### Expected behaviour
there is a command like `doctrine:generate:repositories` that will do something like what `orm:generate-repositories` does in original package
### Actual behaviour
no command

**Comment by patrickbrouwers** [comment]
You can always PR one

**Comment by vv12131415** [comment]
Sure thing, will try to do this on weekends
