### ISSUE TITLE
[PROPOSAL] change mapping_file config name to mappings_config_key

### ISSUE THREAD

**Issue by gadelkareem** [laravel-doctrine/orm#348]
The `mapping_file` config is misleading because it internally look for the config key in the application. Moving the config into another path will cause the mappings to break while no instructions to load the mappings config dynamically. 

### Package version, Laravel version
5.6
### Steps to reproduce the behaviour
Moving the config file `mappings.php` into another path will cause the mappings to break while no instructions to load the mappings config dynamically.

**Comment by TomHAnderson** [comment]
Closing; expired.
