### ISSUE TITLE
[BUG] Metadata for extension is regenerated if entity is not using that extension. 

### ISSUE THREAD

**Issue by garret-gunter** [laravel-doctrine/orm#349]
Please prefix your issue with one of the following: [BUG] [PROPOSAL] [QUESTION].

### Package version, Laravel version
Version: 1.4.9
Laravel: 5.5.43

### Expected behaviour

Gedmo extensions store an empty array for metadata if an entity does not use the extensions.  This is so it doesn't parse the entity multiple times. [See](https://github.com/Atlantic18/DoctrineExtensions/blob/113a5c0494254d2e29d8b4ebc622dba0c8abe922/lib/Gedmo/Mapping/ExtensionMetadataFactory.php#L100-L107). When retrieving the cache entry later, an empty array should be returned and metadata shouldn't need to be parsed again.

### Actual behaviour

`\LaravelDoctrine\ORM\Configuration\Cache\IlluminateCacheAdapter` returns false for falsey values and empty arrays are converted into false.  So the metadata is always parsed and the cache key is written every time.

### Steps to reproduce the behaviour

1.  Enable two doctrine extensions in config.  
2.  Make an entity that does not use one extension, but uses the other extension.  
3.  Cache the metadata for the entity.  
4.  Start a new session and retrieve the entity's metadata.

### Proposed fix

Use null coalesce instead of ternary operator when fetching values.

**Comment by patrickbrouwers** [comment]
Merged
