### ISSUE TITLE
Cannot use Symfony\Component\Console\Command\Command as Command because the name is already in use

### ISSUE THREAD

**Issue by Amrit01** [laravel-doctrine/orm#35]
When trying to publich vendor

```php artisan vendor:publish --tag="config"```

```PHP Fatal error:  Cannot use Symfony\Component\Console\Command\Command as Command because the name is already in use in /var/www/html/laravel-doctrine/vendor/laravel-doctrine/orm/src/Console/ConvertConfigCommand.php on line 17```

                                                                                                      
  [Symfony\Component\Debug\Exception\FatalErrorException]                                             
  Cannot use Symfony\Component\Console\Command\Command as Command because the name is already in use

**Comment by Amrit01** [comment]
making alias as SymfonyCommand Fixed it should i make a PR

**Comment by patrickbrouwers** [comment]
I couldn't reproduce the issue strangely, but it should indeed fail. Pushed a fix.

**Comment by FoxxMD** [comment]
:+1:
