### ISSUE TITLE
[BUG] with the ClockworkLogger Laravel 5.7 + Clockwork 3

### ISSUE THREAD

**Issue by jaimyborgman** [laravel-doctrine/orm#353]
### Package version, Laravel version
Laravel 5.7
laravel-doctrine/orm 1.4.9
itsgoingd/clockwork v3.0.2

### Actual behaviour
When activated the ClockworkLogger within the config/doctrine.php file like defined below:
'logger' => LaravelDoctrine\ORM\Loggers\ClockworkLogger,

I'll get the following error message everywhere CLI, UI and even at composer install until i've set the config back to false :-). It's trying to boot 'Mailer' inside the service provider but isn't possible to load. While the application itself is booting the 'MailServiceProvider'.

ReflectionException thrown with message "Class mailer does not exist"

### Steps to reproduce the behaviour
Install clockwork through composer (i've done it for --dev only) and activate the logger in the doctrine config file.

**Comment by garret-gunter** [comment]
I booted up a test site and it seems to be working for me.  

Steps I took:
1.  Installed laravel/laravel project with composer.
2.  Ran `composer require laravel/laravel laravel-doctrine/orm`. 
3.  Published config for Laravel Doctrine and Clockwork.
4.  Set `DOCTRINE_LOGGER=LaravelDoctrine\ORM\Loggers\ClockworkLogger` in .env
4.  Opened tinker and poked around looking at config values to verify things worked.
5.  Opened the default site home page and Clockwork extension shows stats.
  
  
Is this a fresh install?  Do you have your services providers the normal order?  ( Framework => Package => 
Application ).  
  
  
If none of these work, can you give a stack trace?  ( Cut out any personal information in the file directories. )

**Comment by eigan** [comment]
This error usually appear when you have an error early in the boot process, like configuration or env files. 

You have an error in your post:
```diff
- 'logger' => LaravelDoctrine\ORM\Loggers\ClockworkLogger,
+ 'logger' => LaravelDoctrine\ORM\Loggers\ClockworkLogger::class,
```

But you have probably figured this stuff out by now. Close?
