### ISSUE TITLE
[PROPOSAL] Implement entity listner

### ISSUE THREAD

**Issue by vv12131415** [laravel-doctrine/orm#355]
Implement something that described here https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/events.html#entity-listeners-class and here https://symfony.com/doc/current/bundles/DoctrineBundle/entity-listeners.html

**Comment by garret-gunter** [comment]
You should be able to do this now.  Does adding it in annotations or other configurations not work?

**Comment by vv12131415** [comment]
> Does it adding it in annotations or other configurations not

Haven't tried
I will. Thank you!

**Comment by websmurf** [comment]
Just to add to this discussion, we are actively using listeners so I can confirm that this works already.

**Comment by vv12131415** [comment]
@websmurf thank you!

**Comment by mattkoch614** [comment]
Can someone post a code example?
