### ISSUE TITLE
[BUG] Add support for Laravel 5.8

### ISSUE THREAD

**Issue by diggersworld** [laravel-doctrine/orm#364]
Laravel 5.8 has been released.

`laravel-doctrine/orm 1.4.9 requires illuminate/view 5.5.*|5.6.*|5.7.* -> satisfiable by laravel/framework[v5.7.4]`

**Comment by CharifMakaoui** [comment]
#366 Her is the trick

**Comment by flythenimbus** [comment]
This is very urgent imo
