### ISSUE TITLE
[QUESTION] Dynamic database connection

### ISSUE THREAD

**Issue by kennaar** [laravel-doctrine/orm#365]
### Expected behaviour
I am trying to make an entity manager work with a dynamic database connection (multi-tenant multi-db setup). I have 2 database connections defined in `config/database.php`. One of these connections has empty configuration options because they are set at runtime depending on a url segment.

I am extending the DB connection in the register method of a service provider like this:
```
$this->app->get(DatabaseManager::class)->extend(
            'tenant',
            function ($config, $name) use ($manager) {
                $tenant = $manager->getTenant();

                if ($tenant !== null) {
                    $config['database'] = $tenant->getDatabaseName();
                    $config['username'] = $tenant->getDatabaseUsername();
                    $config['password'] = $tenant->getDatabasePassword();
                }

                return $this->app->get(ConnectionFactory::class)->make($config, $name);
            }
        );
```

The `$manager` object is a singleton that has it's tenant property set in a HTTP middleware. After this a reconnect on the DatabaseManager is called:

```
if ($this->manager->loadTenant($request->route('tenant'))) {
     $request->route()->forgetParameter('tenant');
     $this->databaseManager->connection('tenant')->reconnect();

     return $next($request);
}
```

At this point the connection has a valid configuration if I inspect it. The laravel-doctrine classes do not pick up on it however. I have tried calling `forgetInstance` on the service container of the ConnectionManager, EntityManagerFactory class. I tried calling `resetManager` on the IlluminateRegistry class in an `afterResolving` callback on laravel's DatabaseManager. I tried working with `DoctrineManager::extend` but nothing useful.

Of course I might have missed something somewhere, wrong combination of calls, ...
Some pointers are very much appreciated.

**Comment by xhs345** [comment]
Somewhere you also have to add the EntityManager to the ManagerRegistry. Typically vendor/laravel-doctrine/orm/src/IlluminateRegistry.php -> addManager() (I don't see that in your code right now).

In our case we create a unique EntityManager for each Tenant, but I suppose that is not required. On a request we load the correct connection details in a middleware (similar to how you are doing it), create the EM and then set that manager as the default.

**Comment by miloshke** [comment]
Was this solved? I'm trying to make a multi-tenant app where I change DB connection dynamically.

**Comment by kennaar** [comment]
@milosevicmilos Yes this issue was solved and actually wasn't a problem caused by the library. What are you having issues with?

**Comment by miloshke** [comment]
@knnnrd Thanks, I managed to figure out the issue. :) 
It's not a library thing, I just didn't use the proper steps to switch my DB connection.

**Comment by mohitgusain** [comment]
@milosevicmilos possible to share the steps? I'm facing the same issue where I need to switch the database connection based on a `request()->segment(1)`.

**Comment by AlexanderBich** [comment]
If anyone still struggling with that, here's the instruction of how to do dynamic connection with laravel-doctrine:

1. Update your connection config `database.connections.<CONNECTION_NAME>` with the desired credentials e.g.
```
config(['database.connections.mysql-dynamic' => [
    'driver'    => 'mysql',
    'host'      => 'mysql',
    'database'  => 'app',
    'username'  => 'app',
    'password'  => 'secret',
    'charset'   => 'utf8',
    'collation' => 'utf8_unicode_ci',
    'prefix'    => '',
    'strict'    => false,
]]);
```
2. Then add new manager to IlluminateRegistry:
```
$illuminateRegistry->addManager('mysql-dynamic', [
    'dev' => true,
    'meta' => 'annotations',
    'connection' => 'mysql-dynamic',
    'namespaces' => [],
    'paths' => [
        '/var/www/application/app/Entities',
    ],
    'repository' => 'Doctrine\\ORM\\EntityRepository',
    'proxies' => [
        'namespace' => false,
        'path' => '/var/www/application/storage/proxie
        'auto_generate' => false,
    ],
    'events' => [
        'listeners' => [],
        'subscribers' => [],
    ],
    'filters' => [],
    'mapping_types' => [],
]);
```

**Important note**: you should not have managers with that name (e.i. 'mysql-dynamic' in my case) in your doctrine config file, otherwise it will not update connection details.

3.  Use it via `$illuminateRegistry->getManager('mysql-dynamic')` or set that manager as default.

@mohitgusain

**Comment by eigan** [comment]
A different approach is to modify the env path with  `Application::useEnvironmentPath()` and point it a a tenant specific .env file. You can do this by extending `Application` and calling `useEnvironmentPath` from the constructor.

We have been doing a variant of this, combined with virtual hosts, custom storage path for each tenant, and a middleware to load global a global environment file. Have been working great for 5 years so far :) 

Closing as I think this issue have been solved by now.
