### ISSUE TITLE
[QUESTION] Make entity command

### ISSUE THREAD

**Issue by jonaaix** [laravel-doctrine/orm#377]
### Package version, Laravel version
laravel-doctring 1.4
lumen 5.8

### Expected behaviour
Is it possible to use this [doctrine cli command](https://symfony.com/doc/current/doctrine.html) `php bin/console make:entity` to generate new entities? I'm new to doctrine and it took me some time now to find out that it seems not to be mapped with laravel-doctrine.

**Comment by gmsantos** [comment]
this make:entity command is not from Doctrine, it is from [Symfony Maker](https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html) bundle.

**Comment by jonaaix** [comment]
In deed, that makes sense. Is there any chance to get it working without setting up a symfony project?
