### ISSUE TITLE
LaravelDoctrine is Recruting!!

### ISSUE THREAD

**Issue by josenicomaia** [laravel-doctrine/orm#396]
Good morning guys!! As you migth know, there isn't anyone currently active on the LD staff, soo to not let LD die I am recruiting people that would like to help the package maintenance. Let me know if anyone would like to contribute. I am collecting the names until next monday :smile:

Final list:

| User | State |
|--|--|
| eigan | _Intervied_ |
| heathn | _Intervied_ |
| szainmehdi | _Scheduled_ |
| Garret Gunter | _Scheduling_ |
| Max Carvalho | _Waiting Response_ |
| raygo | _Waiting Response_ |
| NicolasAnelli | _Waiting Response_ |
| bicatu | _Waiting Response_ |

**Comment by eigan** [comment]
Sign me up :)

We have used Laravel Doctrine for the last 3 years as an API for a Single Page App.

**Comment by nicolasanelli** [comment]
Hey, I'm interested

**Comment by bicatu** [comment]
I am interested as well.

**Comment by josenicomaia** [comment]
@NicolasAnelli could you join your slack? I would like to talk to you about LD.

**Comment by dextercampos** [comment]
Halo @josenicomaia, I'm interested as well ;)

**Comment by marcosdipaolo** [comment]
This makes me happy

**Comment by kaamoss** [comment]
I'm interested as well.

**Comment by chewbakartik** [comment]
Hey @josenicomaia, I'm interested in increasing my contributions as well and joining the team.
