### ISSUE TITLE
[QUESTION] Laravel 6.0 support

### ISSUE THREAD

**Issue by zarunet** [laravel-doctrine/orm#397]
Laravel 6.0 is now out, but it looks like this package isn't usable with it yet.
Is a 6.0-compatible version planned?

**Comment by eigan** [comment]
Yes, see #394

**Comment by zarunet** [comment]
Thanks, didn't see that one! I'll wait for it to get merged, then.

**Comment by realshadow** [comment]
@eigan any news about possible merge?

**Comment by Shegl** [comment]
@eigan do you have any news about merge 6.0 support ?

**Comment by eigan** [comment]
We are waiting for a maintainer to review the PR and release a new version.

**Comment by SoftwareDesign-Solution** [comment]
I already use doctrine with Laravel 6 and it works without problems. I have copied the changes from the link https://github.com/laravel-doctrine/orm/pull/394/files/1ef3e774413ad57d33380168f61eb4b7ee9244b6

**Comment by patrickbrouwers** [comment]
Released as 1.5
