### ISSUE TITLE
[BUG] Resetting an entity manager doesn't reload the extensions

### ISSUE THREAD

**Issue by kennaar** [laravel-doctrine/orm#398]
### Expected behaviour
After resetting an entity manager, the same extensions should be loaded (listed in `doctrine.extensions`) for that manager.

### Actual behaviour
None of the extensions are loaded.

### Steps to reproduce the behaviour
- Enable any of the extensions listed in `doctrine.extensions`
- Call `ManagerRegistry::resetManager`
- Inspect the listeners for that particular entity manager

**Comment by TomHAnderson** [comment]
The ManagerRegistry is a Doctrine class.  But I don't think `resetManager` should be concerned with resetting extensions on an entity manager.  If this continues to be an issue, please open a new ticket and work > 3.0.0 may incorporate a bootstrap for an entity manager post-reset.
