### ISSUE TITLE
[PROPOSAL]  test on php 7.4

### ISSUE THREAD

**Issue by vv12131415** [laravel-doctrine/orm#404]
it will be good to be prepared to php7.4 and add tests on travis for php 7.4

**Comment by eigan** [comment]
Agree :+1: Added to Travis for both 1.4, 1.5.

1.4: https://travis-ci.org/laravel-doctrine/orm/builds/602512938
1.5: https://travis-ci.org/laravel-doctrine/orm/builds/602508406
