### ISSUE TITLE
[QUESTION] Register entity mappings outwith doctrine.php

### ISSUE THREAD

**Issue by craigbartholomew** [laravel-doctrine/orm#407]
I'm developing a package that uses laravel-doctrine/orm and laravel-doctrine/fluent.

Is it possible for my package to register entity mappings, rather than have the consumer of my package register them via config/doctrine.php?

**Comment by eigan** [comment]
Try this in your ServiceProvider `register` method:

```php
$manager = $this->app->make(\LaravelDoctrine\ORM\DoctrineManager::class);
$manager->addPaths("path/to/mappings");
```
