### ISSUE TITLE
[PROPOSAL] Allow decoration of the EventManager

### ISSUE THREAD

**Issue by software-artificer** [laravel-doctrine/orm#408]
Hello friends,

Working on the project where I would like to be able to decorate Doctrine's `EventManager`. Currently, we only allow to decorate `EntityManager` by specifying `decorate` configuration option and providing a class name for decoration. It will subsequently used in [EntityManagerFactory::decorateManager()](https://github.com/laravel-doctrine/orm/blob/1.5/src/EntityManagerFactory.php#L421-L427) method. 

This is all nice and dandy, but when the entity manager itself is created, the last parameter (responsible for supplying custom `EventManager` instance) is omitted, see [EntityManagerFactory::create()](https://github.com/laravel-doctrine/orm/blob/1.5/src/EntityManagerFactory.php#L134-L137) and the method it calls [EntityManager::create()](https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/EntityManager.php#L819).

Opening up this issue to see what your thoughts on this are. I have two approaches in mind and would like to see what you think on that as well.

1. Allow extra configuration option to supply the event manager and provide an ability to pull it out of the container and pass it over to the `EntityManager::create()`.
2. Provide an ability to decorate event manager, instantiate the default one and wrap it in the similar way that is already done for `EntityManager`.

I'm inclined towards 1, because it gives more flexibility, e.g. allows to inject extra dependencies and make things a bit more sophisticated. Disadvantage, however is that it's inconsistent with what already exists for entity manager and I'm fine if the decision would be towards decoration.

Looking forward for your feedback.
Cheers,
Garry

**Comment by eigan** [comment]
I would go for 1.

What do you think of an option on `doctrine.managers.[manager].event_manager`, where value would be a class name?

**Comment by software-artificer** [comment]
Proposed key name sounds reasonable to me, however I would make value to be a container key and it could either be just a class name or custom alias.

**Comment by eigan** [comment]
@filakhtov Added in fa459b647a691813e4a17cd243aa0a3a36a18567, will release later today for both 1.4 and 1.5.

**Comment by software-artificer** [comment]
Love it, thank you very much for such a quick turnaround! 10/10 will open an issue again 😍

**Comment by eigan** [comment]
Released in [1.4.12](https://github.com/laravel-doctrine/orm/releases/tag/1.4.12) _(L5)_ and [1.5.2](https://github.com/laravel-doctrine/orm/releases/tag/1.5.2) _(L6)_! Please try it out :)

**Comment by software-artificer** [comment]
@eigan tested with 1.4.12 and it works as expected. Thanks again, really appreciate your help here 🙇
