### ISSUE TITLE
[QUESTION] How to choose a different EnitityManager than Default?

### ISSUE THREAD

**Issue by ghost** [laravel-doctrine/orm#411]
Hello!

In your documentation you mentioned the following for injecting an EnitityManger into a Repository.

```
class AppServiceProvider
{
    public function register()
    {
        $this->app->bind(ScientistRepository::class, function($app) {
            // This is what Doctrine's EntityRepository needs in its constructor.
            return new DoctrineScientistRepository(
                $app['em'],
                $app['em']->getClassMetaData(Scientist::class)
            );
        });
    }
}
```

`$app('em')` is always the default EntityManager.

How can I access a different EntityManager at this point?

**Comment by FoxxMD** [comment]
You can find info about this in the [Entity Manager section.](https://www.laraveldoctrine.org/docs/1.4/orm/entity-manager) You will need to get an implementation of the `ManagerRegistry` interface. 

`$managerRegistry->getManager($managerName)` will return an `EntityManager` configured using the name of a manager you configured in `doctrine.php`

From the container like in your example: 
```php
$app['Doctrine\Common\Persistence\ManagerRegistry']->getManager('otherConnection');
```

or through dependency injection

```php
use Doctrine\Common\Persistence\ManagerRegistry;

class ExampleController extends Controller
{
    protected $em;

    public function __construct(ManagerRegistry $em)
    {
        $this->em = $em->getManager('otherConnection');
    }
}
```

**Comment by ghost** [comment]
Okay, but the point is: 
This is a different Object to the one $app('em') delivers:
Via EntityManagerInterface I can use createQueryBuilder() for some special SQL uses and with the one from ManagerRegistry I cannot...

And you get in struggle with initializing the parent EntityRepository class because the getClassMetadata()-Method is also missing in that object....

```
class RepoFwsBsnrFgVkzQuartal extends EntityRepository implements FwsBsnrFgVkzQuartalInterface
{
    private $em;
    private $qb;

    public function __construct(ManagerRegistry $em){
        $this->em = $em->getManager('am');
        parent::__construct($em,$em->getClassMetadata(FwsBsnrFgVkzQuartal::class));
        //$this->qb = $this->em->createQueryBuilder();
    }
```

**Comment by FoxxMD** [comment]
They are the same object. The phpdoc annotation for `getManager()` says the return type is the interface `ObjectManager` -- which `EntityManagerInterface` extends -- but the actual object returned is the singleton instance of `EntityManager`, which does implement `EntityManagerInterface`. Your code completion will tell you the object is missing those methods but it is not. 

I stepped through my code with both objects, look:
![image](https://user-images.githubusercontent.com/4663766/70331746-16d6b500-180e-11ea-897a-3c224993704f.png)

Disclaimer, I am using version 1.0.21 but I don't think its changed since then.

**Comment by ghost** [comment]
Hello again!

I use laravel-doctrine 1.5.* with Laravel 6.5

If I construct my class like this:
```php
public function __construct(ManagerRegistry $em){
        $this->em = $em->getManager('am');
        parent::__construct($em,$em->getClassMetadata(FwsBsnrFgVkzQuartal::class));
    }
```
I always get this:
![laravel_1](https://user-images.githubusercontent.com/58557343/70419987-f0f81d00-1a66-11ea-96f8-08bdde1c0253.jpg)

When I do:
```php
public function __construct(ManagerRegistry $em){
        $this->em = $em;
        parent::__construct($em,$em->getClassMetadata(FwsBsnrFgVkzQuartal::class));
    }
```
I'll get the same error displayed in the picture above.

When I do:
```php
public function __construct(EntityManagerInterface $em){
        $this->em = $em;
        parent::__construct($em,$em->getClassMetadata(FwsBsnrFgVkzQuartal::class));
    }
```
 
it  returns the result
![laravel_2](https://user-images.githubusercontent.com/58557343/70420271-afb43d00-1a67-11ea-9351-42eaceb47d1a.jpg)

In all cases I'll try to get result of this query:
```php
$query = $this->em->createQueryBuilder()->select('sum(a.'.FwsBsnrFgVkzQuartal::VK.') as '.FwsBsnrFgVkzQuartal::VK)
                        ->from(FwsBsnrFgVkzQuartal::class,'a')
                        ->where('a.'.FwsBsnrFgVkzQuartal::BSNR.'= :bsnr and a.'.FwsBsnrFgVkzQuartal::KV_QUARTAL.' = :kvq')
                        ->setParameters(['bsnr' => $bsnr,'kvq'=> '20161'])->getQuery()
            ;
```

If the EntityManager was always the same object, I had to have the result in all three cases (default EntityMangager ist set to 'am'). 

So the EntityManager returned from ManagerRegistry is not  implementing the EntityManagerInterface at all.

The one that works with ManagerRegistry is the following:
```php
public function __construct(ManagerRegistry $em){
        $this->em = $em->getManagerForClass(FwsBsnrFgVkzQuartal::class);
        parent::__construct($this->em,$this->em->getClassMetadata(FwsBsnrFgVkzQuartal::class));
    }
```
This delivers the result but also doesn't work with the EntityManagerInterface where the getManagerForClass() is missing.

This might be, in my conclusion, a bug, if both delivered  objects should be the same.

Addition: This works because of setting $this->em to the type of EntityManagerInterface

**Comment by eigan** [comment]
```diff
public function __construct(ManagerRegistry $em)
{
    $this->em = $em->getManager('am');
-    parent::__construct($em, $em->getClassMetadata(FwsBsnrFgVkzQuartal::class));    
+   parent::__construct($this->em, $this->em->getClassMetadata(FwsBsnrFgVkzQuartal::class));
}
```
_$em is still ManagerRegistry when you call to `parent::__construct`._

PS: Name your variable `$managerRegistry` and you would probably have avoided this.

**Comment by eigan** [comment]
Sorry, didnt read all the way through your comment before I postet mine. I see that your last code snippet actually uses the fixed call.

Just change your typehint to `EntityManager`?

**Comment by ghost** [comment]
Yes, this works too.

Thanks for your patience discussing this with me :)
