### ISSUE TITLE
[BUG] Incompatibility with doctrine/persistence 1.3.2

### ISSUE THREAD

**Issue by aguvillalba** [laravel-doctrine/orm#414]
Package version: 1.4.12, Laravel version: 5.8.35

When running composer update, got the following error:

Argument 1 passed to Doctrine\ORM\Configuration::setMetadataDriverImpl() must be an instance of Doctrine\Common\Persistence\Mapping\Driver\MappingDriver, instance of Doctrine\ORM\Mapping\Driver\XmlDriver given, called in /code/vendor/laravel-doctrine/orm/src/EntityManagerFactory.php on line 167

It might be related with this: https://github.com/doctrine/persistence/issues/81. I think laravel-doctrine/orm is not compatible with doctrine/persistence >= 1.3.*

Also when I try to run the command:

`php artisan doctrine:clear:metadata:cache`

I got the following error:
`Target [Doctrine\Persistence\ManagerRegistry] is not instantiable.`

**Comment by aguvillalba** [comment]
I had to add this block to my composer.json to avoid this issue:

```
"conflict": {
        "doctrine/persistence": "1.3.*"
},
```

**Comment by eigan** [comment]
Thank you for reporting this and suggesting a temporary fix! Looks like #415 is related.

**Comment by eigan** [comment]
1.4.13 and 1.5.3 released with fix. Solved by [marking](https://github.com/laravel-doctrine/orm/commit/4343a97142fdb35b522c2455ae97133fdcf32d0c) `doctrine/persistence` 1.3 as a conflict. This will prevent composer from upgrading to this version.

See #419. This was something we had to do because we still support PHP 7.0 and doctrine/orm 2.5 which do not even install the doctrine/persistence package - so we cannot just change the namespace in our package.

#415 will let us upgrade to doctrine/persistence 1.3, but only for 1.5 were we have dropped support for PHP 7.0.

**Comment by software-artificer** [comment]
> See #419. This was something we had to do because we still support PHP 7.0 and doctrine/orm 2.5 which do not even install the doctrine/persistence package - so we cannot just change the namespace in our package.

Hey @eigan, what is the reason to support PHP 7.0? Anything lower than 7.2 is [no longer supported by the PHP maintainers](https://www.php.net/supported-versions.php), not even receiving security updates and should not be run on production systems.

**Comment by aguvillalba** [comment]
Thank you @eigan !! So, it is supposed that I should remove the "conflict" section from my composer.json and rely on yours, right?

**Comment by eigan** [comment]
@filakhtov Laravel 5.5 (which we allow in 1.4) is an LTS release and is supported until August 2020. Releasing 1.4 with a new requirement for 7.1+ will prevent these users from getting potenial security related fixes in `laravel-doctrine/orm` (though they will continue to get security fixes for L5.5).

Sadly, there is no way for us to know if anyone actually uses PHP 7.0 as composer do not provide these stats. See https://github.com/composer/packagist/issues/1054.

Problem now is if doctrine/persistence releases a security fix only for 1.3 which also affects 1.2. Then we will have no choice but to drop support for 7.0.

@aguvillalba Thats right :)

**Comment by software-artificer** [comment]
@eigan Thanks for clarification. What do you think about doing:

```php
$this->app->alias(\Doctrine\Common\Persistence\ManagerRegistry::class, \Doctrine\Persistence\ManagerRegistry::class);
```

Rather than marking version conflict?

**Comment by eigan** [comment]
That might work! 

Will you be able to open a PR for this?

**Comment by software-artificer** [comment]
Done #421
