### ISSUE TITLE
[QUESTION] Composer failed install using "~1.5.*"

### ISSUE THREAD

**Issue by roes888** [laravel-doctrine/orm#424]
Please prefix your issue with one of the following: [BUG] [PROPOSAL] [QUESTION].

### Package version, Laravel version
version 6
### Expected behaviour
-
### Actual behaviour
[UnexpectedValueException]                                                  
Could not parse version constraint ~1.5.*: Invalid version string "~1.5.*"
### Steps to reproduce the behaviour
run: `composer require "laravel-doctrine/orm:~1.5.*"`

solved using command: `composer require "laravel-doctrine/orm:1.5.*"`.

**Comment by thascius-rumpelschnick** [comment]
Another way to write it could be `composer require "laravel-doctrine/orm:~1.5.0`. 
This would mean >= 1.5.0 < 1.6.0 - so basically the same. :o)

See: [https://getcomposer.org/doc/articles/versions.md#tilde-version-range-](url)
