### ISSUE TITLE
[QUESTION] Connection config for Oracle Cloud instance (Autonomous Database)

### ISSUE THREAD

**Issue by Stolz** [laravel-doctrine/orm#426]
I would like to know how to configure the package to connect to an Oracle Cloud instance ([Autonomous Database](https://docs.cloud.oracle.com/iaas/Content/Database/Tasks/adbconnecting.htm)) using **TCPS** protocol, either manually providing all the individual connection details (host, port, service name, ...) either providing a TNS name that has been preconfigured.

My Laravel application uses two packages to connect to **the same** Oracle DB:
- `laravel-doctrine/orm` is the main way to interact with the DB.
- `yajra/laravel-oci8` is used only for running the Laravel database migrations.

When I use a self hosted Oracle instance (Docker) I can use the same configuration for both packages and everything works well. For instance:

            'driver' => 'oracle',
            'service_name' => 'ORCLPDB1.localdomain',
            'service' => 'ORCLPDB1.localdomain',
            'host' => 'localhost',
            'port' => 1521,
            'database' => 'ORCLPDB1',
            'username' => 'myuser',
            'password' => 'secret',

When I use the Enterprise Edition instance of my company I also can use the same configuration for both packages and everything works well. For instance:

            'driver' => 'oracle',
            'service_name' => 'myapp.mycompany.net',
            'service' => 'myapp.mycompany.net',
            'host' => 'db.mycompany.net',
            'port' => 1521,
            'database' => 'myapp',
            'username' => 'myuser',
            'password' => 'secret',

But when I tried to do the same to connect to a Oracle Cloud Autonomous Database instance I get the error `ORA-12541: TNS: no listener`:

            'driver' => 'oracle',
            'service_name' => 'redacted_demo_tp.atp.oraclecloud.com',
            'service' => 'redacted_demo_tp.atp.oraclecloud.com',
            'host' => 'adb.ap-tokyo-1.oraclecloud.com',
            'port' => 1522,
            'database' => 'demo',
            'username' => 'myuser',
            'password' => 'secret',

Oracle Cloud provides a wallet file (a zip file) with all the necessary connection details (a TNS listener is installed and configured to use secure TCPS and client credentials). Followin the official instructions linked above, I have downloaded and unziped the file in my computer and configure the `TNS_ADMIN` env variable to point to where I have unziped the wallet.  I've also updated  `$TNS_ADMIN/sqlnet.ora` so DIRECTORY points to teh same directory than `TNS_ADMIN` variable. 

This make possible to connect to a database by simply using one of the TNS names listed in `$TNS_ADMIN/tnsnames.ora` files. 

In my case I want to connect using the 'demo_tp' TNS so I have update the config options and added `'tns' => 'demo_tp'`. After this change the parts of Laravel that use `yajra/laravel-oci8` can successfully connect to the cloud instance (Laravel migrations work and I can see from SQL Developer that the tables are being created) but as soon as I try to use Doctrine I get the error `ORA-12537: TNS:connection closed`. So it seems the connection is established by Doctrine but then closed, probably because it was not using **TCPS** protocol.

Is there any way to configure `laravel-doctrine/orm` so it uses a TNS name from `$TNS_ADMIN/tnsnames.ora` to retrieve all the connection details? If not, how should I configure it to provide the proper connection values for a TCPS connection?

For reference, here is the content of my `$TNS_ADMIN/tnsnames.ora` file

    demo_tp = (description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-tokyo-1.oraclecloud.com))(connect_data=(service_name=redacted_demo_tp.atp.oraclecloud.com))(security=(ssl_server_cert_dn="CN=adb.ap-tokyo-1.oraclecloud.com,OU=Oracle ADB TOKYO,O=Oracle Corporation,L=Redwood City,ST=California,C=US")))

**Comment by eigan** [comment]
You might want to look into the configuration options of Doctrine. I have never used Oracle so cant help you out, sorry :/
