### ISSUE TITLE
[BUG] php7.4 not working ManyToMany relation

### ISSUE THREAD

**Issue by Fabricio872** [laravel-doctrine/orm#431]
Please prefix your issue with one of the following: [BUG] [PROPOSAL] [QUESTION].

### Package version, Laravel version
laravel-doctrine/orm 1.5.4
Laravel Framework 6.13.1
### Expected behaviour
Entity got persisted 
### Actual behaviour
I got an error with addSomething() method in Entity only in php7.4
ErrorException
Trying to access array offset on value of type null 
on line:
vendor/doctrine/orm/lib/Doctrine/ORM/PersistentCollection.php:418
### Steps to reproduce the behaviour
Empty Laravel6 project with Doctrine 1.5.*
make 2 Entities with Many to Many relation 
error occurs when trying to persist fetched entry from one entity to another
my entities are included
[Entities.zip](https://github.com/laravel-doctrine/orm/files/4154325/Entities.zip)

**Comment by Fabricio872** [comment]
I have an update:
If one of two entity that you want to relate is selected in controller and then passed as parameter through listener and event the error appears. i have managed to fix it with reselecting it from db again. Am i doing something wrong or is it a bug?

**Comment by dpslwk** [comment]
when an entity is passed to a `Listener` via `Event` or to a `Job`, the `SerializesModels` trait is used to pack and unpack the entity, as the Event/Job goes through the queue
this means that when the entity is unpacked its not longer registers/linked/associated with the EntityManager

trying to persist the entity can often not work, and things like lazy loaded associations may also not get automatically resolved ( though I have not checked that myself)

two ways people work around this:

1. just pass entity ID's via the event and in the listener always reload/fetch form the EntityManager/Repository 

2. treat passed entities as read only until refetched, which is how I work
If I just need values from the entity I carry on as normal
if I need to change something and persist that entity, refetch it first from the appropriate Repository

**Comment by Fabricio872** [comment]
Thank you for fast respond the first solution is more suitable for my needs because i only need id for relationships.
