### ISSUE TITLE
[QUESTION] Oracle, NLS_DATE_FORMAT 

### ISSUE THREAD

**Issue by mattkoch614** [laravel-doctrine/orm#437]
I'm using Oracle and after setting up the drivers, I'm good to go. I am having one problem, and it's that a ``DATETIME`` column defined in the database is always coming back via the ORM with no time associated with it (``00:00:00.0``) 

Entity column
```php
//...
    /**
     * @ORM\Column(name="FL_LAB_TIME", type="datetime")
     */
    protected $lab_time;
//...
```

Value in Database: 2016-10-19 13:56:58

Value in PHP: 
```shell
^ Carbon\Carbon @1476849600 {#415
  date: 2016-10-19 00:00:00.0 America/New_York (-04:00)
}
```

I suspect I may need to set the NLS_DATE_FORMAT or something like that as indicated here: https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Event/Listeners/OracleSessionInit.php 

But I'm not sure how to implement the above using Laravel-Doctrine.

**Comment by eigan** [comment]
Have you tried adding `Doctrine\DBAL\Event\Listeners\OracleSessionInit::class` to your `managers.default.events.subscribers` config in `config/doctrine.php`?

**Comment by mattkoch614** [comment]
No I'll give that a shot!

**Comment by mattkoch614** [comment]
@eigan Is there any way to turn this off when PHPUnit tests are running?

**Comment by mattkoch614** [comment]
Nevermind, we got it working. Here's how: Some `phpunit` tests made use of a fake database connection, and it was still trying to use this listener for those tests (causing them to fail) - so we just put a conditional in the `config/doctrine.php` file for this:

```php
'events' => [
    'listeners'   => [],
    /*
    If the database connection is a real connection, use this subscriber. If not (e.g.
    when tests are running) then don't.
    */
    'subscribers' => env('WAREHOUSE_CONNECTION') == 'oracle' ? [Doctrine\DBAL\Event\Listeners\OracleSessionInit::class ] : []
],
```
