### ISSUE TITLE
[1.*] Add mongodb support

### ISSUE THREAD

**Issue by FoxxMD** [laravel-doctrine/orm#44]
Per [maxmatteo](https://laraveldoctrine.slack.com/archives/general/p1442835243000875) we should investigate the feasibility of adding support for mongodb. Doctrine already has [an ODM](https://doctrine-mongodb-odm.readthedocs.org/en/latest/reference/introduction.html) so it may be a simple process to tie it into Laravel Doctrine..

**Comment by askmatey** [comment]
:+1: 

https://github.com/doctrine/mongodb/releases/

**Comment by patrickbrouwers** [comment]
If someone uses MongoDB and can helps us, we could start a `laravel-doctrine/odm` package. 
I never use it, so can't say it's high on my todo-list to start working on this.

**Comment by bicatu** [comment]
I use it.  Is there any starting point - besides read the code?

**Comment by joshhornby** [comment]
@patrickbrouwers I am guessing this isn't being actively worked on?

**Comment by josenicomaia** [comment]
@joshhornby,

Actualy, @patrickbrouwers is overloaded taking care of ORM, Fluent and etc.
Because of this, we need someone that can get this mission.

**Comment by patrickbrouwers** [comment]
@joshhornby Nope, and I most likely won't be working on it in the near future, as it is something I won't be using. Other stuff has more prio for me.
If someone wants to be lead on this, let me know. I will help where needed, but don't have the time to learn als this odm stuff to properly implement and test it.

**Comment by patrickbrouwers** [comment]
As @jaschweder bumped this conversation in #175, it's good to update my status about ODM. I might be using it in the near future anyway. Like I said before if there's anybody who wants to help me out, please let me know. Can't promise any delivery dates, but might get there somewhere this year.

**Comment by jaswdr** [comment]
@patrickbrouwers I'm interessed to help on ODM, you has started some repository on Github ? call me if soo :)

**Comment by patrickbrouwers** [comment]
@jaschweder Thanks for the offer. No, I haven't yet. Did you already join our Slack?

**Comment by jaswdr** [comment]
@patrickbrouwers currently no, can you pass the link ?

**Comment by josenicomaia** [comment]
http://slack.laraveldoctrine.org/

**Comment by lucavallin** [comment]
Up!
This could be a starting point: https://github.com/chefsplate/laravel-doctrine-odm

**Comment by dpslwk** [comment]
Please reopen in anyone is still interested in this, but its not something that myself or eigan are likely to implement.
