### ISSUE TITLE
[BUG] The identifier id is missing for a query

### ISSUE THREAD

**Issue by MP-okui** [laravel-doctrine/orm#449]
### Package version, Laravel version

laravel-doctrine/orm 1.6.0
laravel/framework 7.17.2
doctrine/orm 2.7.3

### Expected behaviour

find() returns null if no result.

### Actual behaviour

Throw Doctrine\ORM\ORMException

### Steps to reproduce the behaviour

```php
// App\Providers\RouteServiceProvider
    public function boot()
    {
        parent::boot();
        
        Route::bind('foo', function ($notFoundId) {
            $repository = EntityManager::getRepository(Foo::class);
            return $repository->find($notFoundId);
        });
    }
```

This is as expected.

```php
// App\Http\Controllers\FooController
    public function __invoke(\Illuminate\Http\Request $request)
    {
        $repository = EntityManager::getRepository(Foo::class);
        $foo = $repository->find($notFoundId);
        dd($foo); // null
    }
```

**Comment by eigan** [comment]
This is how Doctrine works afaik. You must pass a valid `$id` to `find()`. I would check if `$notFoundId` is null before calling `find()`. You might be able to use `findOneBy(['id' => $notFoundId])`, but I think this will execute a pointless query.

If you don't like this beviour then this issue belongs in https://github.com/doctrine/orm.

**Comment by MP-okui** [comment]
@eigan Thank you for your reply.

>  I would check if $notFoundId is null before calling find(). 

```$notFoundId``` is not null.
It is an ID that does not exist in the database.
But the results are different.

Are these results unrelated to **laravel-doctrine/orm**?

**Comment by eigan** [comment]
> Are these results unrelated to laravel-doctrine/orm?

Yes, I looks like it. You could do step-through debugging to find out if laravel-doctrine removes the value passed, but that seems very unlikely. 

It would be more helpful if you could provide the proper stacktrace though.

**Comment by MP-okui** [comment]
@eigan 

I checked the ```find()``` parameters.
```find()``` is called twice.

The first time is the expected parameter.
LaravelDoctrine\ORM\Middleware\SubstituteBindings::handle
vendor/laravel-doctrine/orm/src/Middleware/SubstituteBindings.php:48

The second time is null.
LaravelDoctrine\ORM\Middleware\SubstituteBindings::substituteImplicitBindings
vendor/laravel-doctrine/orm/src/Middleware/SubstituteBindings.php:78

### stacktrace
[2020-07-03 00:46:42] local.DEBUG: ID is '100'  
[2020-07-03 00:46:42] local.DEBUG: ID is NULL  
[2020-07-03 00:46:42] local.ERROR: The identifier id is missing for a query of App\Doctrine\Entities\Schedule {"exception":"[object] (Doctrine\\ORM\\ORMException(code: 0): The identifier id is missing for a query of App\\Doctrine\\Entities\\Schedule at /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php:315)
[stacktrace]
#0 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(421): Doctrine\\ORM\\ORMException::missingIdentifierField('App\\\\Doctrine\\\\En...', 'id')
#1 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(151): Doctrine\\ORM\\EntityManager->find('App\\\\Doctrine\\\\En...', Array, NULL, NULL)
#2 /var/www/html/app/Doctrine/Repositories/ScheduleRepository.php(17): Doctrine\\ORM\\EntityRepository->find(NULL, NULL, NULL)
#3 /var/www/html/vendor/laravel-doctrine/orm/src/Middleware/SubstituteBindings.php(78): App\\Doctrine\\Repositories\\ScheduleRepository->find(NULL)
#4 /var/www/html/vendor/laravel-doctrine/orm/src/Middleware/SubstituteBindings.php(50): LaravelDoctrine\\ORM\\Middleware\\SubstituteBindings->substituteImplicitBindings(Object(Illuminate\\Routing\\Route))
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): LaravelDoctrine\\ORM\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#30 /var/www/html/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#31 {main}
"}

**Comment by dpslwk** [comment]
in this code example

```
// App\Http\Controllers\FooController
    public function __invoke(\Illuminate\Http\Request $request)
    {
        $repository = EntityManager::getRepository(Foo::class);
        $foo = $repository->find($notFoundId);
        dd($foo); // null
    }
```

`$notFoundId` is never set anywhere?, you can not pass `null` to `->find()`

looks like your trying to use single action controllers, (`___invoke`)

in the method declaration you are asking laravel to inject in `Request` but not `notFoundId` 

need to see your what's in you route file to be sure but
either pull `notFoundid` form `$request`
```
 $foo = $repository->find($request->notFoundId);
```

or add it into the declaration
```
public function __invoke(\Illuminate\Http\Request $request, int $notFoundId)
```


also as mentioned by @eigan your likely also want to use `findOneBy` not `find` if you want to get `null` back for a non existent row

**Comment by eigan** [comment]
I think we should figure out why SubstituteBindings calls find with NULL. Are you able to figure out why the param is null @MP-okui?

**Comment by MP-okui** [comment]
@dpslwk Thank you.
My example was inadequate.
But the problem is **App\Providers\RouteServiceProvider**.

**Comment by MP-okui** [comment]
@eigan 
I couldn't understand why the parameter was null.

However, I think it's correct to throw an exception if ```find()``` return is null.

```php
    public function boot()
    {
        parent::boot();

        Route::bind('foo', function ($value) {
            $class = Foo::class;
            $repository = EntityManager::getRepository($class);
            $result = $repository->find($value);

            if (is_null($result)) {
                throw \Doctrine\ORM\EntityNotFoundException::fromClassNameAndIdentifier($class, ['id' => $value]);
            }

            return $result;
        });
    }
```

**Comment by dpslwk** [comment]
```
        Route::bind('foo', function ($notFoundId) {
            $repository = EntityManager::getRepository(Foo::class);
            return $repository->find($notFoundId);
        });
```
this is still an incomplete Route
you have listed $notFoundId as a parameter to the callback, but not included it in the URI definition
laravel won't like this, it won't be passing anything from the URI to the callback, and with no type hint it won't be injecting anything from the service container

if your URL should be 
`http://example.test/foo/100`
then the correct route definition is 
`Route::bind('foo/{notFoundId}', function ($notFoundId) {`
and adding in int type would not hurt
`Route::bind('foo/{notFoundId}', function (int $notFoundId) {`

if the URL should be 
`http://example.test/foo?notFoundId=100`
then you should ask laravel to inject the request
`Route::bind('foo', function (Request $request) {`
and then  pull it from `$request->notFoundId`

in both of the above SubstituteBindings should not be doing anything anyway since you have not type hinted a Class
Now if you would actually like `SubstituteBindings` to take care of loading the the Entity for you
then the route should look like
```
Route::bind('foo/{foo}', function (Foo $foo) {
    return $foo;
});
```

**Comment by dpslwk** [comment]
wait I miss read this
it's trying to setup an Explicit Binding?

I assume you are trying to resolve on something other than just the `id` column? even though thats what the example shows?
and your getting some interaction between you **Explicit** binding and the **Implicit** binding of `laravel-doctrine/orm/src/Middleware/SubstituteBindings.php`
If you are just trying to resolve on the `id` column then why not just use the Implicit Bindings?


can you post more detailed/corrected code for your 
`App\Providers\RouteServiceProvider`
`App\Http\Controllers\FooController`
and 
`routes/web.php`


#443 might solve trying to use `Route::bind` sine you could specify the columns in the route/web.php definition of the uri

**Comment by MP-okui** [comment]
@dpslwk 
My route is

```php
Route::resource('foo', 'FooController')->only([
    'show',
]);
```

The parameters are being passed correctly.
/foo/{foo}

And I understand that ```Route::bind()``` is usually not needed.

My purpose is to customize the query.
So I used ```Route::bind()``` and solved it.
The cause of the error was to return null there.

**Comment by dpslwk** [comment]
ah so your `Route::bind` returned `null` and then Laravel tried to resolve it via the Implicit bindings, but the parameter had been modified so `SubstituteBindings` was passed your `null`

**Comment by MP-okui** [comment]
@dpslwk 
I think so.
This was not a bug.

Thank you for your time.
