### ISSUE TITLE
[BUG][QUESTION] failed job queue

### ISSUE THREAD

**Issue by nsn0x01** [laravel-doctrine/orm#452]
HI,

I'm using lumen last version and I have configured the failed job configuration on the queue:

        'failed' => [
            'driver' => env('QUEUE_FAILED_DRIVER', 'database'),
            'database' => env('DB_CONNECTION', 'mysql'),
            'table' => 'failed_jobs',
        ],

Nothing is logged, the table was created correctly and I tried also to enable the FailedJobsServiceProvider.

Any suggests?

**Comment by eigan** [comment]
This you figure out what the problem was? @nsn0x01

**Comment by ukenpachi** [comment]
the database will be your `connection `name instead of the database type e.g. mysql. Your `connection ` name is in `config/Doctrine.php` in the `managers->default` array =
