### ISSUE TITLE
[PROPOSAL] Doctrine 2.8 support

### ISSUE THREAD

**Issue by aftabnaveed** [laravel-doctrine/orm#466]
### Package version, Laravel version
Laravel 8.0

Doctrine 2.8 has just been released https://github.com/doctrine/orm/releases/tag/2.8.1 which adds support for PHP 8,  this means we no longer need to use the doctype annotations and can use PHP 8 Attributes to add meta to entities.   Are there any plans of adding support for it yet?  If not, then it would be great to start a conversation about it.

**Comment by eigan** [comment]
There is #462 for PHP 8. Will help get a PR merged for attributes support.

**Comment by aftabnaveed** [comment]
Looks like the Doctrine Team won't support PHP 8 attributes in this version.  I will close this issue.
