### ISSUE TITLE
[PRPOSAL] Php 8 deprecation bug

### ISSUE THREAD

**Issue by michaeldnelson** [laravel-doctrine/orm#467]
Marking as proposal because php 8 is not supported.

### Package version, Laravel version
1.72, 8

### Expected behaviour
Works with php 8

### Actual behaviour

Fails with deprecation error. Required parameter $manager follows optional parameter $settings

protected function registerListeners(array $settings = [], EntityManagerInterface $manager)

### Steps to reproduce the behaviour

Install php 8

**Comment by michaeldnelson** [comment]
> Please prefix your issue with one of the following: [BUG] [PROPOSAL] [QUESTION].

k

**Comment by eigan** [comment]
There is some work on this here: #462. There is probably more work needed on the other laravel-doctrine packages too.

**Comment by eigan** [comment]
So all pull requests with PHP 8 have been merged now. Please try it out and report bugs :)
