### ISSUE TITLE
[BUG] Documentation site is down

### ISSUE THREAD

**Issue by andrzej-tracz** [laravel-doctrine/orm#468]
As per issue title, website http://laraveldoctrine.org/ gives me `403 Forbidden` error. Not sure if this is temporary.

### Steps to reproduce the behaviour

Visit: http://laraveldoctrine.org/

**Comment by FoxxMD** [comment]
@josenicomaia @patrickbrouwers

**Comment by patrickbrouwers** [comment]
@josenicomaia will have to check, I'm not really part of the project anymore, nor do I have access to that server. If he doesn't see this message, try messaging him on the Doctrine Slack

**Comment by lamkimphu258** [comment]
Sadly, until now, the documentation site is still down. I need to use google cached to read the documentation :(. Hope you will fix it soon.

**Comment by eigan** [comment]
Note that the contents of the webpage is hosted here: https://github.com/laravel-doctrine/docs

**Comment by josenicomaia** [comment]
Ops., I will check the problem. I wasn't reading the mails, sorry for the delay.

**Comment by josenicomaia** [comment]
It's online!!

**Comment by levacic** [comment]
@josenicomaia It's still not fine - opening any page other than the home page shows a Whoops stack trace: http://laraveldoctrine.org/docs/1.4/orm

![Screenshot from 2020-12-20 01-17-43](https://user-images.githubusercontent.com/1636354/102702267-4a418180-4261-11eb-8c83-dca49f91b2f2.png)

**Comment by josenicomaia** [comment]
@levacic yeah, I am debugging it

**Comment by josenicomaia** [comment]
It's fixed. Can you check it again?

**Comment by levacic** [comment]
Seems it works all right now, thanks!
