### ISSUE TITLE
[QUESTION] PHP 8 support

### ISSUE THREAD

**Issue by martio** [laravel-doctrine/orm#469]
Package work properly on PHP 8?

**Comment by eigan** [comment]
See #467

**Comment by Jurigag** [comment]
I runned a test locally on my linux docker container and it seems to be okay. As i see it's failing on a mac and/or php 8.0.0.

**Comment by Jurigag** [comment]
https://github.com/laravel-doctrine/orm/pull/473

Added PR where i fix tests.

**Comment by eigan** [comment]
We have released a new version now with PHP 8 support. Please try it out :)
