### ISSUE TITLE
Listeners / Subscribers should resolve through the DI Container

### ISSUE THREAD

**Issue by maxbrokman** [laravel-doctrine/orm#47]
At the moment adding listeners calls something [like this](https://github.com/laravel-doctrine/orm/blob/980d219ac089faac2a473edde0d379700b1bc471/src/EntityManagerFactory.php#L135)

```php
if (!class_exists($listener, false)) {
     throw new InvalidArgumentException("Listener {$listener} does not exist");
}

$manager->getEventManager()->addEventListener($event, new $listener);
```

This doesn't resolve listeners from the Container, so they won't have any dependencies injected etc.

Obviously switching this to work through the container is probably just as simple as:

```php
try {
     $resolvedListener = $this->container->make($listener);
} catch (ReflectionException $e) {
     throw new InvalidArgumentException("Listener {$listener} could not be resolved: {$e->getMessage()}");
}

$manager->getEventManager()->addEventListener($event, $resolvedListener);
```

But I'm worried that this might be a problem given how the DoctrineServiceProvider works.

The provider does most of its work in `register()` and this includes adding these listeners.

[`DoctrineServiceProvider::registerManagerRegistry()`](https://github.com/laravel-doctrine/orm/blob/980d219ac089faac2a473edde0d379700b1bc471/src/DoctrineServiceProvider.php#L108) sets up the registry to call `IlluminateRegistry::addManager()`, which will trigger the adding of listeners.

Because we then make use of the registered Registry in [`DoctrineServiceProvider::registerEntityManager`](https://github.com/laravel-doctrine/orm/blob/980d219ac089faac2a473edde0d379700b1bc471/src/DoctrineServiceProvider.php#L94) this code will get run during the Provider's register phase. 

If we make a change as above to resolve listeners from the container this means that we may call `make()` before a dependency has been registered, which would break the application. 

To my mind listeners being resolved from the container is what would be expected from a Laravel package, but this may require changes to how the service provider works?

I've noticed that `DoctrineServiceProvider` is deferred, does this mitigate this issue?

**Comment by maxbrokman** [comment]
Actually I may be wrong, this might not all trigger off until you call `app()->make('em')` for the first time, in which case it's a non issue!

Just want to get some input on if this is going to break anything basically.

**Comment by patrickbrouwers** [comment]
Both `ManagerRegistry` and `em` are singletons and the contents of the closure will only be executed when it's called for the first time.
So I don't for see any problems in switching to dependency injections.

Could you add for failing `container->make()` as well (expected exception), thanks!
