### ISSUE TITLE
[QUESTION]Laravel 8 Factories

### ISSUE THREAD

**Issue by k0ka** [laravel-doctrine/orm#470]
Laravel 8 introduced a [new factory system](https://laravel.com/docs/8.x/database-testing#defining-model-factories). Will laravel-doctrine support it?

**Comment by eigan** [comment]
I'm not using the current factory system, so I'm very unlikely to be the one adding support for these.

**Comment by superbiche** [comment]
~~We'll be trying to move our project from using seeded data to factories so we will try to work on something similar~~ 

EDIT: 
@k0ka 
http://laraveldoctrine.org/docs/1.8/orm/testing

**Comment by k0ka** [comment]
That's an old version of Laravel factories. They have rewritten it in the 8th version.

**Comment by TomHAnderson** [comment]
Closing; please open a new ticket if this is still a concern.
