### ISSUE TITLE
[QUESTION] Laravel 7 & 8 Support

### ISSUE THREAD

**Issue by soulcodex** [laravel-doctrine/orm#477]
Hi friend,

Do you have plans to support correctly without problems or trickys with composer the laravel current versions like 7 or 8 version?

I have really doubts to implement this package for a biggest project with 5 - 6 members without biggest bugs

Thanks and regards

**Comment by eigan** [comment]
Hi @soulcodex! 

Currently this package is maintained by the community which means that you should not expect that any new features in Laravel will be ported to support Doctrine implementation. What usually happens is that someone in the community will need it and implement it. 

We are lacking some test coverage and we do not use any static analyzers. This is a bit problematic. The recent bug reports regarding the latest versions (including PHP 8) could have been avoided.

That said, we do support Laravel 7 and 8, including PHP 8. Take a look at the requirements in the [composer.json](https://github.com/laravel-doctrine/orm/blob/1.7/composer.json). Please let me know if you have any problems upgrading/installing. 

_My role in this project is to review pull requests and releasing new versions._
