### ISSUE TITLE
[QUESTION] - How to change quoting strategy ?

### ISSUE THREAD

**Issue by smarcet** [laravel-doctrine/orm#481]
hello, i do see how to change the naming strategy [https://github.com/laravel-doctrine/orm/issues/120] but i do need to change quoting strategy for mysql 8 reserved words.
using method

$configuration->setQuoteStrategy

as doctrine doc said https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/basic-mapping.html#quoting-reserved-words using a custom QuoteStrategy.

do i need to submit a pull request ? regards

**Comment by eigan** [comment]
Pull request would be great 🙂

**Comment by smarcet** [comment]
ok done, https://github.com/laravel-doctrine/orm/pull/485 please review regards

**Comment by eigan** [comment]
Released as part of 1.6.4 and 1.7.5. Thanks! 🙂
