### ISSUE TITLE
[BUG] Problem with dependencies while installing orm 1.7.* in laravel 8.5

### ISSUE THREAD

**Issue by lsrzj** [laravel-doctrine/orm#486]
### Package version, Laravel version
Laravel 8.5.*

### Expected behaviour
Install laravel-doctrine without problems

### Actual behaviour
composer require "laravel-doctrine/orm:1.7.*" 
./composer.json has been updated
Running composer update laravel-doctrine/orm
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/orm[v2.7.0, ..., v2.7.2] require doctrine/common ^2.11 -> satisfiable by doctrine/common[v2.11.0, ..., 2.13.x-dev].
    - laravel-doctrine/orm[1.7.1, ..., 1.7.x-dev] require doctrine/inflector ^1.4 -> found doctrine/inflector[1.4.0, ..., 1.4.x-dev] but the package is fixed to 2.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - doctrine/common[v2.11.0, ..., 2.13.x-dev] require doctrine/inflector ^1.0 -> found doctrine/inflector[v1.0, ..., 1.4.x-dev] but the package is fixed to 2.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - doctrine/orm[v2.7.3, ..., 2.7.x-dev] require doctrine/inflector ^1.0 -> found doctrine/inflector[v1.0, ..., 1.4.x-dev] but the package is fixed to 2.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - doctrine/orm[v2.6.0, ..., 2.6.x-dev] require symfony/console ~3.0|~4.0 -> found symfony/console[v3.0.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev] but the package is fixed to v5.2.6 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires laravel-doctrine/orm 1.7.* -> satisfiable by laravel-doctrine/orm[1.7.0, ..., 1.7.x-dev].
    - Conclusion: don't install doctrine/persistence[2.0.1] | install doctrine/persistence[1.3.8] (conflict analysis result)
    - Conclusion: don't install doctrine/persistence[2.0.0] | install doctrine/persistence[1.3.8] (conflict analysis result)
    - Conclusion: don't install doctrine/persistence[2.2.x-dev] | install doctrine/persistence[1.3.8] (conflict analysis result)
    - Conclusion: don't install doctrine/persistence[2.1.x-dev] | install doctrine/persistence[1.3.8] (conflict analysis result)
    - Conclusion: don't install doctrine/persistence 1.3.8 (conflict analysis result)
    - laravel-doctrine/orm 1.7.0 requires doctrine/orm ^2.6|^2.7 -> satisfiable by doctrine/orm[v2.6.0, ..., 2.9.x-dev].
    - Conclusion: don't install doctrine/orm 2.9.x-dev (conflict analysis result)
    - Conclusion: don't install doctrine/orm 2.8.0 (conflict analysis result)
    - Conclusion: don't install doctrine/orm 2.8.1 (conflict analysis result)
    - Conclusion: don't install doctrine/orm 2.8.2 (conflict analysis result)
    - laravel-doctrine/orm 1.7.0 requires doctrine/persistence ^1.3 -> satisfiable by doctrine/persistence[1.3.0, ..., 1.4.x-dev].
    - You can only install one version of a package, so only one of these can be installed: doctrine/persistence[v1.0.0, ..., 1.4.x-dev, 2.0.0, ..., 2.2.x-dev].
    - doctrine/orm 2.8.x-dev requires doctrine/persistence ^2.0 -> satisfiable by doctrine/persistence[2.0.0, ..., 2.2.x-dev].
    - Conclusion: don't install doctrine/persistence[2.1.0] | install doctrine/persistence[1.3.8] (conflict analysis result)

### Steps to reproduce the behaviour
Install laravel 8.5.* and try to install doctrine/orm:1.7.*

**Comment by eigan** [comment]
Try this
```
composer require laravel-doctrine/orm doctrine/inflector:"^1.4|^2.0"
```

Laravel allows both 1.4 and 2.0 of doctrine/inflector, but composer locks to 2.0 after installing just laravel. The above command should clarify that we want to allow 1.4 of doctrine/inflector.


_Edit: Updated to include `^` for doctrine/inflector._

**Comment by lsrzj** [comment]
This solved the issue and I could install normally
