### ISSUE TITLE
[BUG] Error: InfoCommand::$signature must be string

### ISSUE THREAD

**Issue by Finnesko7** [laravel-doctrine/orm#487]
### Package version , Laravel version
Package version: 1.5
Laravel/lumen-framework: 6.3.5
PHP: 7.4

### Steps to reproduce the behaviour
Execute any php artisan command like : php artisan list

**Comment by dpslwk** [comment]
I've had no issue with this

Package version: 1.5.10
Laravel: 6.20.19
PHP: 7.4.14

on both Mac and Debian

it is a multi line string, but there are several other commands just its the laravel/framework that are written the same way

Can you give more info? OS version?

**Comment by eigan** [comment]
It is a string? https://github.com/laravel-doctrine/orm/blob/1.5/src/Console/InfoCommand.php

Could you provide a stack trace?

**Comment by MoamenAbdelwahed** [comment]
I have the same issue

PHP: 7.4
Lumen: 6
laravel-doctrine/orm: 1.5
@eigan

**Comment by eigan** [comment]
@MoamenAbdelwahed A stack trace would be great :)
