### ISSUE TITLE
[Question] DBAL access

### ISSUE THREAD

**Issue by designermonkey** [laravel-doctrine/orm#488]
Is there a way to easily get access to the Doctrine DBAL within this extension? We don't use ORM within our project, but would prefer the Doctrine DBAL instead of that which Laravel provides.

**Comment by FoxxMD** [comment]
Yes, the [DoctrineManager](http://laraveldoctrine.org/docs/1.4/orm/doctrine-manager) provides access to the DBAL Connection object. All you'd need to do is setup a barebones default [manager](http://laraveldoctrine.org/docs/1.4/orm/config-file) in the config which would give you access to a [Facade or IOC injected manager](https://laravel.com/docs/8.x/facades) (`ManagerRegistry`) that you could get the connection from:

```php
use RegistryManager;

class MyClass {
//...
 function myFunc() {
  $dbalConnection = RegistryManager::getManager()->getConnection();
  }
}
```

**Comment by designermonkey** [comment]
Thank you for your help, I'll give that a go as soon as I can.
