### ISSUE TITLE
[QUESTION] 2.0 version support

### ISSUE THREAD

**Issue by akalongman** [laravel-doctrine/orm#492]
The **2.0** version is 41 commits behind **1.7**

What does it mean? **2.0** is not supported? 

CI is failing as well for **2.0**

**Comment by eigan** [comment]
There was a point where we thought that supporting PHP 8 required some breaking changes so the 2.0 branch was introduced. We ended up solving the problems in a way that ended up not causing any breaking changes so the 2.0 branch was just left behind. It should be deleted.
