### ISSUE TITLE
[PROPOSAL] Add attributes metadata support

### ISSUE THREAD

**Issue by dretsa** [laravel-doctrine/orm#494]
Please prefix your issue with one of the following: [BUG] [PROPOSAL] [QUESTION].

### Package version, Laravel version
doctrine/orm:2.9.1
laravel-doctrine/orm: 1.7.7

### Expected behaviour
Users must be able to specify the new attributes driver when using PHP 8+

### Actual behaviour
There is no metadata driver in the package.

### Steps to reproduce the behaviour
1. Create new Laravel project
2. Install laravel-doctrine/orm
3. Try to use #[ORM\Entity] and #[ORM\Table]
4. You get an error `Class "....." is not a valid entity or mapped super class.`

**Comment by eigan** [comment]
Your PR have been released with 1.5.13, 1.6.7 and 1.7.9. Please try it out. Thanks 👍🏻

**Comment by jurgenbosch** [comment]
@eigan This does not seem to work with the migrations:diff command. Are you aware of that?
