### ISSUE TITLE
[PROPOSAL] It would be nice to see Doctrine queries in Laravel Telescope

### ISSUE THREAD

**Issue by rosamarsky** [laravel-doctrine/orm#500]
### Expected behaviour
Queries are displaying  on the **Queries** page

### Actual behaviour
![image](https://user-images.githubusercontent.com/15215861/133284744-efde59e0-0eab-4101-a167-c4cc39cd6999.png)

**Comment by eigan** [comment]
You might be able to build this by creating a logger. 

See https://github.com/laravel-doctrine/orm/blob/9dc7790f86c2013fc43a733bde50efc0ec17881e/src/Loggers/LaravelDebugbarLogger.php for inspiration, and https://github.com/laravel/telescope/blob/4.x/src/Watchers/QueryWatcher.php for how to push to Telescope. Looks like `Telescope::recordQuery` is the way. 

Register your logger in config/doctrine.php at the `logger` key (which should use the `DOCTRINE_LOGGER` environment variable.

**Comment by rosamarsky** [comment]
> You might be able to build this by creating a logger.
> 
> See https://github.com/laravel-doctrine/orm/blob/9dc7790f86c2013fc43a733bde50efc0ec17881e/src/Loggers/LaravelDebugbarLogger.php for inspiration, and https://github.com/laravel/telescope/blob/4.x/src/Watchers/QueryWatcher.php for how to push to Telescope. Looks like `Telescope::recordQuery` is the way.
> 
> Register your logger in config/doctrine.php at the `logger` key (which should use the `DOCTRINE_LOGGER` environment variable.

Thanks, I think it will help me a lot :)

**Comment by eigan** [comment]
@rosamarsky Relevant PR opened recently: #501. This might make the telescope QueryWatcher work as expected.

**Comment by TomHAnderson** [comment]
Closing; expired.
