### ISSUE TITLE
[QUESTION] ORM version

### ISSUE THREAD

**Issue by userbig** [laravel-doctrine/orm#503]
https://github.com/laravel-doctrine/orm/blob/9dc7790f86c2013fc43a733bde50efc0ec17881e/composer.json#L21

Can the Doctrine/ORM version be bumbed? Because right now it cant be installed on PHP 8.

```
  - doctrine/orm[v2.6.0, ..., 2.7.x-dev] require php ^7.1 -> your php version (8.0.10) does not satisfy that requirement.

```

**Comment by userbig** [comment]
nevermind. removing the whole ORM set and installing it again fixed the issue.

But I wondering why `update` or `upgrade` was not helping

**Comment by eigan** [comment]
Great. Remember to use laravel-doctrine/orm:1.7 and you _should_ be fine :)
