### ISSUE TITLE
When you are releasing laravel-doctrine/orm:2.9 ?

### ISSUE THREAD

**Issue by rehman20281** [laravel-doctrine/orm#507]
@stephandesouza @eigan @jwpage  When you are releasing laravel-doctrine/orm:2.9 ?
is compatible doctrine/orm :2.9 or 10 version with laravel/doctrine-orm 
Can tell me someone ?

**Comment by eigan** [comment]
Hi @rehman20281. What issues are you encountering when trying to install doctrine/orm 2.9?

See composer.json for our constraints as of now: https://github.com/laravel-doctrine/orm/blob/1.7/composer.json

**Comment by rehman20281** [comment]
@eigan I didnot try for installation , i was finding laravel-doctrine/orm which support doctrine/orm:2.9 by default , unfortunately i can't find yet. i was asking that will laravel-doctrine/orm version upgrade with 2.9 ?

**Comment by eigan** [comment]
Please try. It should work with doctrine/orm 2.9. Let me know if you encounter any problems.

**Comment by rehman20281** [comment]
@eigan Okay Thanks
