### ISSUE TITLE
is doctrine/orm supports php 8.1?

### ISSUE THREAD

**Issue by rehman20281** [laravel-doctrine/orm#509]
@eigan @jwpage doctrine/orm:2.7 to 2.9 these versions are supporting php 8.1 ???

**Comment by eigan** [comment]
Haven't tried. You go ahead :) 

I should maybe set up tests for it.

**Comment by eigan** [comment]
And please don't ping other contributors than me next time :)

**Comment by rehman20281** [comment]
your name is famous in comment that's why your name comes first and i send comment :)

**Comment by rehman20281** [comment]
@eigan ok
