### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by elceka** [laravel-doctrine/orm#52]
Hi, please, how can i testing ORM library with PHP unit? I have environment configuration in phpunit.xml file for SQLITE memory database, but ORM library stay use default MYSQL configuration from database.php configuration file and mixing it with SQLITE testing configuration.

I get this error from PHPUnit test environment (SQLSTATE[HY000] [1049] Unknown database ':memory:'):
```
Failed asserting that exception of type "Doctrine\DBAL\Exception\ConnectionException" matches expected exception "\InvalidArgumentException". Message was: "An exception occured in driver: SQLSTATE[HY000] [1049] Unknown database ':memory:'" at
#0 /xxx\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /xxx/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(47): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException))
#2 /xxx/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'user', 'password', Array)
#3 /xxx/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1166): Doctrine\DBAL\Connection->connect()
#4 /xxx/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(230): Doctrine\DBAL\Connection->beginTransaction()
#5 /xxx/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php(85): Doctrine\ORM\EntityManager->transactional(Object(Closure))
#6 /xxx/tests/phpunit/Application/Protocol/RetrieveProtocolsTest.php(69): Doctrine\Common\DataFixtures\Executor\ORMExecutor->execute(Array)
#7 [internal function]: yyy\Tests\Application\Protocol\RetrieveProtocolsTest->testRetrieveProtocolsInvalidArgumentException()
#8 /xxx/vendor/phpunit/phpunit/src/Framework/TestCase.php(881): ReflectionMethod->invokeArgs(Object(yyy\Tests\Application\Protocol\RetrieveProtocolsTest), Array)
#9 /xxx/vendor/phpunit/phpunit/src/Framework/TestCase.php(746): PHPUnit_Framework_TestCase->runTest()
#10 /xxx/vendor/phpunit/phpunit/src/Framework/TestResult.php(601): PHPUnit_Framework_TestCase->runBare()
#11 /xxx/vendor/phpunit/phpunit/src/Framework/TestCase.php(702): PHPUnit_Framework_TestResult->run(Object(yyy\Tests\Application\Protocol\RetrieveProtocolsTest))
#12 /xxx/vendor/phpunit/phpunit/src/Framework/TestSuite.php(735): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#13 /xxx/vendor/phpunit/phpunit/src/Framework/TestSuite.php(735): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#14 /xxx/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(432): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#15 /xxx/vendor/phpunit/phpunit/src/TextUI/Command.php(148): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#16 /xxx/vendor/phpunit/phpunit/src/TextUI/Command.php(100): PHPUnit_TextUI_Command->run(Array, true)
#17 /xxx/vendor/phpunit/phpunit/phpunit(47): PHPUnit_TextUI_Command::main()
#18 {main}.
```

DB environment configuration from phpunit.xml file:
```xml
<env name="APP_ENV" value="testing"/>
<env name="APP_DEBUG" value="true"/>
<env name="DB_CONNECTION" value="sqlite"/>
<env name="DB_DRIVER" value="sqlite"/>
<env name="DB_DATABASE" value=":memory:"/>
<env name="DOCTRINE_METADATA" value="annotations"/>
<env name="DOCTRINE_PROXY_AUTOGENERATE" value="true"/>
```

Configuration for sqlite connection from database.php file:
```php
'default' => env('DB_CONNECTION', 'mysql'),
'connections' => array(
    'mysql' => array(
        ...
    ),
    'sqlite' => array(
        'driver' => env('DB_DRIVER', 'sqlite'),
        'database'  => env('DB_DATABASE'),
        'prefix'   => ''
    )
)
...
```

DB default manager configuration from doctrine.php configuration file:
```php
'managers' => [
    'default' => [
        'dev'        => env('APP_DEBUG'),
        'meta'       => env('DOCTRINE_METADATA', 'annotations'),
        'connection' => env('DB_CONNECTION'),
...
```

Thank You.

**Comment by patrickbrouwers** [comment]
Hello @elceka 

First thing you should consider is, if it's really necessary to have the database connection during your tests. The great thing about Doctrine is that it's super easy to Mock EntityManager and Repositories calls, because the Entity has no database logic. If the EntityManager returns any result, that's Doctrine's responsibility to test. 

If you're doing end-to-end/acceptance testing PHPUnit is maybe not the right tool for it and you might need to consider using a tool like Behat which is designed for it.

Other than my opinion about unit testing, the env() overruling is something that should work. So will have to further investigate this.

**Comment by FoxxMD** [comment]
@elceka 

In `doctrine.php` just use a ternary operator on the `connection` property and test against `APP_ENV` to decide which connection to use.

```
    'managers' => [
        'default' => [
            'meta' => 'yaml',
            'connection' => env('APP_ENV') == 'testing' ? 'sqlite' : 'mysql',
            'paths' => [
                base_path('app/Models/mappings')
            ]
            ,
            'repository' => 'Doctrine\ORM\EntityRepository',
            'proxies' => [
                'namespace' => false,
                'path' => storage_path('proxies'),
                'auto_generate' => false
            ],
            'events' => [
                'listeners' => [],
                'subscribers' => []
            ],
            'filters' => []
        ],
```

This is what I do and works for me

**Comment by ghindle** [comment]
I can also confirm that the environment variable override isn't working.

**Comment by guiwoda** [comment]
@elceka @ghindle I'm not able to reproduce what you're saying. Are you extending Laravel's `TestCase` class? This is **required** for env configuration to load properly.

**Comment by patrickbrouwers** [comment]
Can you let us know if extending `TestCase` fixes the problem while using the latest release of this package?

I couldn't reproduce your error while using your settings, except the fact that I might use `TestCase` instead of `PHPUnit_Framework_TestCase `

**Comment by ghindle** [comment]
I was definitely extending Laravel's `TestCase`. I will have another go this evening, I was trying to use SQLite in memory, which is appears you have made an update to in the meantime - hopefully this fixes my problems. I shall let you know.

**Comment by patrickbrouwers** [comment]
I improved the check on if a table is in memory, so it supports both `:memory` and `:memory:`.

But the strange things is that in your stacktrace I can see `PDOMySql`.

One thing I need to say about the `connection` setting, is that it needs the key (connection name) of `database.connections` config. (so not the driver name). But when using the default database.php, that will be the same as the driver name.

**Comment by ghindle** [comment]
That stack trace isn't from my code so I can't comment about the PDOMySql but my system was trying to connect to MySQL too, even if I removed to configuration entry. 

I'm pretty sure I was using the key of the connection name, but I will have to double check.

**Comment by patrickbrouwers** [comment]
Sorry, was confusing two people, haha :p

**Comment by guiwoda** [comment]
@elceka can you review this with the new comments we made? please do, as without more feedback this cannot be reproduced and should be closed.

**Comment by ghindle** [comment]
@guiwoda @patrickbrouwers Having tested this again since updating the environment variable is now being tracked correctly. For reference if anyone comes across this issue at a later date:

`database.php`

``` php
    'default' =>  env('DB_CONNECTION', 'mysql'),
    'connections' => [

        'mysql' => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST', 'localhost'),
            'database'  => env('DB_DATABASE', 'forge'),
            'username'  => env('DB_USERNAME', 'forge'),
            'password'  => env('DB_PASSWORD', ''),
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
        ],

        'testing' => [
            'driver'   => 'sqlite',
            'database' => ':memory:',
            'prefix'   => '',
        ],

    ],
```

`doctrine.php`

``` php
'managers'                  => [
        'default' => [
            'dev'        => env('APP_DEBUG'),
            'meta'       => env('DOCTRINE_METADATA', 'annotations'),
            'connection' => env('DB_CONNECTION', 'mysql'),
            'namespaces' => [
                'App\Entities'
            ],
            'paths'      => [
                base_path('app/Entities')
            ],
```

`phpunit.xml`

``` xml
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="QUEUE_DRIVER" value="sync"/>
        <env name="DB_CONNECTION" value="testing"/>
    </php>
```
