### ISSUE TITLE
Conflict with symfony/validator,Semantical Error

### ISSUE THREAD

**Issue by visonforcoding** [laravel-doctrine/orm#521]
### Package version, Laravel version

laravel-doctrine/orm": "^1.6",

"laravel/lumen-framework": "^7.2",

### Expected behaviour

```php
use Symfony\Component\Validator\Constraints as Assert;

class PushInfo
{
    /**
     * 
     * @var string
     * @Assert\NotBlank()
     */
    protected $bizId;
}

$va = sfvalidation();
        $errors = $va->validate($pushInfo);

can work
```

### Actual behaviour

 i got a exception `[Semantical Error] The annotation \"@Symfony\\Component\\Validator\\Constraints\\NotBlank\" in property App\\Utils\\HllPush\\PushInfo::$bizId was never imported. Did you maybe forget to add a \"use\" statement for this annotation?`

### Steps to reproduce the behaviour

when i delete `DoctrineServiceProvider`

<img width="662" alt="image" src="https://user-images.githubusercontent.com/4387302/156482104-d82c5bb2-dd76-4ab1-b48d-2aba911b6ba4.png">

it can work right!

**Comment by eigan** [comment]
Which version of symfony/validator are you using?

**Comment by visonforcoding** [comment]
> Which version of symfony/validator are you using?

v5.3.10

**Comment by eigan** [comment]
This might have been related to #537. Did you solve it somehow, or could you try update extensions or acl if you use those?

**Comment by TomHAnderson** [comment]
Annotations are no longer supported >= 3.0
