### ISSUE TITLE
[BUG]Config publish error

### ISSUE THREAD

**Issue by zhalil** [laravel-doctrine/orm#534]
[BUG]

### clean install
1) composer create-project laravel/laravel example-app
2) cd example-app
3)composer require laravel-doctrine/orm
4)add to config/app.php : 
LaravelDoctrine\ORM\DoctrineServiceProvider::class,
'EntityManager' => LaravelDoctrine\ORM\Facades\EntityManager::class,
'Registry'      => LaravelDoctrine\ORM\Facades\Registry::class,
'Doctrine'      => LaravelDoctrine\ORM\Facades\Doctrine::class,
5)php artisan vendor:publish --tag="config" --provider="LaravelDoctrine\ORM\DoctrineServiceProvider"
and on this error:
In ProviderRepository.php line 149:                                                                                  
Call to undefined method LaravelDoctrine\ORM\Facades\EntityManager::isDeferred()

**Comment by dpslwk** [comment]
works fine for me

note the `config/app.php` steps are no longer needed since auto discover picks them up
