### ISSUE TITLE
Subscriber/Listener does not exist.

### ISSUE THREAD

**Issue by Mircea-Ciuchea** [laravel-doctrine/orm#54]
I'm trying to register a event listener and I get InvalidArgumentException. The class does not exist.
Same thing trying to use subscribers.

**Comment by patrickbrouwers** [comment]
Would be helpful if you could supply your config for events here ;)

**Comment by Mircea-Ciuchea** [comment]
```php
'events'     => [
    'listeners'   => [Doctrine\ORM\Events::onFlush => CustomAppName\Listeners\UserListener::class],
    'subscribers' => []
]

**Comment by patrickbrouwers** [comment]
Are you on `~1.0` ?

**Comment by Mircea-Ciuchea** [comment]
I'm on dev-master. I'll update to 1.0 see if it fixes this.

**Comment by patrickbrouwers** [comment]
Dev-master is unstable branch. Always stay on stable tags! :)

**Comment by Mircea-Ciuchea** [comment]
It works! Thanks!
