### ISSUE TITLE
[QUESTION] Installation of 1.8 to Laravel 9.5.2 failed

### ISSUE THREAD

**Issue by fpolli** [laravel-doctrine/orm#551]
### Package version, Laravel version
1.8/9.5.2

Because of another issue I had, I decided to try installing Laravel-Doctrine into a clean install of Laravel and see if my issue did not recur.

I created the laravel 9.5.2 project with composer and all went well. I then cd into the project folder and run:

composer require laravel-doctrine/orm

and this was the output:

`./composer.json has been updated
Running composer update laravel-doctrine/orm
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel-doctrine/orm[1.8.0, ..., 1.8.1] require doctrine/annotations ^1.13 -> satisfiable by doctrine/annotations[1.13.0, ..., 1.14.3].
    - laravel-doctrine/orm[1.0.0, ..., 1.0.13] require illuminate/auth ~5.1 -> found illuminate/auth[v5.1.1, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - laravel-doctrine/orm[1.0.14, ..., 1.0.21] require illuminate/auth 5.1.* -> found illuminate/auth[v5.1.1, ..., v5.1.41] but these were not loaded, likely because it conflicts with another require.
    - laravel-doctrine/orm[1.0.15, ..., 1.2.2] require illuminate/auth 5.2.* -> found illuminate/auth[v5.2.0, ..., v5.2.45] but these were not loaded, likely because it conflicts with another require.
    - laravel-doctrine/orm[1.2.3, ..., 1.2.12] require illuminate/auth 5.2.*|5.3.* -> found illuminate/auth[v5.2.0, ..., v5.3.23] but these were not loaded, likely because it conflicts with another require.
    - laravel-doctrine/orm[1.3.0, ..., 1.3.10] require illuminate/auth 5.4.* -> found illuminate/auth[v5.4.0, ..., v5.4.36] but these were not loaded, likely because it conflicts with another require.
    - laravel-doctrine/orm 1.3.8 requires illuminate/auth 5.4.* | 5.5.* -> found illuminate/auth[v5.4.0, ..., v5.5.44] but these were not loaded, likely because it conflicts with another require.
    - laravel-doctrine/orm[1.4.0, ..., 1.4.2] require illuminate/auth 5.5.* -> found illuminate/auth[v5.5.0, ..., v5.5.44] but these were not loaded, likely because it conflicts with another require.
    - laravel-doctrine/orm[1.4.3, ..., 1.4.7] require illuminate/auth 5.5.*|5.6.* -> found illuminate/auth[v5.5.0, ..., v5.6.39] but these were not loaded, likely because it conflicts with another require.
    - laravel-doctrine/orm[1.4.8, ..., 1.4.9] require illuminate/auth 5.5.*|5.6.*|5.7.* -> found illuminate/auth[v5.5.0, ..., v5.7.28] but these were not loaded, likely because it conflicts with another require.
    - laravel-doctrine/orm[v1.4.10, ..., 1.4.18] require illuminate/auth 5.5.*|5.6.*|5.7.*|5.8.* -> found illuminate/auth[v5.5.0, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - laravel-doctrine/orm[1.5.0, ..., 1.5.14] require illuminate/auth ^6.0 -> found illuminate/auth[v6.0.0, ..., v6.20.44] but these were not loaded, likely because it conflicts with another require.
    - laravel-doctrine/orm[1.5.3, ..., v1.5.8] require php ^7.2 -> your php version (8.2.2) does not satisfy that requirement.
    - laravel-doctrine/orm[1.6.0, ..., 1.6.1] require php ^7.2.5 -> your php version (8.2.2) does not satisfy that requirement.
    - laravel-doctrine/orm[1.6.2, ..., 1.6.7] require illuminate/auth ^7.0 -> found illuminate/auth[v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another require.
    - laravel-doctrine/orm[1.7.0, ..., 1.7.2] require php ^7.3 -> your php version (8.2.2) does not satisfy that requirement.
    - laravel-doctrine/orm[1.7.3, ..., 1.7.13] require illuminate/auth ^8.0 -> found illuminate/auth[v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - doctrine/annotations[1.13.0, ..., 1.13.3] require doctrine/lexer 1.* -> found doctrine/lexer[v1.0, ..., 1.2.3] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - doctrine/annotations[1.14.0, ..., 1.14.3] require doctrine/lexer ^1 || ^2 -> found doctrine/lexer[v1.0, ..., 1.2.3, 2.0.0, 2.1.0] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires laravel-doctrine/orm * -> satisfiable by laravel-doctrine/orm[1.0.0, ..., 1.8.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require laravel-doctrine/orm:*" to figure out if any version is installable, or "composer require laravel-doctrine/orm:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
`
I remember that this happened when I installed into my existing laravel project and I used -W to install. I have no idea what that did.

Thanks

**Comment by dpslwk** [comment]
either use -W as suggested
or remove the `composer.lock` file and vendor folder

just look at the output form using -W, you will likely see it just downgrades a few dependancies, there should be no issues with what it downgrades as `laravel/framework` likely allows multiple version, but new projects it will have installed a version higher than `laravel-doctrine/orm` 1.8 allows


```
  - Downgrading doctrine/instantiator (2.0.0 => 1.5.0)
  - Downgrading doctrine/lexer (3.0.0 => 2.1.0)
```

**Comment by eigan** [comment]
Try `"^2@dev"` for laravel-doctrine/orm

**Comment by dpslwk** [comment]
which php version?
just curious, it should not matter much if 8.1 or 8.2

**Comment by fpolli** [comment]
> which php version? just curious, it should not matter much if 8.1 or 8.2

I believe 8.2.



> Try `"^2@dev"` for laravel-doctrine/orm

I will try that
