### ISSUE TITLE
[BUG] Using SubstituteBindings in Lumen app shows "Target [Illuminate\Contracts\Routing\Registrar] is not instantiable while building [LaravelDoctrine\ORM\Middleware\SubstituteBindings]"

### ISSUE THREAD

**Issue by RobQuistNL** [laravel-doctrine/orm#553]
Please prefix your issue with one of the following: [BUG] [PROPOSAL] [QUESTION].

### Expected behaviour
Getting routes with entities in there resolved nicely.

### Actual behaviour
When adding the `LaravelDoctrine\ORM\Middleware\SubstituteBindings` middleware in the routeMiddleware, we get the following error:

Illuminate\Contracts\Container\BindingResolutionException
```
Target [Illuminate\Contracts\Routing\Registrar] is not instantiable while building [LaravelDoctrine\ORM\Middleware\SubstituteBindings].
```

When we don't have this middleware, the URL resolves, but receives an uninitialized object;
```
Typed property App\Models\Location\Building::$id must not be accessed before initialization
```

**Comment by TomHAnderson** [comment]
Lumen is not supported past version 2.0 of this library.  If you have a fix for this, a release on 2.0 would be in order.
