### ISSUE TITLE
MappingDriverChain causes incompatibility with simplified Xml / simplified Yaml metadata drivers

### ISSUE THREAD

**Issue by matthew-james** [laravel-doctrine/orm#57]
Hello,

In [this method](https://github.com/laravel-doctrine/orm/blob/1.0/src/Extensions/MappingDriverChain.php#L41) `addPaths` is called on the returned `FileLocator`.  

The issue is that `addPaths` is not defined on the `FileLocator` interface.  This is not a problem on the locators returned by the included drivers but is incompatible with the `SymfonyFileLocator` returned by the `SimplifiedXmlDriver` and the `SimplifiedYamlDriver`.

**Comment by nnn406** [comment]
Hi, could you please clarify: What the right way to specify in config file `doctrine.php` to use `Simplified YAML Driver` ??

**Comment by matt-allan** [comment]
Specifying `'meta' => 'simplified_yaml'` should work.

**Comment by nnn406** [comment]
No it does not work. Actually I've tried to debug and during debug i've found that 
`'meta' => 'SimplifiedYaml'` helps to load appropriated driver, but there is another problem

this is my config

```
 'managers'                  => [
        'default' => [
            'dev'        => env('APP_DEBUG'),
            'meta'       => env('DOCTRINE_METADATA', 'SimplifiedYaml'),
            'connection' => env('DB_CONNECTION', 'mysql'),
            'paths'      => [
                /*'Domain\\Company\\Entity\\' =>*/ base_path('Infrastructure/Doctrine/ORM')
            ],
            'repository' => Doctrine\ORM\EntityRepository::class,
..
```

this is what I have in log file:

```
exception 'Doctrine\Common\Persistence\Mapping\MappingException' with message 'No mapping file found named 'Company.orm.yml' for class 'Domain\Company\Entity\Company'.' in /home/vagrant/Code/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:75
```

but file is there

```
❯ ls  Infrastructure/Doctrine/ORM 
Company.orm.yml 
```

And this is what I see if I run `doctrine:info`

```
❯ php artisan doctrine:info

  [Doctrine\Common\Persistence\Mapping\MappingException]                                                  
  File mapping drivers must have a valid directory path, however the given path 0 seems to be incorrect!  

```

from digging in the code, I understood that I need to specify path as a key, I've tried that, but it does not work. Everything stuck on that method `addNamespacePrefixes`. It expect that in `$prefixes` will be key-based array, where key is a path. And then `loadMetadata` and `loadMetadataForClass` does not work as expected. In  `findMappingFile` I have two items in `$this->path` and `$this->prefixes` (http://bit.ly/1JxbCV1) which is weird. And it following step `throw MappingException`

If I use usual yaml driver, everything works great.

**Comment by matt-allan** [comment]
Hi,

Thanks for the detailed reproduction steps.  I just pushed an example that should make usage a little clearer.

The config should be an associative array where `path` => `namespace`, like this:

```
 'managers'                  => [
        'default' => [
            'meta'       => 'simplified_yaml',
            'paths'      => [
                base_path('mappings') => 'App\Domain'
            ],
            // more stuff
            ],
```

[example](https://github.com/matthew-james/laravel-doctrine-example/blob/master/config/doctrine.php)

Then the mapping file should be named like `MyClassName.orm.yml`, and you don't need the namespace because you specified it in  the paths.  In example, `App\Domain\User` would have a mapping file called `User.orm.yml`

```
// mappings/User.orm.yml
App\Domain\User:
  type: entity
  table: users
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
```

[example mapping file](https://github.com/matthew-james/laravel-doctrine-example/blob/master/mappings/User.orm.yml) for [this entity](https://github.com/matthew-james/laravel-doctrine-example/blob/master/app/Domain/User.php)

Let me know if that helps.

**Comment by nnn406** [comment]
Thanks @matthew-james It works!! 

But one small note, How could I satisfy following case: 
I would like to have the same place for mapping files
`base_path('mappings')`

but each different yaml might be pointed to entity from different folders.

In my example I have entities `User` and `Company` in following folders:

```
User -> Domain/User/Entity/User.php
Company -> Domain/Company/Entity/Company.php
```

But all map files should stay in the same place - `Infrastructure/Doctrine/ORM`

Is it possible ? Can I have like that:

```
base_path('mappings') => [
    'Domain\\User\\Entity',
    'Domain\\Company\\Entity'
]
```

Thanks.

**Comment by matt-allan** [comment]
You would need to redeclare the mapping path for each namespace, like this:

```
'paths' => [
    base_path('mappings') => 'Domain\User\Entity',
    base_path('mappings') => 'Domain\Company\Entity',
],
```

I think you could also declare `base_path('mappings') => 'Domain'` and name
your files like `User.Entity.User.orm.yml` if you don't want to map each
namespace.

**Comment by nnn406** [comment]
@matthew-james Ok thanks, I'll try.
