### ISSUE TITLE
[BUG], error during installation, need to update dependencies

### ISSUE THREAD

**Issue by bizzyswift** [laravel-doctrine/orm#577]
### Package version, Laravel version
11

### Expected behaviour
The package installation completes correctly.

### Actual behavior
Installation failed
Problem 1
    - doctrine/orm[2.14.0, ..., 2.14.3] require doctrine/lexer ^1.2.3 || ^2 -> found doctrine/lexer[1.2.3, 2.0.0, 2.1.0, 2.1.1] but the package is fixed to 3.0.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - doctrine/orm[2.15.0, ..., 2.17.5] require doctrine/lexer ^2 -> found doctrine/lexer[2.0.0, 2.1.0, 2.1.1] but the package is fixed to 3.0.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires laravel-doctrine/orm ^2.1 -> satisfiable by laravel-doctrine/orm[2.1.0].
    - carbonphp/carbon-doctrine-types 3.2.0 conflicts with doctrine/dbal 3.8.7.
    - doctrine/orm[2.18.0, ..., 2.19.6] require doctrine/dbal ^2.13.1 || ^3.2 -> satisfiable by doctrine/dbal[2.13.1, ..., 2.13.9, 3.2.0, ..., 3.8.7].
    - nesbot/carbon 3.7.0 requires carbonphp/carbon-doctrine-types * -> satisfiable by carbonphp/carbon-doctrine-types[3.2.0].
    - symfony/http-foundation v7.1.3 conflicts with doctrine/dbal 3.5.4.
    - symfony/http-foundation v7.1.3 conflicts with doctrine/dbal 3.4.6.
    - symfony/http-foundation v7.1.3 conflicts with doctrine/dbal 3.3.8.
    - symfony/http-foundation v7.1.3 conflicts with doctrine/dbal 3.3.5.
    - symfony/http-foundation v7.1.3 conflicts with doctrine/dbal 3.2.2.
    - symfony/http-foundation v7.1.3 conflicts with doctrine/dbal 2.13.9.
    - symfony/http-foundation v7.1.3 conflicts with doctrine/dbal 2.13.8.
    - symfony/http-foundation v7.1.3 conflicts with doctrine/dbal 2.13.1.
    - laravel/framework v11.20.0 requires nesbot/carbon ^2.72.2|^3.0 -> satisfiable by nesbot/carbon[3.7.0].
    - laravel/framework v11.20.0 requires symfony/http-foundation ^7.0 -> satisfiable by symfony/http-foundation[v7.1.3].
    - laravel-doctrine/orm 2.1.0 requires doctrine/orm ^2.14 -> satisfiable by doctrine/orm[2.14.0, ..., 2.19.6].
    - laravel/framework is locked to version v11.20.0 and an update of this package was not requested.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### Steps to reproduce the behavior
will install a new version of laravel
and install laravel-doctrine/orm:^2.1

**Comment by eigan** [comment]
Downgrade doctrine/orm to 2.x

**Comment by TomHAnderson** [comment]
3.0.0 has been released with ORM 3, DBAL 4 support.
