### ISSUE TITLE
FileLogger is not Lumen compatible

### ISSUE THREAD

**Issue by matt-allan** [laravel-doctrine/orm#62]
The FileLogger requires an instance of `Illuminate\Contracts\Logging\Log`.  [Lumen only registers an implementation of 'Psr\Log\LoggerInterface`](https://github.com/laravel/lumen-framework/blob/5.1/src/Application.php#L629).

The laravel log writer also [implements the PSR interface](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Log/Writer.php) so switching the interface typehint _should_ work correctly.

**Comment by patrickbrouwers** [comment]
If Laravel also binds the logger to that interface inside ioC, then I'm fine with changing this.

**Comment by matt-allan** [comment]
Laravel binds an implementation of the PSR LoggerInterface [here](https://github.com/laravel/framework/blob/a423a55ed6601daebcbb75817de6d06b4d670a70/src/Illuminate/Foundation/Bootstrap/ConfigureLogging.php#L35).
