### ISSUE TITLE
Enable lazy database connection initialization

### ISSUE THREAD

**Issue by martio** [laravel-doctrine/orm#648]
Hi,

can lazy database connection initialization be implemented? Currently, a database connection is established for every `php artisan ...` command, even if the command does not require database access.

Best regards! :blush:

**Comment by TomHAnderson** [comment]
Lazy database connections work as expected outside artisan commands, yes?

**Comment by martio** [comment]
@TomHAnderson Everything is fine if you don't use extensions. When you apply any extension, e.g., for timestamps or soft deletes, the connection to the database occurs in the Provider. If you don't use extensions, we have lazy connections. And that's fine.

**Comment by TomHAnderson** [comment]
I'm open to a PR to address this.

**Comment by martio** [comment]
@TomHAnderson, I debugged this issue once again, and it’s not about registering extensions but about registering custom types. I apologize for the confusion.

When we have some custom types to register provided in the configuration file, e.g.:

```php
'mapping_types' => [
    'enum' => 'string',
],
```

or

```php
'custom_types' => [
    'datetime_immutable' => Carbon\Doctrine\DateTimeImmutableType::class,
    'datetime' => Carbon\Doctrine\DateTimeType::class,
],
```

then `LaravelDoctrine\ORM\EntityManagerFactory`, in the `registerMappingTypes` method, tries to establish a connection in order to register the types.

It would be great if this could somehow be delayed... :wink:

Best regards! :blush:

**Comment by TomHAnderson** [comment]
The Doctrine documentation says you must have a connection in order to register types:
https://www.doctrine-project.org/projects/doctrine-orm/en/3.3/cookbook/custom-mapping-types.html
(function registerDoctrineTypeMapping)

And you can't call the connection without having a connection.  If you feel this is wrong you should follow up with the Doctrine team.
