### ISSUE TITLE
Doctrine Paginator foreach not working

### ISSUE THREAD

**Issue by reyezJelle** [laravel-doctrine/orm#70]
After the latest changes the following example code stopped working:

```
<?php namespace App\Http\Controllers;

use Illuminate\Routing\Controller as BaseController;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityManager;
use App\Repositories\Entities\Product;

class TestController extends BaseController
{

    private $product;

    public function __construct(EntityManager $em, Product $product)
    {
        $this->product = $product;
        $this->em = $em;
    }

    public function index()
    {
        $dql = "SELECT p FROM App\\Repositories\\Entities\\Product p ";
        $query = $this->em->createQuery($dql)
                          ->setFirstResult(0)
                          ->setMaxResults(100);
        $paginator = new Paginator($query, $fetchJoinCollection = true);
        $c = count($paginator);

        foreach( $paginator as $post )
        {
            dd($post, 2);
        }
    }

}
```

**Comment by patrickbrouwers** [comment]
It would be useful if you could supply the exception. 

Are you using a tagged release?

**Comment by reyezJelle** [comment]
There is no exception, the foreach is just not looping. I've pulled a previous version and there this code was working and showed the result of dd($post,2); 

I'm using "laravel-doctrine/orm": "dev-master",

**Comment by patrickbrouwers** [comment]
Never use dev-master. It contains potential breaking changes or incomplete features.

Btw did you see in the documentation we have cleaner syntax for pagination?

**Comment by reyezJelle** [comment]
Thank you, I have seen the code. The code was rushed a bit. 

I've reverted to 1.0.5 for now.

**Comment by patrickbrouwers** [comment]
1.0.5 is the latest stable release, so that's fine. 
Thanks for using the package!
