### ISSUE TITLE
DQL getSingleResult and getOneOrNullResult are not working correctly

### ISSUE THREAD

**Issue by linaspasv** [laravel-doctrine/orm#75]
Hello,

today I learned that DQL getSingleResult or getOneOrNullResult functions do not work as expected. Example source code:

``` php
$package = EM::createQuery("SELECT p FROM Entity\Package p WHERE p.minCourses <= :courses AND (p.maxCourses >= :courses OR p.maxCourses IS NULL)")
             ->setParameter('courses', $courseCount)
             ->setMaxResults(1)
             ->getSingleResult();
```

Instead of getting a single Entity, I am receiving result wrapped in Illuminate/Support/Collection. I was digging deeper in the source code and it looks like the following source code fails in Doctrine\ORM\AbstractQuery 

``` php
if ( ! is_array($result)) {    // <-- $result here is Illuminate/Support/Collection object
     return $result;
}
```

Would it be possible to have an option in the config file to use array instead of Illuminate/Support/Collection for the result set?

Looking forward!

Best regards,
Linas Pašviestis

**Comment by patrickbrouwers** [comment]
If you are using dev-master by accident, you should definitely go and use ~1.0 stable and tagged release.

If you were just testing, thanks! Still some small problems with Collections indeed, didn't have the time to get them all out. But that's why they are not in the stable branch ;)

**Comment by linaspasv** [comment]
Thanks Patrick for a quick response. Keep up the good work! Cheers :)
