### ISSUE TITLE
ReplaceQueryParams causes htmlentities() throws ErrorException when param is an array

### ISSUE THREAD

**Issue by 0x9be00ff1** [laravel-doctrine/orm#76]
Doctrine EntityRepositorysupports passing arrays as values to a field and uses an IN query since 2.1
http://www.doctrine-project.org/2011/07/04/doctrine-2-1.html

When I use

```
 $queryBuilder = where('i.id IN (:ids)')
            ->setParameter('ids', $ids)
```

and enable laravel-doctrine logger 

LaravelDoctrine\ORM\Loggers\Formatters\ReplaceQueryParams convertParam passes the $ids array to htmlentities directly.

**Comment by patrickbrouwers** [comment]
If Doctrine supports it, I will add it. 
The way I normally use it (and feels more save) is:

``` php
$builder->where($builder->expr()->in('i.id', ':ids'));
$builder->setParameter('ids', $ids);
```
