### ISSUE TITLE
How would I go back integrating fixtures?

### ISSUE THREAD

**Issue by EwanValentine** [laravel-doctrine/orm#79]
Me again,

Sorry, the title should have been 'How would I go about integrating fixtures'. 

I'd like to replace my Laravel seed data with doctrine fixtures, I can't see any configuration options for supporting this. What would be the best approach? Or would I just use the EntityManager within my existing seeds?

Cheers!

**Comment by patrickbrouwers** [comment]
Actually on my planning to let the seeder run on the doctrine connection. But for now I'd suggest just using the EntityManager.

**Comment by EwanValentine** [comment]
Okay great, thanks!
