### ISSUE TITLE
Password reset broken

### ISSUE THREAD

**Issue by izziaraffaele** [laravel-doctrine/orm#83]
I'm getting this error

```
ErrorException in DoctrineTokenRepository.php line 132:
Argument 1 passed to LaravelDoctrine\ORM\Auth\Passwords\DoctrineTokenRepository::reminderExpired() must be an instance of LaravelDoctrine\ORM\Auth\Passwords\PasswordReminder
```

This is apparently because getOneOrNullResult() returns Illuminate\Support\Collection instead of the expected single entity.

**Comment by patrickbrouwers** [comment]
Please don't use dev-master, we tag stable (`1.0.*`) releases with a reason.

**Comment by izziaraffaele** [comment]
Ops, that's true!! Apparently that's what I've got as default doing composer require so you might have to fix something in your package anyways ;)

**Comment by patrickbrouwers** [comment]
When I run `composer require laravel-doctrine/orm` I get `1.0.7`. Maybe you have some `minimum-stability: dev` setting in your composer.json ?

**Comment by izziaraffaele** [comment]
yes but I also have `prefer-stable` set to `true` so it should grab 1.0.7 anyways. At least that is what it does with the rest of the packages.

**Comment by patrickbrouwers** [comment]
When did you do composer require? Recently or before the 1.0 release? (+- 1,5 month ago)

**Comment by izziaraffaele** [comment]
Just 22 hours ago when I wrote the issue :)

**Comment by patrickbrouwers** [comment]
Confirms my hatred over composer require -_- .
