### ISSUE TITLE
[1.1] Add yaml/xml/config mappings to quickstart repo

### ISSUE THREAD

**Issue by patrickbrouwers** [laravel-doctrine/orm#90]
The quickstart repo already has the Fluent and annotations mappings. Examples for yaml, xml, config and php driver should also be present.

@FoxxMD Yaml is for you?

**Comment by dave-redfern** [comment]
@patrickbrouwers If you want some pre-rolled code, I have a basic Laravel-Doctrine project repo you are free to borrow from.

mapping files: https://github.com/dave-redfern/laravel-doctrine-project/tree/master/config/mappings/core
entities: https://github.com/dave-redfern/laravel-doctrine-project/tree/master/app/Entities

**Comment by patrickbrouwers** [comment]
@dave-redfern thanks
