### ISSUE TITLE
[1.1] Mapping files for password resets and failed jobs for all drivers

### ISSUE THREAD

**Issue by patrickbrouwers** [laravel-doctrine/orm#91]
Currently yaml, xml and fluent mapping files are missing for password resets and failed jobs.

Optimally it should become a console command which publishes the right entity and mapping file

**Comment by FoxxMD** [comment]
Current progress can be found at https://github.com/laravel-doctrine/orm/tree/passwordAndQueueMappingsSupport

**Comment by patrickbrouwers** [comment]
No longer necessary since 1.2.0
