### ISSUE TITLE
[1.1] Integration testing tools

### ISSUE THREAD

**Issue by patrickbrouwers** [laravel-doctrine/orm#92]
Laravel has some useful testing tools like `seeInDatabase` but this runs on the Laravel connection. Perhaps we could provide Doctrine implementation for this.

**Comment by guiwoda** [comment]
IMHO easy mocking of the Doctrine API would be better than actual DB querying. I wouldn't want to be the one recommending integration tests with databases as the standard way of testing with this library.

**Comment by patrickbrouwers** [comment]
I actually found for easy end-to-end testing of stuff like API's, it was extremely easy to do, without needing to mock a lot of querying stuff.

**Comment by patrickbrouwers** [comment]
To summarise our Slack chat:
- Investigate how we can both provide Integration and mocking helpers for Doctrine testing
- Add a section to the docs with information about testing Doctrine parts: first part would be mocking repo's, etc., second part would be how the integration testing would work.

**Comment by maxbrokman** [comment]
I think at the least it might be worth providing replacements for Laravel's migrations, transactions and `seeInDatabase` helpers

**Comment by patrickbrouwers** [comment]
Should no longer be necessary since 1.2.0, as we share the connection with Laravel. If anyone needs something extra, please submit a PR for some doctrine testing trait :)

**Comment by AJenbo** [comment]
Is this still true for Lumen? I simply get a "no such table" when trying to use seeInDatabase(). Do i need to do some additional bindings?

**Comment by AJenbo** [comment]
The following workaround makes the test pass, but that looks to confirm  that the connection isn't shared :/
```
        $connection = app('em')->getConnection()->getWrappedConnection();
        app('db')->setPdo($connection);
```
