### ISSUE TITLE
[1.1] Run seeders on Doctrine connection

### ISSUE THREAD

**Issue by patrickbrouwers** [laravel-doctrine/orm#93]
Currently you can use seeders, but you have to use the EntityManager instead of an easy array of input.

Example code:

```
$connection = $this->container['registry']->getConnection('testing');
$connection->insert('table', [
    'name' => 'value'
]);
```

**Comment by FoxxMD** [comment]
Doctrine doesn't support seeding natively (anymore) right? There are packages for seeding like [DoctrineFixtures](https://symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html) and [Alice](https://github.com/nelmio/alice) but neither provide that kind of generic input you have in the example.

Am I confusing functionality? Fixtures !== seeders?

**Comment by patrickbrouwers** [comment]
Seeder -> just put data in the table (generic)
Fixture -> generated data, then seed to table

**Comment by cniska** [comment]
Maybe you could add a fixture command similar to ours at https://github.com/nordsoftware/lumen-doctrine/blob/develop/src/Console/FixturesLoadCommand.php

**Comment by josenicomaia** [comment]
What about injecting the EntityManager instead? The __construct DI keeps working.

```
private $em;

public function __construct(EntityManagerInterface $em) {
  $this->em = $em;
}

public function run() {
  $object = new FooBarEntity('Foo', 'Bar');
  $this->em->persist($object);
  $this->em->flush();
}
```

**Comment by patrickbrouwers** [comment]
You can indeed, but it gives some overhead. Inserting an array of data is faster.

**Comment by josenicomaia** [comment]
Hmm. I got it.

**Comment by patrickbrouwers** [comment]
Closing this in favour of using Laravel default seeding functionality. Since 1.2.0 were are sharing the same connection with Laravel, meaning we can use all DB functionality too.

**Comment by drmmr763** [comment]
I'm sure this will work for laravel since you have the entire DB functionality as mentioned. What about for lumen when eloquent isn't even included? Would the suggestion be to go forward with entity manager persisting?
