### ISSUE TITLE
[1.1] Generate:entity command

### ISSUE THREAD

**Issue by patrickbrouwers** [laravel-doctrine/orm#95]
Generate entity command is missing

**Comment by patrickbrouwers** [comment]
@maxbrokman something for you?

**Comment by ahmedali5530** [comment]
hi,
why can't we use this command in laravel nor in doctrine standalone installation, is it only available by symfony? 
I searched in doctrine documentation but could not find this command.

**Comment by patrickbrouwers** [comment]
We have it now: https://github.com/laravel-doctrine/orm/blob/1.1/src/Console/GenerateEntitiesCommand.php

**Comment by ahmedali5530** [comment]
Hi @patrickbrouwers thanks for reply, but this command is different from doctrine:generate:entity command, have a look at this page [http://symfony.com/doc/current/book/doctrine.html#creating-an-entity-class](url) as this command provides a wizard like structure for generating entities. I have used it in symfony but unable to find in this package.
![image](https://cloud.githubusercontent.com/assets/4495669/13563284/50574422-e462-11e5-8665-80d69d035c94.png)

this is the picture of wizard which this command provides.

**Comment by patrickbrouwers** [comment]
Feel free to PR it. For me personally it has no priority to implement.
