### ISSUE TITLE
No EntityManager is set-up for

### ISSUE THREAD

**Issue by tofarias** [laravel-doctrine/orm#99]
Hi. In "config/auth" I have this:

'driver' => 'doctrine',
'model' => Domain\Usuarios\Entities\User::class,

---

In "Domain\Usuarios\Entities\User.php" I have this:

<?php namespace Domain\Usuarios\Entities;

use Doctrine\ORM\Mapping as ORM;

/**
- Users
  *
- @ORM\Table(name="users", indexes={@ORM\Index(name="fk_users_1_idx", columns={"group_id"})})
- @ORM\Entity
  */
  class User implements \LaravelDoctrine\ORM\Contracts\Auth\Authenticatable
  {
  
  use \LaravelDoctrine\ORM\Auth\Authenticatable;
  
  /**
  - @var integer
    *
  - @ORM\Column(name="id", type="integer", nullable=false)
  - @ORM\Id
  - @ORM\GeneratedValue(strategy="IDENTITY")
    */
    private $id;
    ----------------------------------------------------------------------------------

But I get this error: "No EntityManager is set-up for Domain\Usuarios\Entities\User", why?

**Comment by sisve** [comment]
Could you show us a stack-trace for the error?

**Comment by tofarias** [comment]
Hi, here: 

![config-auth](https://cloud.githubusercontent.com/assets/7261216/11037081/1fee39c6-86e3-11e5-9bd5-783b4a60a54b.PNG)
![domain-usuarios-entities-user](https://cloud.githubusercontent.com/assets/7261216/11037082/200d8e2a-86e3-11e5-966e-c9dfa2580bb3.PNG)
![config-doctrine](https://cloud.githubusercontent.com/assets/7261216/11037083/2012cb56-86e3-11e5-9768-da8a97760d78.PNG)
![no-entity-manager](https://cloud.githubusercontent.com/assets/7261216/11037084/202a3fde-86e3-11e5-8b12-06eaf4fb9e78.PNG)

**Comment by patrickbrouwers** [comment]
If your entities are in `domain` you have to tell the Entity Manager about that. 
In config file `doctrine.php` change `paths` to `base_path('domain')`

**Comment by tofarias** [comment]
Ok, it's works! but I got a new error: 

![maximum_function_nesting](https://cloud.githubusercontent.com/assets/7261216/11043103/3aa319e8-8702-11e5-877f-945e89548591.PNG)

**Comment by patrickbrouwers** [comment]
Google is your friend, mate ;) http://stackoverflow.com/questions/8656089/solution-for-fatal-error-maximum-function-nesting-level-of-100-reached-abor?answertab=votes#tab-top

**Comment by tofarias** [comment]
Ok, thanks.
